### PR TITLE
Fixes `inspect`

### PR DESCRIPTION
**Pull request by karsa-mistmere**
image

### CODE REVIEW

**Comment by ericfennis** [comment]
The only change I see is the gap, that's a bit bigger. Is this change needed?
What do you think @mittalyashu ?

**Comment by karsa-mistmere** [comment]
It's probably not critical, it's a very minor violation:
image

**Comment by mittalyashu** [comment]
Yup, LGTM 🙂

**Comment by karsa-mistmere** [comment]
@mittalyashu: But doesn't having a 2px spacing at 2x already ensure that? I mean if you have 2px at 2px, then you would have `2px - 2 * 0.5px = 1px` at 3 px (as long as corners have round, not miter joins, which of course they do).

**Comment by lscheibel** [comment]
While we're at it: Do you guys think we could remove the "stem" of the pointer? In my opinion it only adds visual noise.

**Comment by karsa-mistmere** [comment]
I think I agree with @lscheibel, the stem is maybe a bit too much, what about a complete redesign like this?
(This would not only fix the spacing issue and make the pointer pixel perfect, but also make it consistent in size and spacing with `square`).

image
inspect

**Comment by karsa-mistmere** [comment]
@ericfennis Thanks, I've updated the PR.

**Review by ericfennis — APPROVED** [review]

**Comment by mittalyashu** [comment]
LGTM, thank you guys.

**Comment by mittalyashu** [comment]
Do you think we need to match the cursor icon [with this](https://lucide.dev/icon/mouse-pointer-2?search=cursor)?

**Comment by karsa-mistmere** [comment]
I think aiming for pixel perfection and cleanliness is more important in this instance, generally speaking, the shape is not very different and is pretty much only adjusted for changes in density because of the size difference.

**Comment by karsa-mistmere** [comment]
@mittalyashu For demonstration, here's the difference between `inspect`'s (green) and `mouse-pointer-2`'s (magenta) cursor:
image

**Pull request merged**
