### PR TITLE
fix: cogs

### PR DESCRIPTION
**Pull request by jguddas**
- replace small cogs that don't work with 3px stroke width.
- changed cogs, so they are consistent and circularly symmetrical.

### CODE REVIEW

**Comment by jguddas** [comment]
I rotated it for the `brain-cog` icon 33°, what about doing that for all icons?

**Review by ericfennis — COMMENTED** [review]
Nice this looks better. Why is the `folder-cog-2` icon removed?

**Comment by jguddas** [comment]
> Nice this looks better. Why is the `folder-cog-2` icon removed?

It doesn't fit, it would have to be something like this icon (74) to get it to work.

**Comment by jguddas** [comment]
With them being rotated they are sadly less sharp, should I rotate them back?

**Comment by ericfennis** [comment]
@jguddas Can you post a side-by-side comparison image?

**Comment by jguddas** [comment]
> @jguddas Can you post a side-by-side comparison image?

image

**Comment by ericfennis** [comment]
@jguddas Hmm to me actually your changes look the best

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
