### PR TITLE
Add `activity-square` icon

### PR DESCRIPTION
**Pull request by danielbayley**

### CODE REVIEW

**Review by ericfennis — APPROVED** [review]
Nice icon!

**Review by jguddas — APPROVED** [review]
Love it :heart:

**Comment by karsa-mistmere** [comment]
It feels a bit skewed, maybe something like this would have been better?
image
image

**Comment by danielbayley** [comment]
> It feels a bit skewed, maybe something like this would have been better?

@karsa-mistmere I can’t tell, is that .5px difference? Tweak it in another PR if you like…

**Pull request merged**
