### PR TITLE
feat(icons): added `bangladeshi-taka` icon

### PR DESCRIPTION
**Pull request by mayeenulislam**
## What is the purpose of this pull request?
- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description
Adding a new icon: "Bangladeshi Taka"

- BDT
- ৳
- ISO 4217
- Unicode: U+09F3

### Icon use case
A real-life currency &mdash; also used as Money, Shopping, Discount

### Alternative icon designs
No alternative icon designs. It's the universal "Taka" icon

### Concept

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: indian-rupee, badge-indian-rupee, receipt-indian-rupee
- [ ] I've based them on the following design: 

### Naming

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
Hi @mayeenulislam,

I'm afraid these have several guideline violations, please make sure to more closely follow our [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide).

The main issues that need to be addressed:
- Not all elements have 2px gaps between them (especially for the `receipt` and `badge` versions), see guideline no. 8\
  (Not sure, if this makes the small versions feasible or not)
- The icons do not stick to the grid, leading to blurry lines, see our DPI preview and guideline no. 13
- There are some really uneven curves, can we maybe try a more geometric approach? (guideline no. 12)

More Lucide-ey proposas, based on Google image search (but I'm totally unsure if they're recognisable or good enough):

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M14+16c.358-.518.895-1+2-1a2+2+0+0+1+2+2+4+4+0+0+1-8+0V5a2+2+0+0+0-4+0%22+/%3E%3Cpath+d=%22M6+9h11%22+/%3E">icons<br/>Open lucide studio</a> 

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M3.85+8.62a4+4+0+0+1+4.78-4.77+4+4+0+0+1+6.74+0+4+4+0+0+1+4.78+4.78+4+4+0+0+1+0+6.74+4+4+0+0+1-4.77+4.78+4+4+0+0+1-6.75+0+4+4+0+0+1-4.78-4.77+4+4+0+0+1+0-6.76%22+/%3E%3Cpath+d=%22M9+11h3.5%22+/%3E%3Cpath+d=%22M9+8a2+2+0+0+1+2+2v3.5a1+1+0+0+0+5+0+1.4+1.4+0+0+0-.14-.605%22+/%3E">icons<br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M4+2v20l2-1+2+1+2-1+2+1+2-1+2+1+2-1+2+1V2l-2+1-2-1-2+1-2-1-2+1-2-1-2+1z%22+/%3E%3Cpath+d=%22M9+11h3.5%22+/%3E%3Cpath+d=%22M9+8a2+2+0+0+1+2+2v3.5a1+1+0+0+0+5+0+1.4+1.4+0+0+0-.14-.605%22+/%3E">icons<br/>Open lucide studio</a>

**Comment by jguddas** [comment]
We should maybe think about the currency icons, we basically have the same issues here as we do with the brand icons where we try to shoehorn existing possibly copyrighted work into our design guidelines.

For example `€`:
[The European Community, represented by the European Commission, owns the copyright for the euro symbol.](https://european-union.europa.eu/institutions-law-budget/euro/design_en#:~:text=The%20European%20Community%2C%20represented%20by%20the%20European%20Commission%2C%20owns%20the%20copyright%20for%20the%20euro%20symbol.)

**Comment by mayeenulislam** [comment]
@karsa-mistmere I've revised the design, as far as I understood your design guidelines and the previous icons that you already have merged. I did not find any dedicated pull request on "Indian Rupee", hence could not measure the deviations.
With these changes, the stroke widths improved.

BTW, about the DPI (24px) I checked the Rupee symbols in Figma and the symbols that I designed. In the 1px grid, they completely matched in many ways.

Given my current understanding, I believe these modifications will align the design with the guidelines.

**Comment by karsa-mistmere** [comment]
> @karsa-mistmere I've revised the design, as far as I understood your design guidelines and the previous icons that you already have merged. I did not find any dedicated pull request on "Indian Rupee" (except #1401), and I could not measure the deviations. With these changes, the stroke widths improved.
> 
> BTW, about the DPI (24px) I checked the Rupee symbols in Figma and the symbols that I designed. In the 1px grid, they completely matched in many ways.
> 
> Given my current understanding, I believe these modifications will align the design with the guidelines.

I'm afraid every concern raised in my original review still stands: the vertical lines are off grid, gaps are too small, curvatures are uneven (especially for the base icon).

**Comment by mayeenulislam** [comment]
@karsa-mistmere I've updated the Icons once again. Pardon me, would love to have another final review.
If not up to the mark, I might discard the pull request by myself.

**Comment by arifulbfd** [comment]
there are lots of people use lucid but they cannot use bangladeshi-taka to bdt icon. what should we do, remove all branch so i could add new one.

**Pull request closed without merging**
