### PR TITLE
added gizmo icon

### PR DESCRIPTION
**Pull request by pandrr**
Screenshot 2021-12-15 at 14 46 16

a 3d gizmo icon

### CODE REVIEW

**Comment by mittalyashu** [comment]
Google search results shows this on "gizmo" (sorry, poor joke) 😂

image

**Comment by pandrr** [comment]
haha maybe try "3d cursor gizmo"

Screenshot 2021-12-29 at 21 33 50

this is how the icon looks in blender for example:
Screenshot 2021-12-29 at 21 34 51

**Comment by mittalyashu** [comment]
@ericfennis instead of fill circle, do you think we should try with outline circle?

**Comment by delnyn** [comment]
that's a great idea but the circles definitely break the guidelines

**Comment by delnyn** [comment]
I agree,  
also circles would look too big

**Comment by karsa-mistmere** [comment]
image
```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <circle cx="5" cy="19" r="2"/>
  <path d="M5 17V3M3 5l2-2 2 2M7 19h14M19 17l2 2-2 2M6.5 17.5 17 7M14 7h3v3"/>
</svg>
```

**Comment by lscheibel** [comment]
Is there really a need for a general "gizmo-3d" icon? In most 3d applications gizmos have one of three functionalities: move/translate, scale and rotate, each with their own respective icon usually just represented by their 2d equivelent.

The blender icon used as an example actually represents the relative coordinate system used when applying transforms and is unrelated to the gizmos themselves.

I prepared a rough sketch of the transform operations represented as gizmos but the upper two could also just be used for 3d coordinate systems.

image

**Comment by delnyn** [comment]
that's an interesting proposition and the icons look stunning, however, the squares from the `gizmo-scale` icon look like they don't respect the guidelines

**Comment by ericfennis** [comment]
@lscheibel Thanks a lot for checking this, use full information.
Also the icons looks good. 
Maybe Idea, try adding the cricle from @karsa-mistmere icons as center point?

**Comment by ericfennis** [comment]
@lscheibel Can you open an PR for these icons?

**Comment by lscheibel** [comment]
@ericfennis Just submitted them, sorry I'm a bit short on time again. Btw, feel free to just take any screenshot / svg from any issue and take it, I probably won't be that reactive here for the next weeks.

**Comment by ericfennis** [comment]
Fixed by #705

**Pull request closed without merging**
