### PR TITLE
Add `iteration` icons

### PR DESCRIPTION
**Pull request by danielbayley**
Like https://primer.style/design/foundations/icons/iterations-16

### CODE REVIEW

**Review by ericfennis — COMMENTED** [review]
@danielbayley Nice icon!

I think we should rename this to `iteration-ccw` and create another one with the opposite direction. Like the `refresh` icons.

**Comment by karsa-mistmere** [comment]
Really nice icons, but I'm a bit on edge about their visual weight and centre of gravity.

Maybe they could be either moved 1px up or increased by 1 unit in radius, e.g.:
image

In Figma: https://www.figma.com/file/dO1uOdCGn0AHhY0RJyKHc8/lucide%2Fiterations?node-id=0%3A1&t=weYM3Odsf546Dc43-1

Not totally sure, lmkwyt. 🤔

**Comment by danielbayley** [comment]
> Really nice icons, but I'm a bit on edge about their visual weight and centre of gravity.
> 
> Maybe they could be either moved 1px up or increased by 1 unit in radius, e.g. (icons 4 to 6 for comparison): image
> 
> In Figma: https://www.figma.com/file/dO1uOdCGn0AHhY0RJyKHc8/lucide%2Fiterations?node-id=0%3A1&t=weYM3Odsf546Dc43-1
> 
> Not totally sure, lmkwyt. 🤔

Well the options are actually more limited than it probably seems, due to the arrow and the 1px padding around the edge. I think the best solution is just to push it up by 1px, which I committed…

**Comment by ericfennis** [comment]
@danielbayley I think the arrows are now to small with your last commit. If you compare it with other arrow icons from lucide on 100% you can see that the arrow of this icons are not well matching with the other designs. I think it's better to increase the whole icon a bit. I think the second icon from @karsa-mistmere looks more like it.

**Comment by danielbayley** [comment]
@ericfennis @karsa-mistmere Pushed…

**Comment by ericfennis** [comment]
@danielbayley The arrow looks still to small compared to the other arrow icons.

**Comment by danielbayley** [comment]
> @danielbayley The arrow looks still to small compared to the other arrow icons.

@ericfennis `push`ed…

**Review by ericfennis — APPROVED** [review]
Nice work, this looks better!

**Pull request merged**
