### PR TITLE
feat(icons): added `balls` icon

### PR DESCRIPTION
**Pull request by Mp3Alt**
## What is the purpose of this pull request?

- [ x ] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description
Umm, It's balls. use it for plinko.
### Icon use case
Plinko logo

### Concept
- [ x ] I have provided valid use cases for each icon.
- [ x ] I have not added any a brand or logo icon.
- [ x ] I have not used any hate symbols.
- [ x ] I have not included any religious or political imagery.

### Author, credits & license
- [ x ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [ ] I've based them on the following Lucide icons: 
- [ ] I've based them on the following design: 

### Naming
- [ x ] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [ x ] I've named icons by what they are rather than their use case.
- [] I've provided meta JSON files in `icons/[iconName].json`.

### Design

- [ x ] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [ x ] I've made sure that the icons look sharp on low DPI displays.
- [ x ] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [ x ] I've made sure that the icons are visually centered.
- [ x ] I've correctly optimized all icons to three points of precision.

## Before Submitting
- [ x ] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [ x ] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by jguddas** [comment]
Bubbles icon 
icon (57)


<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Ccircle+cx=%2213.5%22+cy=%2219.5%22+r=%222.5%22+/%3E%3Ccircle+cx=%2216%22+cy=%228%22+r=%225%22+/%3E%3Ccircle+cx=%225.5%22+cy=%2214%22+r=%223%22+/%3E">icons<br/>Open lucide studio</a>

**Comment by karsa-mistmere** [comment]
I think we need more and somewhat stronger use cases for this. 😶

**Comment by ericfennis** [comment]
I agree with @karsa-mistmere. Or add this one to https://github.com/lucide-icons/lucide-lab

**Comment by Mp3Alt** [comment]
Well, it's just one of those things where it's nice to have it and whenever you need a icon with 3 balls. Like, a loading Indicator, settings \ option menu, navigation points, networking, data points, the sky's the limit.

**Comment by AndreasSas** [comment]
I wonder if an icon like this could be better used to display balls, plinko, stacking, etc...
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Ccircle+cx=%2212%22+cy=%2219%22+r=%222%22+/%3E%3Ccircle+cx=%2212%22+cy=%225%22+r=%222%22+/%3E%3Ccircle+cx=%2216.33%22+cy=%2212%22+r=%222%22+/%3E%3Ccircle+cx=%2220%22+cy=%2219%22+r=%222%22+/%3E%3Ccircle+cx=%224%22+cy=%2219%22+r=%222%22+/%3E%3Ccircle+cx=%227.67%22+cy=%2212%22+r=%222%22+/%3E">icons<br/>Open lucide studio</a>

**Pull request closed without merging**
