### PR TITLE
Add train icon

### PR DESCRIPTION
**Pull request by delnyn**
as discussed in #330  
  
100% scale
image

### CODE REVIEW

**Review by ericfennis — APPROVED** [review]

**Comment by karsa-mistmere** [comment]
To keep the naming of icons consistent, I think it would be a good idea to call this `train-2`/`transport-train`/`train-transport` and maybe also add a train icon matching the existing transport icons (I think the third steam train from #330 looks pretty good), since the addition of further transport icons similar to this one (e.g. car, bus, see #609) seems inevitable, and it would be great if `train-2` didn't look like `car` and `train` like `car-2`. :)

**Comment by delnyn** [comment]
oh well  
yes  
what should I name it exactly

**Comment by karsa-mistmere** [comment]
Not quite sure. We still don't have solid naming conventions: #112 
What do you think, @ericfennis?

**Comment by ericfennis** [comment]
Hmm I think `train` is fine. I understand some people see the locomotive train version as a more obvious choice for this icon.    But I think we should call that one `locomotive`

**Pull request merged**
