### PR TITLE
Add workflow for release lucide-angular

### PR DESCRIPTION
**Pull request by SMAH1**
I'm not sure it will work.
Please review.

### CODE REVIEW

**Comment by ericfennis** [comment]
I think this will work. But we will see otherwise I will fix the workflow.
Currently I'm having some issues because I changed the flow.

For releasing the angular package, I think it is best if release it first in beta.

**Comment by SMAH1** [comment]
OK.
Where do I find `beta release`? I want to test it.

**Comment by ericfennis** [comment]
@SMAH1 I released it on: `lucide-angular@0.15.1-beta.0`.

**Comment by SMAH1** [comment]
I test it. It works very well.

**Pull request merged**
