### PR TITLE
fix(icons): Updated `sandwich` icon

### PR DESCRIPTION
**Pull request by jamiemlaw**
Rounded the top-front corners, and better aligned the top-most corner of the bread, and the corner of the filling to the grid

## What is the purpose of this pull request?

- [x] Other: Icon update

### Description

Rounded the top-front corners, and better aligned the top-most corner of the bread, and the corner of the filling to the grid

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by jguddas** [comment]
That icon is also too small, we could maybe even fix the size.

**Comment by jamiemlaw** [comment]
> That icon is also too small, we could maybe even fix the size.

Was literally thinking that. I opened up `burger` to see if I needed to update its cheese to match this icon, and noticed the size discrepancy.

Wider sandwich

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m2.37+11.223+8.372-6.777a2+2+0+0+1+2.516+0l8.371+6.777%22+/%3E%3Cpath+d=%22M21+15a1+1+0+0+1+1+1v2a1+1+0+0+1-1+1h-5.25%22+/%3E%3Cpath+d=%22M3+15a1+1+0+0+0-1+1v2a1+1+0+0+0+1+1h9%22+/%3E%3Cpath+d=%22m6.67+15+6.13+4.6a2+2+0+0+0+2.8-.4l3.15-4.2%22+/%3E%3Crect+x=%222%22+y=%2211%22+width=%2220%22+height=%224%22+rx=%221%22+/%3E&name=burger&base=burger">icons<br/>Open lucide studio</a>

Updated burger (for a different PR if necessary)

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?name=burger&base=burger&value=%3Cpath+d=%22M12+16H4a2+2+0+0+1+0-4h16a2+2+0+0+1+0+4h-4.25%22+/%3E%3Cpath+d=%22M5+12a2+2+0+0+1-2-2+9+7+0+0+1+18+0+2+2+0+0+1-2+2%22+/%3E%3Cpath+d=%22M5+16a2+2+0+0+0-2+2c0+1.7+1.3+3+3+3h12c1.7+0+3-1.3+3-3a2+2+0+0+0-2-2%22+/%3E%3Cpath+d=%22m6.67+12+6.13+4.6a2+2+0+0+0+2.8-.4l3.15-4.2%22+/%3E">icons<br/>Open lucide studio</a>

**Comment by jguddas** [comment]
Maybe move it up 1px?

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M15.75+18H21a1+1+0+0+0+1-1v-2a1+1+0+0+0-1-1H3a1+1+0+0+0-1+1v2a1+1+0+0+0+1+1h9%22+/%3E%3Cpath+d=%22m2.37+10.223+8.372-6.777a2+2+0+0+1+2.516+0l8.371+6.777%22+/%3E%3Cpath+d=%22M3+14a1+1+0+0+1-1-1v-2a1+1+0+0+1+1-1h18a1+1+0+0+1+1+1v2a1+1+0+0+1-1+1%22+/%3E%3Cpath+d=%22m6.67+14+6.13+4.6a2+2+0+0+0+2.8-.4l3.15-4.2%22+/%3E">icons<br/>Open lucide studio</a>

**Review by jguddas — APPROVED** [review]

**Review by ericfennis — APPROVED** [review]
Nice this looks better!

**Pull request merged**
