### PR TITLE
Add timer-reset icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-05-01 at 15 47 46@2x |

### CODE REVIEW

**Comment by locness3** [comment]
Doesn't really feel like resetting it, just like a slight variation.

**Comment by mittalyashu** [comment]
There is a use-case for this, when the user hasn't started the timer at time this icon can be used.

**Comment by locness3** [comment]
Then it needs a different name, or a stronger metaphor

**Comment by ericfennis** [comment]
Maybe we can make it a bit more obvious.
The difference between the regular `timer` icon and this icon is too little for the average user.

Maybe we can go for something like this?

image

**Comment by ericfennis** [comment]
@mittalyashu My proposal for the reset timer icon.

image


100%
Frame

**Pull request merged**
