### PR TITLE
Add `home-open` (home) icon

### PR DESCRIPTION
**Pull request by KarandeepSWranch**
## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

The current `home` icon has a path beneath its door indicating it's existence. The submitted (new) icon does not have this path no longer indicating its existence. This allows the icon to be used in the context of an "open" home. This also makes it so when using a similar fill and a stroke color, the icon still holds its shape without needing to give each path its own fill/stroke.

### Icon use case 

1. Home Navigation
2. Home Location Indication

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: `home`
- [x] I've based them on the following design: [Icon](https://api.iconify.design/material-symbols:home-rounded.svg) - [License](https://developers.google.com/fonts/docs/material_icons#licensing)

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
Hi @KarandeepSWranch,
There are a few issues with this icon request that would need to be addressed:

- no specific use case was provided, even is this is a variant of an existing icon a distinct use case justifying the need for this variant is required
- the icon has too much visual weight, it should aim to be close to circle and rectangle in size
- the icon is badly optimised and does not follow the required SVG syntax, please make sure that our pre commit hooks are correctly configured and executed
- our naming conventions do not allow for names such as `home-2` any more, the name should instead signify what makes this variant unique (e.g. `home-outline` etc)

**Comment by KarandeepSWranch** [comment]
> Hi @KarandeepSWranch, There are a few issues with this icon request that would need to be addressed:
> 
> * no specific use case was provided, even if this is a variant of an existing icon a distinct use case justifying the need for this variant is required
> * the icon has too much visual weight, it should aim to be close to circle and rectangle in size
> * the icon is badly optimised and does not follow the required SVG syntax, please make sure that our pre commit hooks are correctly configured and executed
> * our naming conventions do not allow for names such as `home-2` any more, the name should instead signify what makes this variant unique (e.g. `home-outline` etc)

Do you mind taking another look and seeing whether it meets the standards?

**Visual Weight:** I updated the size of the icon to match that of the square. But I believe I may have made it too small? Originally I followed the side of the original `home` icon, but I understand that the guidelines may have been updated since its addition.

**Optimizations:** I followed the software guide for `Adobe XD` and used `SVGOMG` to further optimize the SVG. If the updated icon still doesn't meet the standards, do you mind pointing out what could be better optimized?

**Comment by ericfennis** [comment]
@KarandeepSWranch I think this icon needs some more iterations.
The icon is not recognizable as an "open home". More like an alternative home icon with a wider door. I see you removed the doorstep, but I don't think this design is fulfilling the goal you want to accomplish. The changes are too little and not that obvious.

The provided usecase is a bit vague. I understand it has to do something with navigation and maps, but don't understand the need. To think along with you would be nice if you could refine the provided usecase. The usecase should be in detail described, so we can also understand it. For example: "An icon to locate a home address on a map in a navigation application". 
What also helps is posting some screenshots or examples from other icons.

BTW, maybe issue #1476 is filling to your usecase?

**Comment by ericfennis** [comment]
I've closed this one, see my latest message. Please open an issue or discussion to find best design for your usecase.

**Pull request closed without merging**
