### PR TITLE
add smartphone crash icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-05-01 at 15 33 29@2x |

### CODE REVIEW

**Comment by mittalyashu** [comment]
any suggestion on improving this icon

**Comment by locness3** [comment]
I'd just put an `x` in the phone.

**Comment by mittalyashu** [comment]
I tried it conflict with the dot the bottom.

**Comment by ericfennis** [comment]
I think you can try to remove the dot.

**Comment by mittalyashu** [comment]
Will it even look like phone if we remove the dot?

**Comment by locness3** [comment]
How many phones still have a physical home button nowadays?

**Comment by mittalyashu** [comment]
@locness3 @ericfennis 

| Preview |
| --- |
| CleanShot 2021-05-08 at 10 16 21@2x |

**Comment by locness3** [comment]
Doesn't feel vertically centered to me

**Comment by mittalyashu** [comment]
How about now?

| Preview |
| --- |
| CleanShot 2021-05-09 at 17 33 21@2x |

**Comment by locness3** [comment]
Feels like the phone is charging now :P

**Comment by ericfennis** [comment]
@locness3 Has a point. 😛 Maybe create one with a crack or something?

**Comment by mittalyashu** [comment]
@ericfennis Created the PR https://github.com/lucide-icons/lucide/pull/316

**Comment by ericfennis** [comment]
@mittalyashu What should we do with this one?

**Comment by mittalyashu** [comment]
How about something like this?

CleanShot 2021-06-19 at 13 05 35@2x

IK, it's a vague idea, tried to think of a different way. As we're trying to show the phone is crash not the actual phone.

**Comment by ericfennis** [comment]
And what about just an warning sign with the phone?

**Comment by mittalyashu** [comment]
Like this https://github.com/lucide-icons/lucide/pull/306#issuecomment-835792843

**Pull request closed without merging**
