### PR TITLE
add desktop icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-02-07 at 22 01 11@2x |

### CODE REVIEW

**Comment by ericfennis** [comment]
@mittalyashu 
I'm convinced yet with the name.
Maybe rename this to `devices` ?

**Review by ericfennis — CHANGES_REQUESTED** [review]
^

**Comment by locness3** [comment]
`monitor-speaker`, with a lot of tags?

**Comment by locness3** [comment]
Wait, doesn't really match both of these two icons

**Comment by mittalyashu** [comment]
@ericfennis I think we should use `devices` as category name.

As for icon we can think of some other name?

**Comment by ericfennis** [comment]
I thought of `devices` because that where spotify used them for. Otherwise I would say the same as @locness3. `speaker-desktop` or `desktop-speaker`

**Comment by locness3** [comment]
We never used `desktop` anyhwere else; I'd use `monitor`.

**Comment by ericfennis** [comment]
@locness3 You're right. `monitor-speaker`. You ok with that @mittalyashu ?

**Pull request merged**
