### PR TITLE
Add extra emoji icons

### PR DESCRIPTION
**Pull request by danielbayley**
Breaking up #1462 a bit, moving some icons here…

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
@danielbayley: can you provide use cases for these _apart from_ being used as emojis?
(E.g. for our original smiley set, they can be used on a satisfaction feedback widget 🙁😐🙂, or as like/dislike)

I don't think it is feasible for Lucide to be a complete Unicode emoji set, and while some of the emoji icons you've submitted in this and some other PRs look really nice and I can definitely see some valid use cases for them on UIs, others feel really specific as reaction emoticons in extremely edge case scenarios.

**Comment by danielbayley** [comment]
> I don't think it is feasible for Lucide to be a complete Unicode emoji set

@karsa-mistmere Yeah, I’m not doing all those! 😅

> others feel really specific as reaction emoticons in extremely edge case scenarios.

Which ones exactly? I’d be fine on cutting back a few of them… My thinking for this PR was:

* [`skull`](https://lucide.dev/icons/skull) we already have…
* `poo-face` is a fun way of rating/reacting to something as crap!
* `eyes-look` is currently (I think the only) missing from the default set of reactions, e.g right here on GitHub…

The devil ones were just an easy 10 second adaption from #1462, so I just threw them up… `revert` those?

**Comment by jguddas** [comment]
- `skull-cross-bone-bottom` is missing the 2x padding.
- I think `poo` and `poo-with-eyes` would be nice for ratings as well [`poo` -> `party-popper`]

**Comment by danielbayley** [comment]
> `poo` and `poo-with-eyes`

@jguddas Are you suggesting we have both, like this?

preview

**Comment by jguddas** [comment]
> @jguddas Are you suggesting we have both, like this?

Yes :+1:

**Comment by ericfennis** [comment]
See my comment in #1462

**Pull request closed without merging**
