### PR TITLE
Add `signal*` icons

### LINKED ISSUE #283: Icon Request: Signal level
Name : Signal 1,2,3,4, no-signal, signal-research
Is it possible to have something like that : 
signal-indicator

Thank you for your help

### PR DESCRIPTION
**Pull request by ericfennis**
closes #283
image

### CODE REVIEW

**Comment by mittalyashu** [comment]
feedback: any better way to make it distinct from `bar-chart`

CleanShot 2021-11-02 at 10 03 45@2x

**Comment by mittalyashu** [comment]
@ericfennis how about something like this?

CleanShot 2021-11-13 at 18 01 45@2x

**Comment by ericfennis** [comment]
@mittalyashu 
I think it is too thick. The lucide style is, thin and simplistic. 
I don't really bother me that the icon is a bit similar with bar-chart. The signal icon is to be fair a sort of bar chart icon displaying the strength of the signal.

**Comment by maxim-s-barabash** [comment]
I'm not sure if the icon "signal-zero" is correct

Screenshot from 2022-04-14 18-01-47

**Comment by ericfennis** [comment]
@@maxim-s-barabash you right. This need a fix

**Pull request merged**
