### PR TITLE
sparkle icon variations

### PR DESCRIPTION
**Pull request by sveltarne**
## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description
This adds two variations to the sparkles, one with a big sparkle and mini sparkle on the TR and one with a big sparkle and mini sparkle on the TL.

### Icon use case 
 The majority of sparkle icons nowadays (used alot more recently to represent AI stuff) only have one big sparkle and one mini sparkle, not two mini sparkles.

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: Sparkles
- [ ] I've based them on the following design: 

### Naming 

- [x ] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
While we currently have a few alts for icons that use the `-2` naming scheme, this has by now been deprecated and we do not accept any new icons that use it, icons' names should include what makes them unique instead.

In this instance, however, I'm not entirely sure there's a valid use case justifying the existence of three separate variants, should we move forward with this PR at all, I feel like we should stick with just one out of the three separate variants (not necessarily the one we currently have).

**Comment by ericfennis** [comment]
I agree with @karsa-mistmere

**Comment by sveltarne** [comment]
The icons dont even use the -2 naming scheme, i renamed them to sparkles-top-right and sparkles top-left after reading the guidelines before i made the PR. As for having three variants or just one, i don't really have an opinion on that, but if we can only do one i would suggest keeping sparkles-top-right

**Comment by sveltarne** [comment]
comment

**Comment by karsa-mistmere** [comment]
As I've previously stated:

> I'm not entirely sure there's a valid use case justifying the existence of three separate variants, should we move forward with this PR at all, I feel like we should stick with just one out of the three separate variants (not necessarily the one we currently have).

**Comment by ericfennis** [comment]
See the comment of @karsa-mistmere

**Pull request closed without merging**
