### PR TITLE
fix(icons): added rounding to `star` icon

### PR DESCRIPTION
**Pull request by jguddas**
## What is the purpose of this pull request?
- [x] Other: Icon update

### Description
Added rounding

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
could benefit from scaling it up for better visual weight to make up for the increased corner rounding.

**Review by ericfennis — COMMENTED** [review]
@jguddas Don't forget `star-off` and `star-half`, they should match the `star` icon 😊

**Review by ericfennis — CHANGES_REQUESTED** [review]
`star-half` should be updated as well for consistency.

**Review by ericfennis — APPROVED** [review]
Thanks, nice work!

**Pull request merged**
