### PR TITLE
Added round corners to `network`

### PR DESCRIPTION
**Pull request by jguddas**

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
Also not in favour of this change, I realise that at first glance these corners seem to conflict with the guidelines, but 2px brings these just bit too close to circles I think.

**Comment by jguddas** [comment]
What about 1px https://github.com/lucide-icons/lucide/pull/1190/commits/59b95d60f556addb0f4c1d4fe5083c98a081a8de ?

**Comment by ericfennis** [comment]
1px is better I think, Is nice if we make this consistent with #1184

**Review by ericfennis — CHANGES_REQUESTED** [review]
Change to 1px corners?

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
