### PR TITLE
Add customization options to the icon display and download

### PR DESCRIPTION
**Pull request by aelfric**
As discussed in #110 , this adds a knob for changing the color of the icons output by the website.  I also went ahead and added sliders for stroke-width and icon size similar to what is on the Feather Icons website.

### CODE REVIEW

**Comment by locness3** [comment]
Love it! Maybe making the sliders value "float" to the right like this ?
Capture du 2020-10-27 10-41-26

**Review by locness3 — APPROVED** [review]

**Comment by aelfric** [comment]
> Love it! Maybe making the sliders value "float" to the right like this ?
> Capture du 2020-10-27 10-41-26

Good idea - done.  

I also fixed the sliders - they are supposed to be filled in on the left of the thumb control, but something in Chakra was making the filled part have a zero height.  I put the values in manually for now, but I suspect this is a Chakra bug.  Will investigate a bit more later.

**Comment by ericfennis** [comment]
@aelfric Nice work!

I noticed one thing, on default each icon have the stroke color on "currentColor", so it takes the font-color that is applied. 
Is it possible to keep that on default? unless you change it of course.

**Comment by aelfric** [comment]
Yes. I can do that. I'll push a fix for it.

**Comment by Andreto** [comment]
The rounded edges on the input look kinda odd.
image

Maybe put no border-radius on the bottom corners. I also think that the color field could have a border around it. Looks a lot better on the bright side.
image

Alternatively, some margin between the input and color field. 
image

**Pull request merged**
