### PR TITLE
fix(icons): changed `image-up` icon

### PR DESCRIPTION
**Pull request by jguddas**
## What is the purpose of this pull request?
- [x] Other: Icon update

### Description
Changed arrow to common small arrow.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
It's off grid, making it blurry at 1x.

**Comment by jguddas** [comment]
> It's off grid, making it blurry at 1x.

Yes, the spacing is 2px now tho + the arrow is the same arrow we use elsewhere, which I think is better.

**Comment by karsa-mistmere** [comment]
> > It's off grid, making it blurry at 1x.
> 
> Yes, the spacing is 2px now tho + the arrow is the same arrow we use elsewhere, which I think is better.

Yeah, I get it, you fix some, you break some, but let's first explore some other ways of resolving this.
image

**Comment by karsa-mistmere** [comment]
Two alternate proposals:

image

https://www.figma.com/design/Og6ALjntwtP1I4ulGYn5Cg/lucide%2Fimage?node-id=0-1&t=DJh5zCxZldwlYFIL-1

**Comment by jguddas** [comment]
We could also move the mountain.
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?name=image-down&value=%3Cpath+d=%22m13+19+3+3v-6%22+/%3E%3Cpath+d=%22m16+22+3-3%22+/%3E%3Cpath+d=%22M19+3a2+2+0+0+1+2+2v11l-3.6-3.928a2+2+0+0+0-2.814.014L5+21a2+2+0+0+1-2-2V5a2+2+0+0+1+2-2z%22+/%3E%3Cpath+d=%22M9.5+21H5%22+/%3E%3Ccircle+cx=%229%22+cy=%229%22+r=%222%22+/%3E">icons<br/>Open lucide studio</a>

**Comment by karsa-mistmere** [comment]
> We could also move the mountain.
> 
> [iconsOpen lucide studio](https://lucide-studio.vercel.app/edit?name=image-down&value=%3Cpath+d=%22m13+19+3+3v-6%22+/%3E%3Cpath+d=%22m16+22+3-3%22+/%3E%3Cpath+d=%22M19+3a2+2+0+0+1+2+2v10.5l-3.6-3.428a2+2+0+0+0-2.814.014L5+21a2+2+0+0+1-2-2V5a2+2+0+0+1+2-2z%22+/%3E%3Cpath+d=%22M9.5+21H5%22+/%3E%3Ccircle+cx=%229%22+cy=%229%22+r=%222%22+/%3E)

I did move it in my proposals, but we should 100% keep them at a 45deg angle.

**Pull request closed without merging**
