### PR TITLE
Add more weather icons

### LINKED ISSUE #146: Different weather icons
Sorry for posting so many issues, thank you for a great fork!! Exactly what I've been looking for. I have some more suggestions for weather icons:

Hot weather: A thermometer with a sun
Windy weather: Three curvy strokes that looks like someone is blowing.
Heavy showers: Cloud with rain that goes diagonally,
Cold temperature: Thermometer with a snowflake.
Clear night: Moon but with two stars, one small and one a bit larger. 
Partly cloudy: Cloud with sun in the back.
Thunderstorm: Cloud with a lightning.

Suggestion:
Nicer looking cloud and snowflake.
The original clouds doesn't look very nice, it's hard to see that they are clouds. Do them a bit like this instead, and also the snowflake.

cloud
snow

### PR DESCRIPTION
**Pull request by ericfennis**
Closes #146
image

### CODE REVIEW

**Comment by SMAH1** [comment]
`Fog` like `menu`.
I think it should be like this:
Capture

**Comment by ericfennis** [comment]
@SMAH1 hmm intersting, I can look if I create one like those.

**Comment by ericfennis** [comment]
Should I add it as an extra icon, or replace it?
image

**Comment by SMAH1** [comment]
I am thinking about replacing.

**Comment by ericfennis** [comment]
@SMAH1 I replaced it!

**Pull request merged**
