### PR TITLE
Add bug icon

### PR DESCRIPTION
**Pull request by ericfennis**
image

100% bug

### CODE REVIEW

**Comment by mittalyashu** [comment]
Can you try in something like this style, instead of keeping the body in cylinder shape.

CleanShot 2021-03-10 at 20 39 42@2x

insect-icon-22

_the above screenshots are copyright to its respective owners_

**Comment by ericfennis** [comment]
@mittalyashu Like this?
image

**Comment by mittalyashu** [comment]
@ericfennis the first one, definitely looks like a bug but his head seems to be missing.

**Comment by ericfennis** [comment]
I think from a 100% view the second design looks better. Also because we no really use oval shapes in our icons.
image

**Pull request merged**
