### PR TITLE
feat(icons): added `amphora` icon

### LINKED ISSUE #1833: Archaeological artifacts/museum objects
### Icon name

silex, arrowhead, amphora

### Use cases

Especially if you are developing applications for museums or universities - in this case related to archaeology, it would be good to have icons for this.
These icons are specifically designed to represent archaeological finds.

I currently use the `coins` icon from Lucide to display archaeological discoveries, but this does not always seem to be suitable. 

### Design ideas

GameIcons has some neat designs for [Sillex/Flint](https://game-icons.net/1x1/delapouite/silex.html) and [Arrowhead](https://game-icons.net/1x1/lorc/arrowhead.html).

Also the discussed [amphora icon ](https://github.com/FortAwesome/Font-Awesome/issues/10022) in the FontAwesome repo is kinda nice.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

### PR DESCRIPTION
**Pull request by karsa-mistmere**
closes #1833

## What is the purpose of this pull request?

- [x] New Icon

### Description
Adds amphora icon to represent archaeological artefacts.

### Icon use case 
To represent:
- museological/archaeological artefacts
- pottery
- Greek culture
- amphora-aging for wines

### Alternative icon designs
see #1833

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] The icons are solely my own creation.

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by jguddas** [comment]
the handles feel a bit cramped.

**Comment by karsa-mistmere** [comment]
> the handles feel a bit cramped.

How about this?

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/?value=%3Csvg++xmlns=%22http://www.w3.org/2000/svg%22++width=%2224%22++height=%2224%22++viewBox=%220+0+24+24%22++fill=%22none%22++stroke=%22currentColor%22++stroke-width=%222%22++stroke-linecap=%22round%22++stroke-linejoin=%22round%22%3E++%3Cpath+d=%22M10+5H8a2+2+0+1+0+0+4h.682%22+/%3E++%3Cpath+d=%22M14+2v6.341A6+6+0+0+1+18+14a6+6+0+0+1-3+5.197V22%22+/%3E++%3Cpath+d=%22M14+5h2a2+2+0+1+1+0+4h-.682%22+/%3E++%3Cpath+d=%22M18+22H6%22+/%3E++%3Cpath+d=%22M9+22v-2.803A6+6+0+0+1+6+14a6+6+0+0+1+4-5.659V2%22+/%3E++%3Cpath+d=%22M9+2h6%22+/%3E%3C/svg%3E&name=image">icons<br/>Open lucide studio</a>

**Review by ericfennis — APPROVED** [review]

**Review by jguddas — CHANGES_REQUESTED** [review]
I think we should add some round corners.

Maybe somewhat more in this direction:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M10+5H7.97A2+2+0+1+0+10+7V3a1+1+0+0+0-1-1%22+/%3E%3Cpath+d=%22M14+5h2.03a2+2+0+1+1-2+2.344L14+3a1+1+0+0+1+1-1%22+/%3E%3Cpath+d=%22m15+22+.012-2.221a2+2+0+0+1+1.065-1.553A5+5+0+0+0+16+9%22+/%3E%3Cpath+d=%22M17.5+22H6%22+/%3E%3Cpath+d=%22m9+22-.012-2.221a2+2+0+0+0-1.065-1.553A5+5+0+0+1+8+9%22+/%3E">icons<br/>Open lucide studio</a>

**Comment by karsa-mistmere** [comment]
> I think we should add some round corners.
> 
> Maybe somewhat more in this direction:
> 
> [iconsOpen lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M10+5H7.97A2+2+0+1+0+10+7V3a1+1+0+0+0-1-1%22+/%3E%3Cpath+d=%22M14+5h2.03a2+2+0+1+1-2+2.344L14+3a1+1+0+0+1+1-1%22+/%3E%3Cpath+d=%22m15+22+.012-2.221a2+2+0+0+1+1.065-1.553A5+5+0+0+0+16+9%22+/%3E%3Cpath+d=%22M17.5+22H6%22+/%3E%3Cpath+d=%22m9+22-.012-2.221a2+2+0+0+0-1.065-1.553A5+5+0+0+1+8+9%22+/%3E)

Feels a bit like a bong or something. 🤔

**Comment by karsa-mistmere** [comment]
@jguddas: 

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M10+2v5.632c0+.424-.272.795-.653.982a6+6+0+0+0-.834+10.274c.292.207.487.532.487.89V22%22+/%3E%3Cpath+d=%22M10+5H8a2+2+0+1+0+0+4h.68%22+/%3E%3Cpath+d=%22M14+2v5.632c0+.424.272.795.652.982a5.999+5.999+0+0+1+.835+10.274c-.292.207-.487.532-.487.89V22%22+/%3E%3Cpath+d=%22M14+5h2a2+2+0+0+1+0+4h-.68%22+/%3E%3Cpath+d=%22M18+22H6%22+/%3E%3Cpath+d=%22M9+2h6%22+/%3E">icons<br/>Open lucide studio</a>

Is this better?

image

**Comment by jguddas** [comment]
> @jguddas:
> 
> [iconsOpen lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M10+2v5.632c0+.424-.272.795-.653.982a6+6+0+0+0-.834+10.274c.292.207.487.532.487.89V22%22+/%3E%3Cpath+d=%22M10+5H8a2+2+0+1+0+0+4h.68%22+/%3E%3Cpath+d=%22M14+2v5.632c0+.424.272.795.652.982a5.999+5.999+0+0+1+.835+10.274c-.292.207-.487.532-.487.89V22%22+/%3E%3Cpath+d=%22M14+5h2a2+2+0+0+1+0+4h-.68%22+/%3E%3Cpath+d=%22M18+22H6%22+/%3E%3Cpath+d=%22M9+2h6%22+/%3E)
> 
> Is this better?
> 
> image

Still does not spark joy.

What about making it a teardrop shaped?

image

**Comment by karsa-mistmere** [comment]
> Still does not spark joy.
> 
> What about making it a teardrop shaped?

We can definitely try that.

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M10+2v5.632c0+.424-.272.795-.653.982A6+6+0+0+0+6+14c.006+4+3+7+5+8%22+/%3E%3Cpath+d=%22M10+5H8a2+2+0+0+0+0+4h.68%22+/%3E%3Cpath+d=%22M14+2v5.632c0+.424.272.795.652.982A6+6+0+0+1+18+14c0+4-3+7-5+8%22+/%3E%3Cpath+d=%22M14+5h2a2+2+0+0+1+0+4h-.68%22+/%3E%3Cpath+d=%22M18+22H6%22+/%3E%3Cpath+d=%22M9+2h6%22+/%3E">icons<br/>Open lucide studio</a>

**Comment by karsa-mistmere** [comment]
> I prefer the teardrop shaped one.

Updated, I think I also prefer it, as it's much less bong-y.

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
