### PR TITLE
add timer off icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-05-01 at 15 50 24@2x |

### CODE REVIEW

**Comment by mittalyashu** [comment]
@ericfennis any changes require in this PR?

**Comment by ericfennis** [comment]
@mittalyashu Sorry for the late reply.

Something bothers me that the gap along side the slash is on the bottom left instead of the right top we do on other `-off` icons. Did you try to make the gap top-right of the slash?

**Comment by mittalyashu** [comment]
@ericfennis It looks more weird doing it from other side

CleanShot 2021-11-02 at 10 02 22@2x

**Comment by ericfennis** [comment]
@mittalyashu hmmm, and if you remove the seconds hands. Like the alarm-off icon.

Can you post a 100% version maybe it looks ok.

**Comment by mittalyashu** [comment]
| Full scale | 100% |
| --- | --- |
| CleanShot 2021-11-13 at 17 34 30@2x | CleanShot 2021-11-13 at 17 34 54@2x |

**Comment by ericfennis** [comment]
@mittalyashu Hmm I think I'm ok with it. I see it is hard to design the slash with the gap on the other side. So I think we can do this one.

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
