### PR TITLE
add capsules and pills, sunglasses, peace

### PR DESCRIPTION
**Pull request by archistico**
It is my first pull, before producing other icons I would like to know if these are ok. Thank you

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
Hey @archistico!

Thank you for submitting an icon request, however, make sure all your icons follow our [design guidelines](https://lucide.dev/docs/icon-design-guide).\
Some issues include:
* Invalid stroke widths (all strokes must be exactly 2px wide)
* Lack of a 2px spacing between elements
* Various transforms on elements (there should be none)
* Inline styles (there should be none)

Some other stuff to consider in the future:
1) please do provide the full icon request data (use cases, similar icons) for each icon
2) any pull request should only contain icons that belong to a single group (e.g. it's fine to add different medical icons all at once, but I fail to see the connection between sunglasses, a peace sign and medicine tablets 🙂 )
3) make sure your icon has the same [global attributes](https://lucide.dev/docs/icon-design-guide#global-attributes) as all other icons and that they are correctly optimized.

Incidentally, there's already an [ongoing icon request for pills](https://github.com/lucide-icons/lucide/issues/605).

**Comment by archistico** [comment]
Thank you for the directions. I'll try to make the changes and redo everything.
It is probably better if I use Inkscape instead of Affinity Designer. I see that in the export he has made me some trouble

**Comment by ericfennis** [comment]
@archistico I see you removed your changes from this PR. Are you still working on this?

**Comment by ericfennis** [comment]
No file changes, I close this for now

**Pull request closed without merging**
