### PR TITLE
feat(docs): add icon showcase to icon page

### LINKED ISSUE #2356: Layout shifts on icon page
### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

On the specific icon page, under the code block section.
On clicking `"Vanilla"` tab and `"React"` tab, the layout tends to shift.
This decreases UX

### Steps to reproduce

1. Go to any icon page (say: https://lucide.dev/icons/bug)
2. Navigate to Code Section
3. Click on "Vanilla" tab.
4. Click on "React" tab.

The layout shifts!

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

### PR DESCRIPTION
**Pull request by karsa-mistmere**
closes #2356 

## What is the purpose of this pull request?
- [x] Documentation update

### Description
This PR adds a simple icon showcase to icon pages fulfilling our promise that the user can "See [the icon] in action":
image

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by jguddas** [comment]
Those kinds of showcase docs should be done as accessible as possible, since people might copy paste form there.
I don't want to touch it tho.

**Comment by karsa-mistmere** [comment]
> Those kinds of showcase docs should be done as accessible as possible, since people might copy paste form there. I don't want to touch it tho.

Not quite sure about that, this is for visual demonstration purposes _not_ proper use cases and definitely not code examples.

If anything, this entire section should be hidden from screen readers.

**Comment by karsa-mistmere** [comment]
> Yeah, it can be just a picture for all I care, it's more about contrast and stuff like that.

Completely agree with that, however, these demos use the lucide.dev color scheme which itself is faulty, our brand color (#FF7070) only has a contrast ratio of 2.69:1 with white.

We could flip the brand buttons like this:

image

=>

image


To be honest, it looks kind of ugly. 🫤

**Review by jguddas — APPROVED** [review]

**Review by ericfennis — APPROVED** [review]
Awesome work @karsa-mistmere.
Sorry for the late review. 

Let's merge this!

**Pull request merged**
