### PR TITLE
icon: iMac

### PR DESCRIPTION
**Pull request by mittalyashu**
- **Name of the icon** : iMac
- **Tags (alternative names for this icon)** : _will do after the approval of icon_  

| Full scale | 100% |
| --- | --- |
| CleanShot 2021-11-13 at 17 32 56@2x | CleanShot 2021-11-13 at 17 45 06@2x |

### CODE REVIEW

**Comment by ericfennis** [comment]
Something else,  I'm not sure if we should make icons for specific brands/devices.
@locness3 What do you think?

**Comment by locness3** [comment]
> Something else, I'm not sure if we should make icons for specific brands/devices.

Definitely NOT.

**Comment by ericfennis** [comment]
@locness3 Allrighty.
@mittalyashu Sorry we close this one. We should not make icons for specific brands/devices.

**Comment by mittalyashu** [comment]
Ignoring the name "iMac", it can be considered as another display icon.

**Pull request closed without merging**
