### PR TITLE
add arrow's icons

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-05-16 at 13 04 04@2x |

### CODE REVIEW

**Comment by ericfennis** [comment]
Nice icons!
The `left-right` and `top-down` already exists. They called `move-vertical` and `move-horizontal`.

**Comment by ericfennis** [comment]
@mittalyashu Can you try to match `expand` and `shrink` icons with the `maximize-2` and the `minimize-2` icons? So the design looks more consistent.

**Comment by mittalyashu** [comment]
LGTM

**Comment by mittalyashu** [comment]
@ericfennis Any other changes this PR require?

**Comment by locness3** [comment]
> @mittalyashu Can you try to match `expand` and `shrink` icons with the `maximize-2` and the `minimize-2` icons? So the design looks more consistent.

**Comment by mittalyashu** [comment]
LGTM

**Comment by locness3** [comment]
Please update the preview, if you didn't

**Review by ericfennis — APPROVED** [review]

**Comment by mittalyashu** [comment]
@locness3 the preview is already updated.

**Pull request merged**
