### PR TITLE
add circle-check-2 icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| zoom | 100% |
| --- | --- |
| CleanShot 2021-02-25 at 16 07 32@2x | CleanShot 2021-02-25 at 16 07 40@2x |

### CODE REVIEW

**Comment by ericfennis** [comment]
hmm looks not like the one you posted in discord. I think the check can bigger. on 100% scale the icons looks too small.
image

**Comment by mittalyashu** [comment]
@ericfennis the reason I made the check smaller in size, as it looks like it will be touching the circle at 100% view.

Also, we try increasing the `stroke-width` it will look even more weird.

**Review by ericfennis — APPROVED** [review]

**Review by locness3 — CHANGES_REQUESTED** [review]
All good except it should be `check-circle-2`.

**Comment by mittalyashu** [comment]
Isn't the file name is already that `circle-check-2`?

**Comment by locness3** [comment]
It should be the other way around. `check-circle-2`, not `circle-check-2`

**Comment by ericfennis** [comment]
@locness3 It's `check-circle-2` !

**Pull request merged**
