### PR TITLE
Add `spiral` and `lucide` icon

### PR DESCRIPTION
**Pull request by danielbayley**
spiral

lucide

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
Brand icons, even our own 🙂, are deprecated: #670 
Any use cases for the spiral?

**Comment by danielbayley** [comment]
> Any use cases for the spiral?

Well it started as an alternate for the existing `tornado`…

image

But then, I thought it looked better as `spiral`, then naturally also made it into the _Lucide_ icon…

> Brand icons, even our own 🙂, are deprecated: #670

…which I didn’t realise would even fall under #670.

**Comment by karsa-mistmere** [comment]
I think from a weather report use case people rarely expect to look at a tornado from above. 😄

**Comment by danielbayley** [comment]
> I think from a weather report use case people rarely expect to look at a tornado from above. 😄

At that point, it would be too late for the report 😅

I have a demo weather app as a `create-react-app` base template, and was thinking of doing that particular icon this way…

**Review by karsa-mistmere — CHANGES_REQUESTED** [review]
@danielbayley: The `lucide` icon has to go and the spiral will need some proposed use cases before this can move forward.

**Pull request closed without merging**
