### PR TITLE
Add `chevron-*-square` (including `terminal` alternate) icons

### PR DESCRIPTION
**Pull request by danielbayley**
terminal-square-2

chevron-left-square

chevron-up-square

chevron-down-square

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
I think this looks more like a candidate for `chevron-right-square`. :)

**Comment by danielbayley** [comment]
> I think this looks more like a candidate for `chevron-right-square`. :)

In which case, it will also need `chevron-`[`left`/`up`/`down`]`-square`…

**Comment by karsa-mistmere** [comment]
Hm... these seem a bit off centre, how about making the chevrons 5x10 and 10x5 as they are in `chevrons-*` icons?
image

**Comment by karsa-mistmere** [comment]
> Hm... these seem a bit off centre, how about making the chevrons 5x10 and 10x5 as they are in `chevrons-*` icons?

I guess never mind, the regular chevron icons appear off centre as well. :D
Chevrons have a funky centre of gravity.

**Review by karsa-mistmere — APPROVED** [review]

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
