### PR TITLE
fix(icons): changed `pizza` icon

### PR DESCRIPTION
**Pull request by jamiemlaw**
## What is the purpose of this pull request?

- [ ] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other: Icon update

### Description
Rounded the corners of the pizza slice and spaced out the pepperoni to address the two-pixel-gap rule.

### Alternative Designs

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11.5+14.501h.01%22+/%3E%3Cpath+d=%22M14.5+11.501h.01%22+/%3E%3Cpath+d=%22M16+16.001h.01%22+/%3E%3Cpath+d=%22M16.9+5.536A16+16+0+0+0+5.535+16.901%22+/%3E%3Cpath+d=%22M21.95+20.685a1+1+0+0+1-1.266+1.265l-18-6a1+1+0+0+1-.633-1.265A20+20+0+0+1+14.684+2.051a1+1+0+0+1+1.265.633z%22+/%3E">icons<br/>Open lucide studio</a>
thinner slice, most similar to existing pizza shape, but the pepperoni lies on half-pixels in order to fit

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+15h.01%22+/%3E%3Cpath+d=%22M15+12h.01%22+/%3E%3Cpath+d=%22M16+16h.01%22+/%3E%3Cpath+d=%22M17.775+5.654a15.68+15.68+0+0+0-12.121+12.12%22+/%3E%3Cpath+d=%22M21.964+20.732a1+1+0+0+1-1.232+1.232l-18-5a1+1+0+0+1-.695-1.232A19.68+19.68+0+0+1+15.732+2.037a1+1+0+0+1+1.232.695z%22+/%3E">icons<br/>Open lucide studio</a>
submitted design, I think the most balanced

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+15h.01%22+/%3E%3Cpath+d=%22M15+12h.01%22+/%3E%3Cpath+d=%22M16+16h.01%22+/%3E%3Cpath+d=%22M18.2+5.696a15.57+15.57+0+0+0-12.504+12.51%22+/%3E%3Cpath+d=%22M21.97+20.758a1+1+0+0+1-1.213+1.212l-18-4.5a1+1+0+0+1-.727-1.212A19.55+19.55+0+0+1+16.258+2.03a1+1+0+0+1+1.212.728z%22+/%3E">icons<br/>Open lucide studio</a>
thicker slice, but the arcs at te edge of the pizza lie on half pixels

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by jguddas** [comment]
Lovely ❤️ 

With different toppings:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m12+14-1+1%22+/%3E%3Cpath+d=%22m13.75+18.25-1.25+1.42%22+/%3E%3Cpath+d=%22M17.775+5.654a15.68+15.68+0+0+0-12.121+12.12%22+/%3E%3Cpath+d=%22M18.8+9.3a1+1+0+0+0+2.1+7.7%22+/%3E%3Cpath+d=%22M21.964+20.732a1+1+0+0+1-1.232+1.232l-18-5a1+1+0+0+1-.695-1.232A19.68+19.68+0+0+1+15.732+2.037a1+1+0+0+1+1.232.695z%22+/%3E">icons<br/>Open lucide studio</a>

**Comment by karsa-mistmere** [comment]
> Lovely ❤️
> 
> With different toppings:
> 
> [iconsOpen lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m12+14-1+1%22+/%3E%3Cpath+d=%22m13.75+18.25-1.25+1.42%22+/%3E%3Cpath+d=%22M17.775+5.654a15.68+15.68+0+0+0-12.121+12.12%22+/%3E%3Cpath+d=%22M18.8+9.3a1+1+0+0+0+2.1+7.7%22+/%3E%3Cpath+d=%22M21.964+20.732a1+1+0+0+1-1.232+1.232l-18-5a1+1+0+0+1-.695-1.232A19.68+19.68+0+0+1+15.732+2.037a1+1+0+0+1+1.232.695z%22+/%3E)

I think this really helps it to look more like pizza and less like watermelon

**Comment by jguddas** [comment]
We could also consider renaming this icon `slice-pizza`.

**Comment by jamiemlaw** [comment]
> I think this really helps it to look more like pizza and less like watermelon

100% agreed. That's a beautiful looking pizza.

**Review by ericfennis — APPROVED** [review]
Niceee 🍕

**Pull request merged**
