### PR TITLE
Add megaphone icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-02-06 at 14 15 24@2x |

### CODE REVIEW

**Comment by locness3** [comment]
"microphone"?

**Comment by ericfennis** [comment]
I think @mittalyashu means megaphone :p

**Comment by mittalyashu** [comment]
Yeah, while submitting PR, I also got confused there 😅.

**Comment by ericfennis** [comment]
@mittalyashu 
Maybe try to make handle a bit bigger.
On 100% scale the handle looks a bit small.

**Review by ericfennis — CHANGES_REQUESTED** [review]
^

**Comment by ericfennis** [comment]
Like this 
image
100% 
Frame

**Comment by ericfennis** [comment]
@mittalyashu what do you think?

**Pull request merged**
