### PR TITLE
Add movie icons

### PR DESCRIPTION
**Pull request by it-is-not**
movie icon
movie icon

### CODE REVIEW

**Comment by it-is-not** [comment]
I also added movie-play and movie-pause
movie pause
movie play

**Review by karsa-mistmere — CHANGES_REQUESTED** [review]

**Comment by karsa-mistmere** [comment]
I can see legit use cases for the movie icon, not quite sure if we need the play/pause variants, can you provide a use case for these, @it-is-not?

**Comment by karsa-mistmere** [comment]
Also, I think the gap between the parts is a bit narrow, and the top part is maybe a bit too dense, how about just two lines instead of three?
image
movie

**Comment by it-is-not** [comment]
thank you @karsa-mistmere I'll try and sort those issues out later

**Comment by karsa-mistmere** [comment]
We should probably try sticking to the grid as much as possible, straight horizontal/vertical lines on half pixels sometimes end up looking really funky on low dpi screens.

**Comment by it-is-not** [comment]
agreed, I'll have another look

**Comment by it-is-not** [comment]
here's the new icon with on top of a grid

image

**Comment by it-is-not** [comment]
I'm not entirely sure what you mean, but I've redesigned the top so it's a rectangle, moved some of the lines to make it more evenly spread out and increased the top's rotation so it's further away from the bottom bit. Does this fix the issue?

image

**Comment by ericfennis** [comment]
@it-is-not Nice Icon, love it!

**Comment by ericfennis** [comment]
I think the name of the icon need to be changed to 'clapperboard', because that is what the icons represents.

**Comment by mittalyashu** [comment]
According to what @it-is-not said https://github.com/lucide-icons/lucide/pull/629#issuecomment-1107889192

Those two icons might not match the lucide icon guidelines

**Comment by it-is-not** [comment]
@ericfennis - I'll change this and add `movie` as a tag

**Comment by it-is-not** [comment]
@mittalyashu - I've removed the play and pause icons since they don't really have a use case

**Comment by ericfennis** [comment]
@it-is-not can you also remove the icons in the tags.json?

**Review by ericfennis — APPROVED** [review]

**Comment by it-is-not** [comment]
thank you for your help @karsa-mistmere and @ericfennis and @mittalyashu 😄

**Pull request merged**
