### PR TITLE
Add missing `arrow-*-from-square`/optimise `external-link` icon/s

### PR DESCRIPTION
**Pull request by danielbayley**
Following on from #1351, and closely related to #1013.

### CODE REVIEW

**Review by ericfennis — APPROVED** [review]
@danielbayley Nice ones !

**Review by karsa-mistmere — APPROVED** [review]

**Comment by jguddas** [comment]
Should we remove the -from, and make the name shorter?

**Comment by karsa-mistmere** [comment]
> Should we remove the -from, and make the name shorter?

I vote against, I think we should leave space for matching `arrow-down-left-to-square` icons, should the need arise:
image

**Comment by danielbayley** [comment]
> Should we remove the -from, and make the name shorter?

> I vote against

Same, as I was also going off the existing naming of other icons… See https://lucide.dev/icons/?search=from.

**Pull request merged**
