### PR TITLE
Add album icon

### PR DESCRIPTION
**Pull request by ericfennis**
image
100% 
image

### CODE REVIEW

**Comment by locness3** [comment]
Feels a little off to me.

**Comment by ericfennis** [comment]
@locness3 hmm ok.

**Comment by locness3** [comment]
I'm just not too sure about the use case for this one.

**Comment by ericfennis** [comment]
Sorry, maybe it's better that I explain more what I make. 😅
But for this one, I imagine it used in UIs for photo applications.

So here in example how it can look.
image

**Pull request merged**
