### PR TITLE
Add `panel-*` icons

### PR DESCRIPTION
**Pull request by danielbayley**
This PR aims to complete the existing `sidebar-*` set of icons, cover the `layout`[`-panel`]`-*` [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html) and consolidate everything into a more coherent subset of icons. Closes #1059.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
I also have these in my drafts (`sidebar-open`, `sidebar-close`), what do you think of also adding these?
image

**Comment by ericfennis** [comment]
@karsa-mistmere I think we have already some of these

**Comment by karsa-mistmere** [comment]
> @karsa-mistmere I think we have already some of these

Sure, I meant just the matching pairs for the new orientation. :)

**Comment by danielbayley** [comment]
> @karsa-mistmere I think we have already some of these

Yeah https://lucide.dev/?search=sidebar just `sidebar-open`/`close`, which should be renamed to `sidebar-left-open`/`close`…

**Comment by karsa-mistmere** [comment]
@danielbayley If we rename them, we'll have to add aliases for their old names.

**Comment by danielbayley** [comment]
> @danielbayley If we rename them, we'll have to add aliases for their old names.

Done.

**Comment by danielbayley** [comment]
> @danielbayley If we rename them, we'll have to add aliases for their old names.

Done.

**Comment by karsa-mistmere** [comment]
Not super sure about the names `panel` and `menu-bar`, it'd be neat if we could come up with a single name that works for both `...-bottom` and `...-top`.

I've seen UI libs use the names `drawer`, `sheet` and `slide-over` for all four placements, but I'm not totally sold on either of these.

**Comment by danielbayley** [comment]
> Not super sure about the names `panel` and `menu-bar`, it'd be neat if we could come up with a single name that works for both `...-bottom` and `...-top`.
> 
> I've seen UI libs use the names `drawer`, `sheet` and `slide-over` for all four placements, but I'm not totally sold on either of these.

Why not just `panel-top`/`bottom` then?

**Comment by danielbayley** [comment]
@karsa-mistmere @ericfennis @jguddas Are there too many icons in this PR for the CI…?! https://github.com/lucide-icons/lucide/actions/runs/4748547120/jobs/8434857195?pr=1003#step:6:14

**Comment by jguddas** [comment]
> @karsa-mistmere @ericfennis @jguddas Are there too many icons in this PR for the CI…?! https://github.com/lucide-icons/lucide/actions/runs/4748547120/jobs/8434857195?pr=1003#step:6:14

The error looks like it being caused by returning too much from the generate comment step, but AFAIK the limit is 16mb, and we shouldn't hit that with just so few icons.

**Comment by ericfennis** [comment]
@jguddas Looks like the branch need to rebased. We did some optimization in #1025.

**Comment by danielbayley** [comment]
> @jguddas Looks like the branch need to rebased. We did some optimization in #1025.

`rebase`d…

**Comment by ericfennis** [comment]
@danielbayley I think this PR got way to big. 

To accept this PR, I will only accept these icons for this PR:

- panel-bottom
- panel-bottom-close
- panel-bottom-open
- panel-bottom-inactive
- panel-left
- panel-left-close
- panel-left-open
- panel-left-inactive
- panel-right
- panel-right-close
- panel-right-open
- panel-right-inactive
- panel-top
- panel-top-close
- panel-top-open
- panel-top-inactive

For the others:
I think for the other icons. We must discuss in another PR. For example `panel-top-left` is currently conflicting with layout icons. But to keep us focused I think we should move this discussion to another PR/issue.

I think `rows` is nice, but let's do that one in another PR as well

**Comment by danielbayley** [comment]
> I think this PR got way to big.

> To accept this PR, I will only accept these icons for this PR:
> 
> * panel-bottom
> * panel-bottom-close
> * panel-bottom-open
> * panel-bottom-inactive
> * panel-left
> * panel-left-close
> * panel-left-open
> * panel-left-inactive
> * panel-right
> * panel-right-close
> * panel-right-open
> * panel-right-inactive
> * panel-top
> * panel-top-close
> * panel-top-open
> * panel-top-inactive

@ericfennis Ok, so I’ve cut it down to size, leaving only those listed…

> I think `rows` is nice, but let's do that one in another PR as well

Moved this back to #1059…

> for the other icons. We must discuss in another PR.

See #1154…

**Comment by karsa-mistmere** [comment]
I think the dashed lines should fall more in line with pre-existing dashed lines (`box-select`, `ticket`, `flip-*`), in this case `box-select` in particular (the dash array of flip just doesn't work here):
image

**Comment by danielbayley** [comment]
> dashed lines should fall more in line with pre-existing dashed lines

@karsa-mistmere `push`ed…

**Review by karsa-mistmere — APPROVED** [review]

**Review by ericfennis — APPROVED** [review]
Nice work, thanks for you changes!

**Pull request merged**
