### PR TITLE
Add `tree` icon

### PR DESCRIPTION
**Pull request by lscheibel**
I needed this one for a soundboard.

image

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
All in all nice, but I think the trunk needs to be taller, as deciduous trees' trunks usually are, otherwise it looks a little more like a shrub than it does a tree:
image
image

**Comment by lscheibel** [comment]
I like the last one, I thought it looked a bit like cotton candy but I think in context it works. I updated the PR

**Comment by ericfennis** [comment]
@lscheibel @karsa-mistmere Nice, I've one suggestion I'm curious what you think of it.
Maybe rename this to `tree-broadleaf` and create add another icon for `tree-pine`. I can image sometimes the pine tree is for some people more obvious choice.

**Comment by karsa-mistmere** [comment]
@ericfennis Yeah, totally agree, there should be different kinds of trees. There's actually already an issue in progress: #599
I would maybe name this `tree-deciduous` (but it definitely needs it at least as a tag).

Here's a mashup overview of current design proposals by @lscheibel and myself.
image
tree

**Comment by ericfennis** [comment]
@karsa-mistmere I like the top row. But with the current `tree-deciduous` icon.

**Comment by karsa-mistmere** [comment]
@ericfennis: I guess that can work, but I actually quite grew to like the top row version, it's quite unmistakable and I think @lscheibel is right that the second row version does in fact look a bit like cotton candy.

**Pull request closed without merging**
