### PR TITLE
Optimise `send` icon/add variant

### PR DESCRIPTION
**Pull request by danielbayley**
Leaving alt here for reference…

preview

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
The central gap is very dense and the icon seems a bit too large in the cohesion preview.

**Comment by danielbayley** [comment]
> The central gap is very dense and the icon seems a bit too large in the cohesion preview.

@karsa-mistmere Fixed now, matches the other `send` when rotated…

**Comment by jguddas** [comment]
I'm not a fan of introducing variants, why add this?

**Comment by danielbayley** [comment]
> I'm not a fan of introducing variants, why add this?

@jguddas We already have variants. People have preferences, and maybe their ideal set of common icons is _almost_ covered by Lucide, but just not _quite_… very frustrating. That said, we obviously shouldn’t be going crazy…

This one is commonly found in the wild, and specifically looks better on a button say, where it is quite likely to be used.

**Comment by karsa-mistmere** [comment]
While I do see the rationale behind adding a horizontal alt, I think a horizonal send icon should look more like this, to keep the style consistent:
send-horizontal

**Comment by danielbayley** [comment]
> I think `send-horizonal` (note name) should look more like this, to keep the style consistent:

@karsa-mistmere `push`ed…

**Review by karsa-mistmere — APPROVED** [review]

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
