### PR TITLE
Adds various food icons

### PR DESCRIPTION
**Pull request by karsa-mistmere**
closes #678 

## Icon Request

* Icon name:
* Use case:
* _Screenshots_ of similar icons:

As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/32 this PR adds further food icons.

image
food

### CODE REVIEW

**Comment by ericfennis** [comment]
I appreciate the work, but I'm not sure about the amount of food icons.
Some are I think a bit too specific. 
How do you think of this @locness3 ?

**Comment by karsa-mistmere** [comment]
Here are some use cases:

- ice-cream: ice cream shop location pin
- apple/cherry/banana/grape: just representing fruit in general (these are all pretty iconic looking fruits)
- egg-fried: representing breakfast, or breakfast places
- pizza:

**Comment by wojtekmaj** [comment]
Just to give come context around ice cream icon: we want to use it as an icon for Flavors subpage in an app for the ice cream venue :)

**Comment by ericfennis** [comment]
@karsa-mistmere Thanks for the explanation.
I think one ice cream is ok.
For the others: I think `grape` and one or two fruit icons are enough. I understand that it maybe helpful for grocery store but then you should also add all the other "fruits" and "veggies", I think that is a bit to much. We should keep the icons we add a bit "general".
For `breakfast` I think I never saw a fried egg used. Maybe "utencils" or "coffee" should fit better. 
I think one pizza icon is fine.

Let me know if you agree with this or not.

**Comment by karsa-mistmere** [comment]
As for breakfast, these are from Foursquare & Swarm: CCE0F7F8-3D64-4F85-BC7B-224FB4906183
7B6D27B8-6863-4FFF-B44A-38CB540AA599
4B1FCBFA-2414-45A4-A71D-451B7E2F1FA4

I think we're basically in agreement about the rest.

**Comment by karsa-mistmere** [comment]
I guess adding a slice of bacon to further clarify breakfast is also an option:
image
image

**Review by ericfennis — APPROVED** [review]

**Comment by locness3** [comment]
Sorry for not replying, I honestly do not have much interest in this project anymore.

I'd say these are too specific, but I'll trust you all with maintaining the quality and consistency of the whole icon set.

**Pull request merged**
