### PR TITLE
Add `barcode`/`scan` icons/optimise/improve metadata

### PR DESCRIPTION
**Pull request by danielbayley**
Loosely related to #1344.

### CODE REVIEW

**Review by jguddas — APPROVED** [review]
It's a violation :disappointed:, but it looks sooooooo good.

**Comment by danielbayley** [comment]
> It's a violation 😞, but it looks sooooooo good.

Oh no! 😭 Is it really? How?

**Comment by karsa-mistmere** [comment]
> > It's a violation 😞, but it looks sooooooo good.
> 
> Oh no! 😭 Is it really? How?

Yeah, I'm afraid the 1px wide rectangles aren't something we have in any other icons, and they don't scale well:
image

**Comment by danielbayley** [comment]
Such a shame! Fixed now anyway… @karsa-mistmere @jguddas

**Comment by jguddas** [comment]
not sure `scan` is the right word

**Comment by danielbayley** [comment]
> not sure `scan` is the right word

@jguddas  It’s the [existing](https://lucide.dev/icons/?search=scan) naming… What else should it be?

**Review by ericfennis — APPROVED** [review]
Nicee ones!!

**Review by jguddas — APPROVED** [review]

**Comment by Gobot1234** [comment]
Hi sorry for the slight necro but didn't want to open a new issue. After staring at the barcode scan it seems that the margin isnt the same on either side with the lines. Was this intentional?

**Comment by danielbayley** [comment]
> After staring at the barcode scan it seems that the margin isnt the same on either side with the lines. Was this intentional?

@Gobot1234 Of course. The uneven gap between lines is what makes it idetifiable as a barcode… Not ideal in this case that means the margins also are not even, but constraints are tight!

**Pull request merged**
