### PR TITLE
fix(icons): redesigned `person-standing` icon

### PR DESCRIPTION
**Pull request by jguddas**
## What is the purpose of this pull request?
- [x] Other: Icon update

### Description
Redesigned icon, fixing gap violations and increasing size.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by ericfennis** [comment]
Hmm, I don't like it. It does not fit the style IMO

**Comment by jguddas** [comment]
> Hmm, I don't like it. It does not fit the style IMO

What do you not like about it?

For me, it feels to professional and sterile.

**Comment by jguddas** [comment]
image

**Comment by ericfennis** [comment]
@jguddas The body is not one shape, which made it feel a bit too abstract.

**Pull request closed without merging**
