### PR TITLE
Add theater/drama icons

### LINKED ISSUE #1399: Theater/drama icon
## Icon Request

* Icon name: Theater/Theatre/Drama/Entertainment
* Use case: Filtering by entertainment type (similar as how Megaphone can be used for 'advertising' and Clapperboard for 'film/movie'
* _Screenshots_ of similar icons:
image

Something like this could also be nice, however i feel that this could get really dense on small sized icons
image

### PR DESCRIPTION
**Pull request by MaxTechnics**
Fixes #1399
These icons were designed by danielbayley (not me)

### CODE REVIEW

**Review by ericfennis — COMMENTED** [review]
Hmm, not sure if we should add two drama icons.

**Comment by MaxTechnics** [comment]
In terms of the drama icons:
Both the upright and angled are really popular representations of the drama masks. Depending on context, one may choose one over the other. eg. when their organisation logo has the same orientation, in order to keep consistency.

**Comment by danielbayley** [comment]
@MaxTechnics Oh did I give you them both? I don’t remember 😅

> Hmm, not sure if we should add two drama icons.

Yeah I agree with @ericfennis, I think the one with the angled masks is easily the most recognisable…

**Comment by MaxTechnics** [comment]
> @MaxTechnics Oh did I give you them both? I don’t remember 😅
> 
> > Hmm, not sure if we should add two drama icons.
> 
> Yeah I agree with @ericfennis, I think the one with the angled masks is easily the most recognisable…

I took the svg's from the [issue comment](https://github.com/lucide-icons/lucide/issues/1399#issuecomment-1661204688). Didn't get them any other way i know of :)

The angled ones probably are more recognizable, but the straight ones do have their place in my opinion. I plan on using both in a few ongoing projects. If the straight one does not pass, i'll probably use the svg code outside of lucide.

I'm also working on improving the metadata a little.

**Comment by ericfennis** [comment]
@MaxTechnics Let's go for the angled one.

**Comment by MaxTechnics** [comment]
Have updated branch, removed the non-angled icon and added some tags (mostly british spelling for theater)

**Comment by ericfennis** [comment]
@MaxTechnics Awesome, this one is good to go!

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
