### PR TITLE
add clipboard-copy icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-02-26 at 10 26 34@2x |

### CODE REVIEW

**Comment by locness3** [comment]
Not sure about that one

**Comment by mittalyashu** [comment]
@ericfennis @locness3 any updates?

**Comment by ericfennis** [comment]
I think it's ok, @locness3 can you explain what's wrong?

**Comment by mittalyashu** [comment]
> Well, I did had small concern while designing the icon.

It was big arrow head, not sure about that.

**Comment by locness3** [comment]
> I think it's ok, @locness3 can you explain what's wrong?

There is already a `copy` icon, I'm not sure what benefit this one adds.

**Comment by locness3** [comment]
Also could have more icons with something in the clipboard : maybe one with an x...

**Comment by mittalyashu** [comment]
@ericfennis @locness3 

* Clipboard-X https://github.com/lucide-icons/lucide/pull/325
* Clipboard-Check https://github.com/lucide-icons/lucide/pull/323

**Pull request merged**
