### PR TITLE
Fix for flutter release package

### PR DESCRIPTION
**Pull request by prateekmedia**

### CODE REVIEW

**Comment by ericfennis** [comment]
@prateekmedia shit, thanks for fixing this!
Do you maybe have experience working with testing in dart? 

We need to have something to prevent this, see #417.

**Comment by prateekmedia** [comment]
@ericfennis Some helps regarding test can be found here https://stackoverflow.com/questions/65191069/golden-tests-with-custom-icon-font-class

**Comment by prateekmedia** [comment]
@ericfennis I think it's safe to merge this now.

**Comment by prateekmedia** [comment]
@ericfennis I will try to write it. I also have not written any tests but I have experience with flutter and dart.

**Comment by ericfennis** [comment]
@prateekmedia alright, yeah maybe good opportunity for you to learn testing 😊

**Pull request merged**
