### PR TITLE
Add `waterfall` icon

### PR DESCRIPTION
**Pull request by lscheibel**
I needed this one for a soundboard.

image

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
Not sure about this one. What would be the use case?

Also, I'm not convinced this is easily recognisable as a waterfall, how about an alternate design or adding a few lines of movement?
image

**Comment by lscheibel** [comment]
Tbh these don't have the "feather" feeling for me. Taking a look at the original designs (https://feathericons.com/) most of them try to use as much whitespace as possible and I personally like the "light" ones best (like the clipboard).

As for the use-case: It is very niche, I needed it for a soundboard but I would totally understand it if we decided to skip this one!

**Comment by karsa-mistmere** [comment]
Yes, as minimalist and light as possible is definitely preferable, but I think the icons still need convey reasonably well what they mean to represent and unfortunately, I don't believe the original proposal succeeds in this regard. 😕

Still not quite sure about the use case. On the soundboard, what does the waterfall icon stand for?

**Comment by lscheibel** [comment]
It was the sound of water splashing 😄 Let's hear what others think, but I'd be fine with closing this one.

**Comment by karsa-mistmere** [comment]
(Oh, _that_ kind of soundboard 😅)

**Comment by karsa-mistmere** [comment]
@lscheibel: I think for this particular use case, [`waves`](https://lucide.dev/icon/waves) or [`droplets`](https://lucide.dev/icon/droplets) could work as well?

**Comment by karsa-mistmere** [comment]
@lscheibel: I've been revisiting this topic time and again in the last two weeks and made a few alternate drafts and ideas (fountain?).
image

**Comment by ericfennis** [comment]
This icon design needs more prototyping and research. For more discussion about this icon design, you can continue in this thread. But I close this for now because it is inactive.

**Pull request closed without merging**
