### PR TITLE
Add template icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-01-27 at 21 02 00@2x |

### CODE REVIEW

**Comment by ericfennis** [comment]
Hmm I don't know with this one.
Can you explain what the difference in usecase is with the `layout` icon?
https://lucide.netlify.app/icon/layout

**Comment by mittalyashu** [comment]
Well, people can find many use-cases just to use the icon.

It can represent "blocks of section" too.

**Comment by ericfennis** [comment]
Allright.
Can you try to make it matching with the other `layout` icons?
And maybe we can call it `layout-template`?

**Comment by mittalyashu** [comment]
@ericfennis done

**Comment by ericfennis** [comment]
Can you try match it with the other `layout` icons?

**Comment by ericfennis** [comment]
I meant this. What do you think?
image

**Comment by ericfennis** [comment]
@mittalyashu Any updates on this?

**Comment by locness3** [comment]
Maybe `layout-blocks`?

**Comment by mittalyashu** [comment]
@ericfennis should I rename the icon too?

**Comment by ericfennis** [comment]
I think its fine. `layout-blocks` I think conflicts a bit with the `layout-grid` according to the style.

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
