### PR TITLE
Optimise/refine/add `*box`/`chest` icons

### PR DESCRIPTION
**Pull request by danielbayley**
Bunch of options… See column:

1. `briefcase-plus` (first aid kit)
2. `lunch-box`
3. `toolbox`
4. `chest`
5. … `mailbox`

Untitled
Artboard 1@2x

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
I already have a draft for chest. 😄 
image

**Comment by danielbayley** [comment]
> I already have a draft for chest. 😄

Of course you do… 😅

**Comment by jguddas** [comment]
Neither of those are super fun and playful :/

**Comment by karsa-mistmere** [comment]
> Neither of those are super fun and playful :/

I think that's rather subjective, the question is, are they consistent with other icons, @danielbayley based his on `mailbox`, I based mine on `briefcase`:
image

**Comment by jguddas** [comment]
Creating boxes that spark joy are a lot harder to do than cute animals.

Not happy with my "tool" boxes either:

**Comment by karsa-mistmere** [comment]
> Creating boxes that spark joy are a lot harder to do than cute animals.
> 
> Not happy with my "tool" boxes either:  

It's almost identical to mine. 😄 
toolkits

**Comment by jguddas** [comment]
Yours looks better tho 😛

**Comment by jguddas** [comment]
I like those: image

The right one feels a bit small tho.

**Comment by ericfennis** [comment]
This PR is merged to the lab branch. This PR does not match our [PR template](https://github.com/lucide-icons/lucide/blob/main/.github/pull_request_template.md), which requires valid use cases. To move on we merged this PR to the [lab branch](https://github.com/lucide-icons/lucide/tree/lab), which will be moved to a separate repo in the future.

**Pull request merged**
