### PR TITLE
Add newspaper icon from Feather requests #21

### PR DESCRIPTION
**Pull request by djsime1**
https://github.com/feathericons/feather/issues/21
Large:
Newspaper96w
100%:
Newspaper100

### CODE REVIEW

**Review by locness3 — CHANGES_REQUESTED** [review]
Too dense imo

**Comment by ericfennis** [comment]
@djsime1 Welcome to the Lucide community! 
Please checkout our [Icon Design Guide](https://github.com/lucide-icons/lucide/blob/master/docs/ICON_DESIGN_GUIDE.md), we have some rules to make sure icons are consistent and match with the other icons.

If you can't figure it out, just say it we can help you.

**Comment by ericfennis** [comment]
I close this one due to inactivity

**Comment by tidoni** [comment]
3 different Versions, any comment on them?

Not 2px spacing between the "header" and newspaper line: 
newspaper

Not 2px spacing between the lines representing the content of the newspaper:
newspaper3

Fulfilling all rules, but my least favorite:
 newspaper2

**Comment by locness3** [comment]
What about that last one with the header not filled?

**Comment by tidoni** [comment]
The header was not filled, it just was two pixels high, so it wouldn't show a white space in between.
Here two other versions.

newspaper2_2
newspaper2

**Pull request closed without merging**
