### PR TITLE
Add pencil icon

### PR DESCRIPTION
**Pull request by ericfennis**
Adds pencil icon
image

### CODE REVIEW

**Comment by locness3** [comment]
edit-4 basically

**Comment by ericfennis** [comment]
Yeah true, I a bit doubting what the right name is .. 🤔

**Comment by ericfennis** [comment]
@locness3 Do you think we need to call it edit-4?

**Comment by locness3** [comment]
No idea

**Comment by delnyn** [comment]
Also shouldn't it be rounded? I personally don't like the shape of this icon. Maybe you could do something more like Octicon's pencil, but... 2px rounded? 
image

**Pull request merged**
