### PR TITLE
Add `sort-alphabetic-`[`asc`/`desc`]ending icon

### PR DESCRIPTION
**Pull request by danielbayley**
Artboard 1@30x

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
The letter `A` does not have sufficient inner spacing, I'm afraid. :(

I actually have these in my icon drafts, but since I was unhappy with the shape, I never submitted it:
image

**Comment by karsa-mistmere** [comment]
Not fantastic, but this spacing is maybe very-very barely sufficient. :/ 
image

**Comment by danielbayley** [comment]
Shouldn’t the arrow be on the left, same as https://lucide.dev/?search=sort?

**Comment by danielbayley** [comment]
Shouldn’t the arrow be on the left, same as https://lucide.dev/?search=sort?

@karsa-mistmere See above…

**Comment by karsa-mistmere** [comment]
These are pretty old designs, made for Feather before Lucide even came to existence, but I don't think that's really the point. :)

What's noteworthy though is that the arrows are of a different size than in `sort-asc` and `sort-desc`. They could be swapped around but the smaller arrow makes them not very well balanced. :/ 

image

**Comment by ericfennis** [comment]
I agree with @ karsa-mistmere, the use case for lowercase is not very solid. Most of the time you sort by alphabet or numbers.

**Comment by danielbayley** [comment]
> I agree with @ karsa-mistmere, the use case for lowercase is not very solid. Most of the time you sort by alphabet or numbers.

I think there is a slight misunderstanding here. I wasn’t proposing lowercase sort as a separate use case to say, uppercase sort (although they can technically be slightly different in terms of functionality…) I was simply playing with lowercase a-z as a way to visually line things up nicely as a set of `sort-*` icons, a-z meant to represent only alphabetic sort _in general_, if that makes sense…?

**Comment by karsa-mistmere** [comment]
I think we got you, we're just saying that using `a..z` in this use case is (maybe too) unusual (for it to actually work) — I haven't been able to find a single sort icon that uses lowercase letters.

**Comment by danielbayley** [comment]
> I think we got you

Ok cool, not sure what difference it really makes (aside from I suppose _possibly_ implying some kind of separate, case-sensitive sort) but see `push`ed an alternative approach anyway…

**Comment by karsa-mistmere** [comment]
Hey @danielbayley,

I've just opened a new PR (#1028), since I have a somewhat unrelated bone to pick with these icons and didn't want to make you do what I believe is the necessary work to sort things out, since it's a _lot_ of refactoring. 😅 

I hope I didn't step on your toes, it was all done in good faith. 🙈

**Comment by danielbayley** [comment]
> Hey @danielbayley,
> 
> I've just opened a new PR (#1028), since I have a somewhat unrelated bone to pick with these icons and didn't want to make you do what I believe is the necessary work to sort things out, since it's a _lot_ of refactoring. 😅
> 
> I hope I didn't step on your toes, it was all done in good faith. 🙈

Fine with me… I have enough to do! 😅 I see you stole some of these… So I should go ahead and just close this PR?

**Comment by karsa-mistmere** [comment]
Nah, not yet, I still want to see what @ericfennis thinks of that other one.
And obviously, should that one get merged, you'll be duly credited. :)

**Comment by ericfennis** [comment]
Closed by #1028

**Pull request closed without merging**
