### PR TITLE
feat(icons): added `fork-in-road` icon

### PR DESCRIPTION
**Pull request by sempijja**
## What is the purpose of this pull request?
- [x] New Icon
image

### Icon use case

This pull request introduces a new "fork-in-road" icon to our map interface assets. The icon represents an upcoming split or division in the route where users must choose between two or more paths.

Purpose:
The primary purpose of this icon is to provide clear visual guidance for users navigating complex road networks, highways, or decision points in various transportation scenarios. It alerts users to upcoming route choices, enhancing navigation accuracy and user experience.

Categories:
1. Navigation
2. Route Guidance
3. Traffic Signs

Real-life use cases:

1. Highway navigation: Alerting drivers to an upcoming major highway split, such as I-95 dividing into I-95 and I-295.

2. Airport approach: Guiding travelers to choose between terminals or specific airline areas as they approach an airport complex.

3. National park trail systems: Indicating trail splits for hikers, where paths diverge to different natural attractions or campsites.

4. Urban transit networks: Showing passengers where a bus or tram route splits into multiple directions, each serving different city areas.

5. Bike path navigation: Alerting cyclists to upcoming path divisions in extensive urban or rural cycling networks.

6. Theme park navigation: Guiding visitors through large amusement parks where paths split to different themed areas or attractions.

7. Shopping mall wayfinding: Indicating where corridors split to different wings or levels of a large shopping complex.

8. University campus navigation: Showing students and visitors where campus paths diverge to different faculties or facilities.

9. Industrial complex routing: Guiding truck drivers or workers through large industrial areas where roads split to different loading docks or facilities.

10. Ski resort trail maps: Indicating where ski runs split into different difficulty levels or end points on the mountain.

11. Emergency evacuation routes: Showing critical decision points in evacuation plans for large buildings or urban areas.

12. Harbor navigation: Guiding boats to choose between different channels or docking areas as they approach a port.

### Concept

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] The icons are solely my own creation.
- [x] The icons were originally created in #<issueNumber> by @Sempijja
- [x] I've based them on the following Lucide icons: `fork-in-road`
- [ ] I've based them on the following design: 

### Naming

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by jguddas** [comment]
Feels a bit big.

**Comment by karsa-mistmere** [comment]
Hi @sempijja,

The lines are off-grid, can you fix that?

I also agree with @jguddas, I think we could stick within `square`'s dimensions, keeping this in line with [`expand`](https://lucide.dev/icons/expand).

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+22v-9.17a2+2+0+0+1+.586-1.415L21+3%22+/%3E%3Cpath+d=%22M21+8V3h-5%22+/%3E%3Cpath+d=%22m3+3+8.414+8.414A2+2+0+0+1+12+12.828%22+/%3E%3Cpath+d=%22M8+3H3v5%22+/%3E">icons<br/>Open lucide studio</a>

**Comment by karsa-mistmere** [comment]
Ah, wait a minute, this is a duplicate of https://lucide.dev/icons/split

**Comment by sempijja** [comment]
I don't think its the same thing especially if you look at it from a road user perspective because it has that break in the flow but well.

This is the user interface use case perspective;
image

**Comment by jguddas** [comment]
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?name=split&base=split&value=%3Cpath+d=%22M12+22v-8.3a4+4+0+0+0-1.172-2.872L3+3%22+/%3E%3Cpath+d=%22M12.5+7V3%22+/%3E%3Cpath+d=%22M8+3H3v5%22+/%3E">icons<br/>Open lucide studio</a>
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?name=split&base=split&value=%3Cpath+d=%22M12+22v-8.3a4+4+0+0+0-1.172-2.872L3+3%22+/%3E%3Cpath+d=%22m15+9+4-4%22+/%3E%3Cpath+d=%22M8+3H3v5%22+/%3E">icons<br/>Open lucide studio</a>
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?name=split&base=split&value=%3Cpath+d=%22M+3+14+L+8+14%22+/%3E%3Cpath+d=%22M12+22v-8.3a4+4+0+0+0-1.172-2.872L3+3%22+/%3E%3Cpath+d=%22M8+3H3v5%22+/%3E">icons<br/>Open lucide studio</a>

**Pull request closed without merging**
