### PR TITLE
fix(lucide-svelte): update IconProps to include all properties of Icon component

### LINKED ISSUE #2114: svelte-check error when using ComponentType<Icon>
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [X] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.376.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [X] Windows
- [X] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

When using the latest version of lucide-svelte (0.376.0 and 0.376.1), using the pattern [described on the Lucide website](https://lucide.dev/guide/packages/lucide-svelte#types) to pass icon components causes the following error in `svelte-check`:
```
Error: Type 'typeof Home' is not assignable to type 'ComponentType<Icon>'.
  Types of construct signatures are incompatible.
    Type 'new (options: ComponentConstructorOptions<IconProps>) => Home' is not assignable to type 'new (options: ComponentConstructorOptions<{ [x: string]: any; name?: string | undefined; color?: string | undefined; size?: string | number | undefined; strokeWidth?: string | number | undefined; absoluteStrokeWidth?: boolean | undefined; iconNode: IconNode; mergeClasses?: (<ClassType = string>(...classes: ClassType[]) => string) | undefined; }>) => Icon'.
      Property 'mergeClasses' is missing in type 'SvelteComponentTyped<IconProps, { [evt: string]: CustomEvent<any>; }, { default: {}; }>' but required in type 'Icon'. (ts)
                        href: '/',
                        icon: Home,
                },
```

### Steps to reproduce

Follow the [steps documented on the Lucide website](https://lucide.dev/guide/packages/lucide-svelte#types) to create a new project using the Svelte library, then copy the typescript example from the Types section and run svelte-check.

1. Create a new Svelte project using Typescript:
    ```
    npm create svelte@latest myapp
    cd myapp
    npm install
    npm run dev
    ```
2. Install lucide-svelte: `npm install lucide-svelte`
3. Open the default `+page.svelte` file and replace its contents with the example contents from the Types section on the Lucide website:
    ```
    <script lang="ts">
      import Home from 'lucide-svelte/icons/home';
      import Library from 'lucide-svelte/icons/library';
      import Cog from 'lucide-svelte/icons/cog';
      import type { ComponentType } from 'svelte';
      import type { Icon } from 'lucide-svelte';
    
      type MenuItem = {
        name: string;
        href: string;
        icon: ComponentType<Icon>;
      }
    
      const menuItems: MenuItem[] = [
        {
          name: 'Home',
          href: '/',
          icon: Home,
        },
        {
          name: 'Blog',
          href: '/blog',
          icon: Library,
        },
        {
          name: 'Projects',
          href: '/projects',
          icon: Cog,
        }
      ];
    </script>
    
    {#each menuItems as item}
      <a href={item.href}>
       <svelte:component this={item.icon} />
        <span>{item.name}</span>
      </a>
    {/each}
    ```
4. Run svelte-check against the project: `npm run check`
5. It should pass, but instead causes the following errors:
    ```
    npm run check

    > lucide-typescript-bug@0.0.1 check
    > svelte-kit sync && svelte-check --tsconfig ./tsconfig.json
    
    
    ====================================
    Loading svelte-check in workspace: s:\code\lucide-typescript-bug
    Getting Svelte diagnostics...
    
    s:\code\lucide-typescript-bug\src\routes\+page.svelte:18:4
    Error: Type 'typeof Home' is not assignable to type 'ComponentType<Icon>'.
      Types of construct signatures are incompatible.
        Type 'new (options: ComponentConstructorOptions<IconProps>) => Home' is not assignable to type 'new (options: ComponentConstructorOptions<{ [x: string]: any; name?: string | undefined; color?: string | undefined; size?: string | number | undefined; strokeWidth?: string | number | undefined; absoluteStrokeWidth?: boolean | undefined; iconNode: IconNode; mergeClasses?: (<ClassType = string>(...classes: ClassType[]) => string) | undefined; }>) => Icon'.
          Property 'mergeClasses' is missing in type 'SvelteComponentTyped<IconProps, { [evt: string]: CustomEvent<any>; }, { default: {}; }>' but required in type 'Icon'. (ts)
                            href: '/',
                            icon: Home,
                    },
    
    
    s:\code\lucide-typescript-bug\src\routes\+page.svelte:23:4
    Error: Type 'typeof Library' is not assignable to type 'ComponentType<Icon>'.
      Types of construct signatures are incompatible.
        Type 'new (options: ComponentConstructorOptions<IconProps>) => Library' is not assignable to type 'new (options: ComponentConstructorOptions<{ [x: string]: any; name?: string | undefined; color?: string | undefined; size?: string | number | undefined; strokeWidth?: string | number | undefined; absoluteStrokeWidth?: boolean | undefined; iconNode: IconNode; mergeClasses?: (<ClassType = string>(...classes: ClassType[]) => string) | undefined; }>) => Icon'.
          Property 'mergeClasses' is missing in type 'SvelteComponentTyped<IconProps, { [evt: string]: CustomEvent<any>; }, { default: {}; }>' but required in type 'Icon'. (ts)
                            href: '/blog',
                            icon: Library,
                    },
    
    
    s:\code\lucide-typescript-bug\src\routes\+page.svelte:28:4
    Error: Type 'typeof Cog' is not assignable to type 'ComponentType<Icon>'.
      Types of construct signatures are incompatible.
        Type 'new (options: ComponentConstructorOptions<IconProps>) => Cog' is not assignable to type 'new (options: ComponentConstructorOptions<{ [x: string]: any; name?: string | undefined; color?: string | undefined; size?: string | number | undefined; strokeWidth?: string | number | undefined; absoluteStrokeWidth?: boolean | undefined; iconNode: IconNode; mergeClasses?: (<ClassType = string>(...classes: ClassType[]) => string) | undefined; }>) => Icon'.
          Property 'mergeClasses' is missing in type 'SvelteComponentTyped<IconProps, { [evt: string]: CustomEvent<any>; }, { default: {}; }>' but required in type 'Icon'. (ts)
                            href: '/projects',
                            icon: Cog,
                    }
    
    
    s:\code\lucide-typescript-bug\src\routes\+page.svelte:35:4
    Error: Property 'iconNode' is missing in type '{}' but required in type '{ [x: string]: any; name?: string | undefined; color?: string | undefined; size?: string | number | undefined; strokeWidth?: string | number | undefined; absoluteStrokeWidth?: boolean | undefined; iconNode: IconNode; mergeClasses?: (<ClassType = string>(...classes: ClassType[]) => string) | undefined; }'. (ts)
            <a href={item.href}>
                    <svelte:component this={item.icon} />
                    <span>{item.name}</span>
    
    
    ====================================
    svelte-check found 4 errors and 0 warnings in 1 file
    ```

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

### PR DESCRIPTION
**Pull request by garrettpauls**
closes #2114

## What is the purpose of this pull request?
- [ ] New Icon
- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description
`svelte-check` currently errors due to a type mismatch between the Icon component type (`ComponentType<Icon>`) and the generated icons. This fixes that bug by updating the exported `IconProps` type to contain all properties of the `Icon` component.

The `iconNode` property was also given a default empty value (`[]`) which was necessary to get the constructor parameters to match between generated icons and `ComponentType<Icon>`.

This allows the [TypeScript example](https://lucide.dev/guide/packages/lucide-svelte#typescript-example) on the Lucide website to pass `svelte-check` type checking. I have verified that the example on the website both passes svelte-check and displays icons as expected with this change.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Review by ericfennis — APPROVED** [review]
Ah makes sense, Thanks for the fix!

**Comment by mrgreenstone** [comment]
Good work. But it still throws and error if `iconNode` in `IconProps` is optional.

**Comment by garrettpauls** [comment]
@mrgreenstone I hadn't encountered that, can you post an example of how you're using it and the error it gives?

**Comment by mrgreenstone** [comment]
Sure. I created this minimal example:

`icon.svelte`
```svelte
<script lang="ts">
  import type { Icon } from "lucide-svelte";
  import type { ComponentType } from "svelte";

  export let icon: ComponentType<Icon>;
</script>

<svelte:component this={icon} size="16"/>
```

`+page.svelte`
```svelte
<script lang="ts">
  import { Cog } from "lucide-svelte";
  import Icon from "./icon.svelte";
</script>

<Icon icon={Cog}/>
```

When `iconNode` is required I have to add the attribute `iconNode={[]}` to the `svelte:component` or else it throws the following error on the `svelte:component`:

```
Property 'iconNode' is missing in type '{ size: string; }' but required in type '{ [x: string]: any; name?: string | undefined; color?: string | undefined; size?: string | number | undefined; strokeWidth?: string | number | undefined; absoluteStrokeWidth?: boolean | undefined; iconNode: IconNode; }'.ts(2741)
Renders a component dynamically, using the component constructor specified as the this property. When the property changes, the component is destroyed and recreated.

If this is falsy, no component is rendered.
```

When `iconNode` is optional the `icon` attribute of the `Icon` component throws the following error:
```
Type 'typeof Cog' is not assignable to type 'ComponentType<Icon>'.
  Types of construct signatures are incompatible.
    Type 'new (options: ComponentConstructorOptions<IconProps>) => Cog' is not assignable to type 'new (options: ComponentConstructorOptions<{ [x: string]: any; name?: string | undefined; color?: string | undefined; size?: string | number | undefined; strokeWidth?: string | number | undefined; absoluteStrokeWidth?: boolean | undefined; iconNode: IconNode; }>) => Icon'.
      Construct signature return types 'Cog' and 'Icon' are incompatible.
        The types of '$$prop_def' are incompatible between these types.
          Type 'IconProps' is not assignable to type '{ [x: string]: any; name?: string | undefined; color?: string | undefined; size?: string | number | undefined; strokeWidth?: string | number | undefined; absoluteStrokeWidth?: boolean | undefined; iconNode: IconNode; }'.ts(2322)
```

I admit that I am not that skilled when it comes to reading errors.
So please tell me if have done something wrong.

**Comment by garrettpauls** [comment]
@mrgreenstone Interesting, that's the same as what I've been testing against. I looked into a bit more and I notice that I get no errors from `svelte-check` but I _do_ get that error inline in VS Code. I'll see what I can do to resolve it in both places instead of just for `svelte-check`...

**Review by ericfennis — APPROVED** [review]
@garrettpauls Good work!
And thanks for testing and checking @mrgreenstone!

**Pull request merged**
