### PR TITLE
Adds `leafy-green` icon

### LINKED ISSUE #1143: Leafy green 🥬 icon
## Icon Request

* Icon name: leafy-green
* Use case: to indicate various vegetables
* _Screenshots_ of similar icons: 🥬

### PR DESCRIPTION
**Pull request by karsa-mistmere**
closes #1143 

Based on `salad` by @kemie.
Also adds salad to the [emoji category](https://emojipedia.org/green-salad/).

### CODE REVIEW

**Comment by jguddas** [comment]
In 100% the arcs feel quite small, making it more pronounced might be nice.

**Comment by jguddas** [comment]
What about something like this icon (30) (I only changed the top arcs to show the difference)?

And what about adding a bit of a swoosh and making the center line not 100% straight?

**Comment by karsa-mistmere** [comment]
I prefer the simpler, more geometric style, but I'll let @ericfennis decide. :)

**Comment by ericfennis** [comment]
I prefer the simple one. :)

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
