### PR TITLE
feat(icons): adds microchip icon

### PR DESCRIPTION
**Pull request by karsa-mistmere**
## What is the purpose of this pull request?

- [x] New Icon

### Description
We do not currently have an icon that could represent GPUs, this PR adds a `microchip` icon that could stand in for either GPUs or RAM.

### Icon use case
- gpu
- ram
- microchip

### Alternative icon designs 
image

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] I've based them on the following Lucide icons: `cpu`

### Naming 
- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by ericfennis** [comment]
Maybe first design is a better fit?

**Comment by karsa-mistmere** [comment]
What do you think about this design?
image

**Comment by ericfennis** [comment]
@karsa-mistmere That will work. I think the right one will look the best on 100% scale with the tiny pins.

**Comment by jguddas** [comment]
All feel hard to identify.

**Comment by midnight-wonderer** [comment]
I like the top left one in the alternative designs.
For three reasons:
- The aspect ratio of the chip looks familiar. While the ratio itself IRL depends on pin count, I work with many ICs with similar ratios to that one.
- It has eight pins. While six pins are not unusual, eight are easier to come by.
- No weird line on top of the package. I don't know what that depicts.

PS.
Do you remember this guy?
Old Game

Probably add a curve on top to depict marking similar to the real IC package.

**Comment by karsa-mistmere** [comment]
So we basically have these four candidates?

image

Tbh, I'm not a very big fan of the notch, it's just too large proportionally.

**Comment by jguddas** [comment]
Do you have the studio link for the right most one 2nd row?

image

**Comment by karsa-mistmere** [comment]
> Do you have the studio link for the right most one 2nd row?
> 
> image

I didn't but now I do:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M18+12h2%22+/%3E%3Cpath+d=%22M18+16h2%22+/%3E%3Cpath+d=%22M18+20h2%22+/%3E%3Cpath+d=%22M18+4h2%22+/%3E%3Cpath+d=%22M18+8h2%22+/%3E%3Cpath+d=%22M4+12h2%22+/%3E%3Cpath+d=%22M4+16h2%22+/%3E%3Cpath+d=%22M4+20h2%22+/%3E%3Cpath+d=%22M4+4h2%22+/%3E%3Cpath+d=%22M4+8h2%22+/%3E%3Cpath+d=%22M8+2a2+2+0+0+0-2+2v16a2+2+0+0+0+2+2h8a2+2+0+0+0+2-2V4a2+2+0+0+0-2-2h-1.5c-.276+0-.494.227-.562.495a2+2+0+0+1-3.876+0C9.994+2.227+9.776+2+9.5+2z%22+/%3E&name=image">icons<br/>Open lucide studio</a>

**Comment by jguddas** [comment]
image (4)
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M13.725+3a2+2+0+0+1-3.452+0%22+/%3E%3Cpath+d=%22M18+12h2%22+/%3E%3Cpath+d=%22M18+16h2%22+/%3E%3Cpath+d=%22M18+20h2%22+/%3E%3Cpath+d=%22M18+4h2%22+/%3E%3Cpath+d=%22M18+8h2%22+/%3E%3Cpath+d=%22M4+12h2%22+/%3E%3Cpath+d=%22M4+16h2%22+/%3E%3Cpath+d=%22M4+20h2%22+/%3E%3Cpath+d=%22M4+4h2%22+/%3E%3Cpath+d=%22M4+8h2%22+/%3E%3Cpath+d=%22M9.5+2.677A2+2+0+0+0+6+4v16a2+2+0+0+0+2+2h8a2+2+0+0+0+2-2V4a2+2+0+0+0-3.5-1.324%22+/%3E&name=image">icons<br/>Open lucide studio</a>

**Comment by ericfennis** [comment]
Hmm I'm more in for the first design. To keep it simple.
I know the notch is there in some chips in real life. But feels a bit weird to me to make it part of the design. I think the shape should be consistent with the CPU icon.

But it's my opinion if you all like this design I go with you.

**Review by jguddas — APPROVED** [review]

**Comment by jguddas** [comment]
What about rotating it +90°?
Most icons that can be horizontal are horizontal after all?

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
