### PR TITLE
Adds common API elements to the Angular package

### PR DESCRIPTION
**Pull request by karsa-mistmere**
Features an almost complete rewrite of the Angular package based on recommendations for the latest version:
- Upgraded to Angular 15
- Added input properties for manually overriding: `size`, `color`, `strokeWidth`, as well as implementing the latest `scaleStrokeWidth` property (as per #939).
- Additional icons can now be provided using the `LUCIDE_ICONS` injection token expecting an instance of `LucideIconProviderInterface`, with multiple providers supported.
  (Also added legacy support for the class based `Icons` provider but marked it as deprecated).
- The new provider class improves performance by no longer making it necessary to [duplicate the icon list in each and every component on every change](https://github.com/lucide-icons/lucide/blob/d0f26f41105210b98048c21bab47e135f9621687/packages/lucide-angular/src/lib/lucide-angular.component.ts#L36) instead working as a data access service.
- Deprecated some unfortunately generically named types and classes in favour of prefixed names (`Icons` => `LucideIcons`) and added deprecation notices to the former.
- Migrated to `pnpm` from `npm`.
- Migrated linting to ESlint using the recommended Angular configuration from the deprecated TSlint and added Prettier support.
- Migrated to the recommended [`public-api.ts`](https://github.com/nrwl/nx/issues/155) export format from `index.ts`.
- Added proper unit testing to `LucideAngularComponent`.
- Rewrote documentation to be much more simple and streamlined.

### CODE REVIEW

**Comment by ericfennis** [comment]
@karsa-mistmere Really nice work.
Maybe we can release an alpha/beta version so we can do some testing?

**Comment by karsa-mistmere** [comment]
Yeah, definitely, a preview release would be super useful.

**Comment by ericfennis** [comment]
@karsa-mistmere I release a beta version on `0.125.0-beta.0`

To install and test
```
npm install lucide-angular@0.125.0-beta.0
```

**Review by ericfennis — APPROVED** [review]

**Comment by dsnoeck** [comment]
Thanks for the beta, but I still have error using it 

Testing with Angular: 13 and lucide-angular: 0.125.0-beta.0

```
./node_modules/lucide-angular/fesm2020/lucide-angular.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/Users/dsnoeck/Documents/workspace/COCKPIT/abu-dhabi-cockpit/web-client/node_modules/lucide-angular/fesm2020/lucide-angular.mjs: This application depends upon a library published using Angular version 15.2.0, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  13599 | }
  13600 | LucideAngularComponent.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "15.2.0", ngImport: i0, type: LucideAngularComponent, deps: [{ token: ElementRef }, { token: ChangeDetectorRef }, { token: LUCIDE_ICONS }], target: i0.ɵɵFactoryTarget.Component });
> 13601 | LucideAngularComponent.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "14.0.0", version: "15.2.0", type: LucideAngularComponent, selector: "lucide-angular, lucide-icon, i-lucide, span-lucide", inputs: { class: "class", name: "name", img: "img", color: "color", size: "size", strokeWidth: "strokeWidth", absoluteStrokeWidth: "absoluteStrokeWidth"[3[39m9m }, usesOnChanges: true, ngImport: i0, template: '<ng-content></ng-content>', isInline: true });
        |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[3[39m1m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[3[39m1m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[3[39m1m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[3[39m1m^^^^^^^^^^^^^^^^^^^^^^
  13602 | i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "15.2.0", ngImport: i0, type: LucideAngularComponent, decorators: [{
  13603 |             type: Component$1,
  13604 |             args: [{'
    at run (/Users/dsnoeck/Documents/workspace/COCKPIT/abu-dhabi-cockpit/web-client/node_modules/@babel/core/lib/transformation/index.js:37:15)
    at run.next (<anonymous>)
    at Function.transform (/Users/dsnoeck/Documents/workspace/COCKPIT/abu-dhabi-cockpit/web-client/node_modules/@babel/core/lib/transform.js:25:41)
    at transform.next (<anonymous>)
    at step (/Users/dsnoeck/Documents/workspace/COCKPIT/abu-dhabi-cockpit/web-client/node_modules/gensync/index.js:261:32)
    at /Users/dsnoeck/Documents/workspace/COCKPIT/abu-dhabi-cockpit/web-client/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/dsnoeck/Documents/workspace/COCKPIT/abu-dhabi-cockpit/web-client/node_modules/gensync/index.js:223:11)
    at /Users/dsnoeck/Documents/workspace/COCKPIT/abu-dhabi-cockpit/web-client/node_modules/gensync/index.js:37:40

Error: node_modules/lucide-angular/lib/lucide-angular.component.d.ts:41:18 - error TS2314: Generic type 'ɵɵComponentDeclaration' requires 7 type argument(s).

41     static ɵcmp: i0.ɵɵComponentDeclaration<LucideAngularComponent, "lucide-angular, lucide-icon, i-lucide, span-lucide", never, { "class": "class"; "name": "name"; "img": "img"; "color": "color"; "size": "size"; "strokeWidth": "strokeWidth"; "absoluteStrokeWidth": "absoluteStrokeWidth"; }, {}, never, ["*"], false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✖ Failed to compile.
```

**Comment by dsnoeck** [comment]
Version 0.190.0 fixes remaining issues.

**Pull request merged**
