### PR TITLE
fix(icons): rename `box-select` to `square-dashed`

### PR DESCRIPTION
**Pull request by chessurisme**
## What is the purpose of this pull request?

- [ ] New Icon
- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

The icon named `box-select` violates the naming convention as outlined in [Naming convention in Lucide's design principle #3](https://lucide.dev/guide/design/icon-design-guide#naming-conventions). Instead of using `box-select`, we will rename it to `square-dashed`, following the convention used in names like `square-dashed-mouse-pointer`.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Review by jguddas — CHANGES_REQUESTED** [review]
Don't forget to add the alias field for backwards compatibility.

**Comment by chessurisme** [comment]
How do I? I haven't read any ‘alias’ or same thing in the documentation. Would you point out similar icons that renamed like `box-select`? Thanks.

**Comment by jguddas** [comment]
> How do I? I haven't read any ‘alias’ or same thing in the documentation. Would you point out similar icons that renamed like `box-select`? Thanks.

You can search the code it's in the .json, I'm on the phone right now, that's the best I can do.

**Comment by chessurisme** [comment]
I already added an aliases.

**Review by jguddas — APPROVED** [review]

**Pull request merged**
