### PR TITLE
feat(icons): add `cannabis` icon

### LINKED ISSUE #1900: Add `cannabis` (marijuana/weed/pot) icon
### Icon name

cannabis

### Use cases

I need a cannabis icon for a dating app I'm building, to show whether that person uses cannabis or not.

### Design ideas

https://fontawesome.com/search?q=weed&o=r

Screenshot 2024-02-17 at 7 36 36 PM

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

### PR DESCRIPTION
**Pull request by jguddas**
closes #1900

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

A cannabis leaf icon.

### Icon use case 

- To show whether that person uses cannabis or not.
- Map indicator for dispensaries.
- Representing a section in an online store that sells cannabis-related products.
- Indicating a news category or blog post topic related to cannabis.
- Representing cannabis-related laws or regulations in infographics or educational materials.
- In a healthcare or pharmaceutical context, symbolizing medical marijuana prescriptions or treatments.
- In an app tracking personal habits or health metrics, representing cannabis consumption.

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [ ] I've based them on the following Lucide icons: 
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [ ] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
These parts feel a bit too wavy:
image

**Comment by karsa-mistmere** [comment]
My version based on yours: image

**Comment by jguddas** [comment]
> My version based on yours: image

Can you share the svg?

**Comment by karsa-mistmere** [comment]
Sure: https://lucide-studio.vercel.app/?value=%3Csvg++xmlns=%22http://www.w3.org/2000/svg%22++width=%2224%22++height=%2224%22++viewBox=%220+0+24+24%22++fill=%22none%22++stroke=%22currentColor%22++stroke-width=%222%22++stroke-linecap=%22round%22++stroke-linejoin=%22round%22%3E++%3Cpath+d=%22M12+22v-4%22+/%3E++%3Cpath+d=%22M7+12c-1.5+0-4.5+1.5-5+3+3.5+1.5+6+1+6+1-1.5+1.5-2+3.5-2+5+2.5+0+4.5-1.5+6-3+1.5+1.5+3.5+3+6+3+0-1.5-.5-3.5-2-5+0+0+2.5.5+6-1-.5-1.5-3.5-3-5-3+1.5-1+4-4+4-6-2.5+0-5.5+1.5-7+3+0-2.5-.5-5-2-7-1.5+2-2+4.5-2+7-1.5-1.5-4.5-3-7-3+0+2+2.5+5+4+6%22+/%3E%3C/svg%3E&name=image

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
