### PR TITLE
Optimise/add remaining `panel-*`/consolidate `layout` icons

### PR DESCRIPTION
**Pull request by danielbayley**
Following up from https://github.com/lucide-icons/lucide/pull/1003#issuecomment-1521387131 …

> For example `panel-top-left` is currently conflicting with layout icons.

I propose to rename `layout` as `panels-top-left` (leaving `layout` as an alias), to make it part of the `panel-*` set in #1003, and this PR… Which is meant to cover `layout-panel-*` [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html) for use in an upcoming VS Code _Lucide_ product and file icon theme…

`panels-top-left` (currently https://lucide.dev/icons?search=layout) is also `project-*` from [octicons](https://primer.style/design/foundations/icons), obviously as you can see above, right here on GitHub… So relevant `tags` also added, and `panels-top-left-dashed` as `project-template` from the same set.

Related to #1059, #1181, #1201, #1498 and #1500.

---

Edit: As per https://github.com/lucide-icons/lucide/pull/1156#issuecomment-1696013745, leaving these here for reference…

preview

### CODE REVIEW

**Comment by danielbayley** [comment]
> This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 5 days.

Need these for [vscode-lucide-icons](https://github.com/danielbayley/vscode-lucide-icons) 😢

**Comment by karsa-mistmere** [comment]
# I think we should keep only these:
                  


# And remove these:

**Comment by danielbayley** [comment]
> I think we should keep only these: …
> And remove these: …

They were all included to cover [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html), for [vscode-lucide-icons](https://github.com/danielbayley/vscode-lucide-icons)…

For which I now have a build step that bundles a bunch of SVG icons—which for whatever reason were rejected, or otherwise yet to be merged—into another, separate font for use in the extension. However then it does cease to be _strictly_ Lucide… What are your thoughts on that? @karsa-mistmere cc: @jguddas @ericfennis 

Preview below…

image

**Comment by karsa-mistmere** [comment]
> They were all included to cover [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html), for [vscode-lucide-icons](https://github.com/danielbayley/vscode-lucide-icons)…
> 
> For which I now have a build step that bundles a bunch of SVG icons—which for whatever reason were rejected, or otherwise yet to be merged—into another, separate font for use in the extension. However then it does cease to be _strictly_ Lucide… What are your thoughts on that? @karsa-mistmere cc: @jguddas @ericfennis

I don't mind, in fact I think in any app using custom icons is sometimes necessary, and that need should be handled by that particular app instead of putting the burden on Lucide.

**Comment by danielbayley** [comment]
@karsa-mistmere See latest changes, and left the rest here https://github.com/lucide-icons/lucide/pull/1156#issue-1683023121 for reference…

**Review by ericfennis — APPROVED** [review]
I think this one is good to go.

**Review by jguddas — APPROVED** [review]

**Review by karsa-mistmere — APPROVED** [review]

**Pull request merged**
