### PR TITLE
Add flora icons

### PR DESCRIPTION
**Pull request by danielbayley**
`trees-forest` matches `tent-tree` in https://github.com/lucide-icons/lucide/pull/1409#issuecomment-1612273766.

`flower-rose-single` alts…

preview

Also been playing around with some animation for something else…

rose

---

`cactus` alts…

preview

### CODE REVIEW

**Review by ericfennis — COMMENTED** [review]
@danielbayley Nice work, the icons are nice.
But I think multiple variants for some are a bit too much.
So I think one cactus and one tree-forest is enough.

I doubt the design for the pond, not sure if the clear what the design tries to tell on 100%.

**Comment by danielbayley** [comment]
> I think one cactus

@ericfennis Between [the `commit`ed variants](https://github.com/lucide-icons/lucide/pull/1398#issuecomment-1606095062) and [the alts posted above](https://github.com/lucide-icons/lucide/pull/1398#issue-1773288032), which do you think…? cc: @karsa-mistmere @jguddas

**Comment by ericfennis** [comment]
@danielbayley So for the icons icon, I vote for the third one in the examples in your description.

**Comment by ericfennis** [comment]
Oh I thought more one of those ones.
image

 I think those ones are a bit more recognizable for a simple cactus. 
Like this:
image

Let me know what you think.

**Comment by danielbayley** [comment]
@ericfennis See latest changes…

**Review by ericfennis — APPROVED** [review]

**Comment by jguddas** [comment]
Those two lily pads look a bit out of place, what about something like this?

**Comment by ericfennis** [comment]
This PR is merged to the lab branch. This PR does not match our [PR template](https://github.com/lucide-icons/lucide/blob/main/.github/pull_request_template.md), which requires valid use cases. To move on we merged this PR to the [lab branch](https://github.com/lucide-icons/lucide/tree/lab), which will be moved to a separate repo in the future.

**Pull request merged**
