### PR TITLE
add power-on icon

### PR DESCRIPTION
**Pull request by mittalyashu**
<details>
    <summary>Old design</summary>

| Preview |
| --- |
| CleanShot 2021-01-31 at 11 50 52@2x |
</details>

| Preview |
| --- |
| image |

### CODE REVIEW

**Comment by mittalyashu** [comment]
@ericfennis How about this?

| Preview |
| --- |
| CleanShot 2021-02-02 at 15 02 54@2x |

**Comment by ericfennis** [comment]
@mittalyashu like it!

**Comment by mittalyashu** [comment]
@ericfennis can you review the PR again?

**Comment by ericfennis** [comment]
Nice looks good.
I am a little bit doubting about the name.
I think it should include `plug` in de name.

`plug-zap`
`plug-power`
🤔

**Comment by mittalyashu** [comment]
@ericfennis How about `plug-zap`?

**Comment by locness3** [comment]
> @ericfennis How about `plug-zap`?

and then we'd also have `plug` alone

**Comment by ericfennis** [comment]
@mittalyashu `plug-zap` is allright.

**Comment by ericfennis** [comment]
@locness3 Exactly, in this way we keep the icons and variants grouped

**Review by ericfennis — CHANGES_REQUESTED** [review]
Rename to `plug-zap` or something with plug

**Comment by locness3** [comment]
and add a standalone `plug`

**Pull request merged**
