### PR TITLE
Added radii to `whole-word` and `space`

### PR DESCRIPTION
**Pull request by jguddas**

### CODE REVIEW

**Comment by danielbayley** [comment]
@jguddas Also https://lucide.dev/icon/space?search=space

**Comment by karsa-mistmere** [comment]
Not sure about this change, I think it hurts overall legibility.

**Comment by danielbayley** [comment]
@karsa-mistmere @jguddas What about 1px rounding?

**Comment by danielbayley** [comment]
@karsa-mistmere @jguddas What about 1px radius…?

Untitled

Untitled

**Pull request closed without merging**
