### PR TITLE
Add history icon

### PR DESCRIPTION
**Pull request by ericfennis**
image

Closes [#291](https://github.com/feathericons/feather/issues/291)

### CODE REVIEW

**Comment by mittalyashu** [comment]
Can you try making (those two inner-hands) bit by 1 or 2 px's?

**Comment by ericfennis** [comment]
you mean shorter?

Here one with 1px shorter.
image

**Comment by mittalyashu** [comment]
yes, the right one @ericfennis 

In the left part, the two hands, does it matches (shape and size) with rest of icons?

**Comment by ericfennis** [comment]
Hmm seeing this smaller the left one looks better
Group 20

**Pull request merged**
