### PR TITLE
Fix duplicate keys being generated if SVG attributes are identical

### PR DESCRIPTION
**Pull request by FPDK**
Fixes issue #244 by adding an extra attribute to the generated hash

### CODE REVIEW

**Comment by ericfennis** [comment]
I think this fix is not needed. The hash is generated based on the svg elements, I checked the code of the [`cloud-upload.svg`](https://github.com/lucide-icons/lucide/blob/master/icons/upload-cloud.svg?short_path=0e2da28). And the icon contains double elements. 
So I think we need to fix this icon.

**Comment by FPDK** [comment]
What if I change it so it throws on duplicate keys?
Then it could serve as a test, at least when _renderUniqueKey_ is on.

**Comment by ericfennis** [comment]
@FPDK yeah exactly, we need to add check in the build.

**Comment by ericfennis** [comment]
I added a check for the duplicated children in [a03ece6](https://github.com/lucide-icons/lucide/pull/272/commits/e8ca0a479ceacb27a5f1765a9f631045d77e8af2). So the build will fail if there are duplicated children.

**Pull request closed without merging**
