### PR TITLE
Add packages sections

### LINKED ISSUE #336: Promote the library packages on the website
The Lucide packages and librairies should be promoted on the lucide.dev website somehow.

### PR DESCRIPTION
**Pull request by ericfennis**
I added a packages section, you can navigate via the packages link in the nav.
And worked on the first version of the docs section, but that need to be completed with a sidebar for links and some nice navigation. The markdown part is completely done.

Closes #336 

Preview:

image

### CODE REVIEW

**Comment by locness3** [comment]
I'd also put this stuff somewhere on the homepage. Like `use it with : React / Vue / ...`

**Comment by locness3** [comment]
Or just a more prominent link to this page.

**Comment by ericfennis** [comment]
Yeah good idea, small section with all the supported frameworks.

**Comment by ericfennis** [comment]
Added small section to the homepage.
image

**Comment by locness3** [comment]
Nice, maybe a bit smaller.

**Comment by ericfennis** [comment]
@locness3 Resized them!

**Comment by locness3** [comment]
Looks good! Final suggestions :
- make the "available for" text link to the packages page
- add a line break between the "available for" text and the icons, on mobile but maybe also on desktoo

**Comment by ericfennis** [comment]
@locness3 got ya!

**Comment by ericfennis** [comment]
@locness3 I think this is it, can you check if it is right?

**Comment by locness3** [comment]
Perfect.

**Comment by locness3** [comment]
Oh, shouldn't the downloads/version badges on the packages page link to something?

**Comment by ericfennis** [comment]
I added them @locness3  tnx for noticing.
If you find more thing let me know, I will fix it in an other PR

**Pull request merged**
