### PR TITLE
Add bank icon

### PR DESCRIPTION
**Pull request by BeezBeez**
Preview : 
image

### CODE REVIEW

**Comment by ericfennis** [comment]
@BeezBeez Thanks for submitting this icon, looks awesome!

Did you read the [Icon Design Guide](https://github.com/lucide-icons/lucide/blob/master/docs/ICON_DESIGN_GUIDE.md)?

**Comment by nixoncode** [comment]
See #350 landmark icon

**Comment by mittalyashu** [comment]
@nixoncode can you run the optimise script?

**Comment by BeezBeez** [comment]
@connium Seem like to have created a pull request for this icon

**Comment by ericfennis** [comment]
@BeezBeez Sorry I leave this one for now, please join the discussion in #358.

**Pull request closed without merging**
