### PR TITLE
Icons/outlined

### PR DESCRIPTION
**Pull request by Heahl**
## What is the purpose of this pull request? 

- [X] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Description

Added kununu and Xing Icons

### Icon use case 

For social buttons, I can't think of more use cases. Should be reasonable enough, though.

### Alternative icon designs 

-

#### Concept 

- [X] I have provided valid use cases for each icon.
- [ ] I have not added any a brand or logo icon.
- [X] I have not used any hate symbols.
- [X] I have not included any religious or political imagery.

#### Author, credits & license

- [X] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [ ] I've based them on the following Lucide icons: 
- [ ] I've based them on the following design: 

#### Naming 

- [X] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [X] I've named icons by what they are rather than their use case.
- [X] I've provided meta JSON files in `icons/[iconName].json`.

#### Design 

- [X] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [X] I've made sure that the icons look sharp on low DPI displays.
- [X] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [X] I've made sure that the icons are visually centered.
- [X] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [X] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [X] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
> What can I improve @karsa-mistmere ?

We do not accept brand icons: #670

**Comment by Heahl** [comment]
You mean you don’t accept specific brand icons? Because there are already twenty in your DB. So what is wrong with these two? @karsa-mistmere ?
________________________________
Von: Karsa ***@***.***>
Gesendet: Thursday, August 24, 2023 6:22:41 PM
An: lucide-icons/lucide ***@***.***>
Cc: Heahl ***@***.***>; Author ***@***.***>
Betreff: Re: [lucide-icons/lucide] Icons/outlined (PR #1530)


What can I improve @karsa-mistmere<https://github.com/karsa-mistmere> ?

We do not accept brand icons: #670<https://github.com/lucide-icons/lucide/issues/670>

**Comment by karsa-mistmere** [comment]
#670 #94

**Comment by Heahl** [comment]
Ah sry, just read the issue #670. Still don’t understand the decision. Can you give me a short reasoning for that?
________________________________
Von: H A ***@***.***>
Gesendet: Thursday, August 24, 2023 10:04:15 PM
An: lucide-icons/lucide ***@***.***>; lucide-icons/lucide ***@***.***>
Cc: Author ***@***.***>
Betreff: Re: [lucide-icons/lucide] Icons/outlined (PR #1530)

You mean you don’t accept specific brand icons? Because there are already twenty in your DB. So what is wrong with these two? @karsa-mistmere ?
________________________________
Von: Karsa ***@***.***>
Gesendet: Thursday, August 24, 2023 6:22:41 PM
An: lucide-icons/lucide ***@***.***>
Cc: Heahl ***@***.***>; Author ***@***.***>
Betreff: Re: [lucide-icons/lucide] Icons/outlined (PR #1530)


What can I improve @karsa-mistmere<https://github.com/karsa-mistmere> ?

We do not accept brand icons: #670<https://github.com/lucide-icons/lucide/issues/670>

**Pull request closed without merging**
