### PR TITLE
add sidebar open & close icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-02-03 at 22 28 09@2x |

### CODE REVIEW

**Comment by ericfennis** [comment]
Nice icon!

**Comment by mittalyashu** [comment]
@ericfennis it doesn't look good in the sense that, it doesn't depicts the difference between sidebar and main.

| Preview |
| --- |
| CleanShot 2021-02-05 at 10 09 53@2x |

**Comment by ericfennis** [comment]
@mittalyashu I think it will work just fine. 
To me the other icons,the arrow looks not aligned to something. And that looks weird to me.

**Review by ericfennis — APPROVED** [review]

**Review by ericfennis — CHANGES_REQUESTED** [review]
@mittalyashu Can you try to make it consistent with the sidebar icon? 
image

**Pull request merged**
