### PR TITLE
fix(icons): add table-of-contents icon

### LINKED ISSUE #1859: [icon request] Outline or hierarchy
### Icon name

outline

### Use cases

This is when a button to show hierarchical content is needed. 

### Design ideas

outline

SVG:
outline

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

### PR DESCRIPTION
**Pull request by karsa-mistmere**
closes #1859 (up for debate)

## What is the purpose of this pull request?

- [x] New Icon

### Description
Adds a ToC icon.

### Icon use case 
- **Document Navigation**: An icon for a table of contents can be used in digital documents and eBooks to allow users to quickly navigate to different sections.
- **Websites and Blogs**: Use the icon on websites and blogs to help visitors jump to specific parts of long articles or pages.
- **PDF Viewers**: Integrate the icon into PDF viewers to offer a quick overview of the document's structure and enable easy access to different chapters.
- **Content Management Systems (CMS)**: Use the icon in CMS interfaces to assist users in organizing and accessing various content sections.
- **Educational Platforms**: Implement the icon in educational resources to help students and educators navigate through course materials and syllabi.
- **Software Documentation**: Include the icon in software documentation to allow developers and users to quickly find relevant sections.
- **Mobile Applications**: Use the icon in mobile apps to provide a clear and intuitive way for users to navigate lengthy content.
- **Project Management Tools**: Utilize the icon in project management software to help users quickly locate different parts of project plans and documentation.
- **Books and Manuals**: Integrate the icon in digital versions of books and manuals to enhance user experience by facilitating easy navigation.
- **Knowledge Bases**: Use the icon in knowledge bases and FAQs to allow users to jump to specific topics of interest.

### Alternative icon designs 
n/a

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] The icons are solely my own creation.

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Review by jguddas — COMMENTED** [review]
I feel like having rotated and flipped versions is kinda WET(not **D**on't**R**epeat**Y**ourself), not really a fan, even tho the use cases are really solid.

**Comment by karsa-mistmere** [comment]
> I feel like having rotated and flipped versions is kinda WET(not **D**on't**R**epeat**Y**ourself), not really a fan, even tho the use cases are really solid.

Part agree, part disagree, hear me out:

1. CSS transforms are cool – unless you want to apply animations or different transformations than the flipping/rotating. From then on, it can become utterly cumbersome to code your transform matrices (you can usually work around this issue by applying certain transforms to wrapper elements, but this isn't always a possibility).

2. Even if how an icon visually appears happens to be a reflection or rotation of a different icon, the use cases, hence the tags and categories may differ completely, so we do need to add at least the meta descriptors.

We could in theory add clever stuff to our JSONs that decrease redundancy in our SVG files, e.g.:

`table-of-contents.json`:
```json
{
  ...,
  "generateFrom": ["list", ["flip-x"]]
}
```

`arrow-up.json`:
```json
{
  ...,
  "generateFrom": ["arrow-right", ["rotate-90deg", "flip-y"]]
}
```

But up until we have something like this, I think "duplicate" icons are fine.

**Comment by jguddas** [comment]
Yeah, it's not really blocking, just something to think about.

What about naming conventions for flipped icons maybe `-rtl` or something?

**Comment by karsa-mistmere** [comment]
> Yeah, it's not really blocking, just something to think about.
> 
> What about naming conventions for flipped icons maybe `-rtl`?

That could work for icons that are actually just RTL versions of existing ones (e.g. `pilcrow-rtl`). In this scenario, for example, I think the `list`/`toc` reflection is purely coincidental.

**Comment by ericfennis** [comment]
@jguddas Yeah, I get your points, but on the other side, why make a complex system that will rotate icons when we can just rotate the "design" ourselves? It's not worth the effort I think.

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
