### PR TITLE
fix: fixed github icon api route issue

### PR DESCRIPTION
**Pull request by jguddas**

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
@jguddas: I've merged and rebased, but it doesn't seem to have done the job. :(

**Comment by jguddas** [comment]
Here it works with the preview deployment:

**Comment by karsa-mistmere** [comment]
Ah, yes, possibly the issue is that vercel is still deploying the new app.

**Comment by jguddas** [comment]
> Ah, yes, possibly the issue is only that Vercel is still deploying the new app.

And GitHub is caching stuff as well ...

**Comment by karsa-mistmere** [comment]
@jguddas: The build has finished, and things now seem to be working perfectly, thanks for the super quick fix, you're the best. ^_^

**Pull request merged**
