### PR TITLE
add scale icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-02-03 at 22 24 49@2x |

### CODE REVIEW

**Comment by ericfennis** [comment]
@mittalyashu Hmm I think we can refine this icon some more.
Are you ok if I give it a try?

**Comment by mittalyashu** [comment]
Sure

**Comment by ericfennis** [comment]
@mittalyashu 
What do you think of this?
image

**Comment by ericfennis** [comment]
@mittalyashu Like this? 

image

100% 
Frame 63

**Comment by mittalyashu** [comment]
@ericfennis The spacing looks fine to me, what about adding a curvy slant on both left and right side?

**Comment by ericfennis** [comment]
@mittalyashu Mneeh I'm not really fan of it, I think we should keep it simple.
image

**Comment by mittalyashu** [comment]
@ericfennis thats not what I mean.

Can you provide the source of the icon?

**Comment by ericfennis** [comment]
@mittalyashu Yes of course!
```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<rect width="24" height="24" fill="white"/>
<path d="M16 16L19 8L22.001 16C21.1353 16.649 20.0825 16.9999 19.0005 16.9999C17.9185 16.9999 16.8657 16.649 16 16Z" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M2 16L5 8L8.001 16C7.1353 16.649 6.08248 16.9999 5.0005 16.9999C3.91852 16.9999 2.8657 16.649 2 16Z" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M7 21H17" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M12 3V21" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M3 7H7L12 5L17 7H21" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

**Comment by ericfennis** [comment]
@mittalyashu I think the icons looks better without slant.

**Comment by mittalyashu** [comment]
@ericfennis That's what I mean by adding curves _(the preview below doesn't look much good)_.

CleanShot 2021-04-23 at 19 56 08@2x

**Comment by ericfennis** [comment]
@mittalyashu looks great, I think this is the one.

**Comment by mittalyashu** [comment]
@ericfennis LGTM

**Review by ericfennis — APPROVED** [review]

**Comment by ericfennis** [comment]
Looks good!

**Pull request merged**
