### PR TITLE
feat(icons): added `tray-horizontal` icon & `tray-vertical` icon

### LINKED ISSUE #1396: Meal tray
## Icon Request

* Icon name: Meal tray / `meal-tray`
* Use case: To represent bento or any kind of meal
* _Screenshots_ of similar icons: 
image
image

### PR DESCRIPTION
**Pull request by AndreasSas**
closes #1396 

## What is the purpose of this pull request?
- [x] Other: Icon update

### Description
Added new `tray-horizontal` icon.

### Icon use case

Can be used to represent mealtrays, as well as a general icon for GUI layouts

### Concept

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] The icons are solely my own creation.
- [x] The icons were originally created in #1396 by @AndreasSas 
- [ ] I've based them on the following Lucide icons: 
- [ ] I've based them on the following design: 

### Naming

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by jguddas** [comment]
There are gaps of less than 2px.

**Comment by AndreasSas** [comment]
> There are gaps of less than 2px.
Do you mean the rounded internal edges, if so adding the entire inside of the tray as straight lines feels to change the rigidity
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?dialog=false&name=aaa&value=%3Cpath+d=%22M10+4v16%22+/%3E%3Cpath+d=%22M2+15h8%22+/%3E%3Cpath+d=%22M2+9h8%22+/%3E%3Cpath+d=%22M22+12H10%22+/%3E%3Crect+x=%222%22+y=%224%22+width=%2220%22+height=%2216%22+rx=%222%22+/%3E">icons<br/>Open lucide studio</a>

If I combine the two then the shape stays consistent up until a line width of 0.75px witht the following shape:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?dialog=false&name=aaa&value=%3Cpath+d=%22M10+10a2+2+0+0+0+2+2+2+2+0+0+0-2+2%22+/%3E%3Cpath+d=%22M10+11a2+2+0+0+0-2-2+2+2+0+0+0+2-2%22+/%3E%3Cpath+d=%22M10+17a2+2+0+0+0-2-2+2+2+0+0+0+2-2%22+/%3E%3Cpath+d=%22M10+4v16%22+/%3E%3Cpath+d=%22M12+4a2+2+0+0+0-2+2+2+2+0+0+0-2-2%22+/%3E%3Cpath+d=%22M2+13a2+2+0+0+0+2+2+2+2+0+0+0-2+2%22+/%3E%3Cpath+d=%22M2+15h8%22+/%3E%3Cpath+d=%22M2+7a2+2+0+0+0+2+2+2+2+0+0+0-2+2%22+/%3E%3Cpath+d=%22M2+9h8%22+/%3E%3Cpath+d=%22M22+12H10%22+/%3E%3Cpath+d=%22M22+14a2+2+0+0+0-2-2+2+2+0+0+0+2-2%22+/%3E%3Cpath+d=%22M8+20a2+2+0+0+0+2-2+2+2+0+0+0+2+2%22+/%3E%3Crect+x=%222%22+y=%224%22+width=%2220%22+height=%2216%22+rx=%222%22+/%3E">icons<br/>Open lucide studio</a>

In this case, wouldn't it then make more sense to use solid shapes inbetween the internal rounded edges so they always stay gap-less or am I overall on the wrong track with this the design?

**Comment by jguddas** [comment]
> Do you mean the rounded internal edges

Yes, looking good until .75 stoke width is just not good enough.

We have that rule, so it looks good no matter how narrow the stroke is.
The max we support is 3px, but a min is not set, this is mostly there, so people can scale the icon to however ginormous sizes they want.

**Comment by AndreasSas** [comment]
> > Do you mean the rounded internal edges
> 
> Yes, looking good until .75 stoke width is just not good enough.
> 
> We have that rule, so it looks good no matter how narrow the stroke is. The max we support is 3px, but a min is not set, this is mostly there, so people can scale the icon to however ginormous sizes they want.

Thanks for correcting me.
I think I've now made a better approach to these trays:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?dialog=false&name=aaa&value=%3Cpath+d=%22M10+12h10a2+2+0+0+1+2+2v4a2+2+0+0+1-2+2h-8a2+2+0+0+1-2-2V6a2+2+0+0+0-2-2H4a2+2+0+0+0-2+2v1a2+2+0+0+0+2+2h6%22+/%3E%3Cpath+d=%22M10+18a2+2+0+0+1-2+2H4a2+2+0+0+1-2-2v-1a2+2+0+0+1+2-2h6%22+/%3E%3Cpath+d=%22M20+12a2+2+0+0+0+2-2V6a2+2+0+0+0-2-2h-8a2+2+0+0+0-2+2%22+/%3E%3Cpath+d=%22M4+9a2+2+0+0+0-2+2v2a2+2+0+0+0+2+2%22+/%3E">icons<br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?dialog=false&name=aaa&value=%3Cpath+d=%22M12+10v8a2+2+0+0+0+2+2h6a2+2+0+0+0+2-2v-6a2+2+0+0+0-2-2%22+/%3E%3Cpath+d=%22M15+10V6a2+2+0+0+1+2-2h3a2+2+0+0+1+2+2v2a2+2+0+0+1-2+2H4a2+2+0+0+0-2+2v6a2+2+0+0+0+2+2h6a2+2+0+0+0+2-2%22+/%3E%3Cpath+d=%22M15+6a2+2+0+0+0-2-2h-2a2+2+0+0+0-2+2%22+/%3E%3Cpath+d=%22M4+10a2+2+0+0+1-2-2V6a2+2+0+0+1+2-2h3a2+2+0+0+1+2+2v4%22+/%3E">icons<br/>Open lucide studio</a>

**Comment by ericfennis** [comment]
"Representing meal trays" is not a correct use case. Since it isn't describe the direct use-case of the icon. For representing GUI we already have the "layout" icons.
This one can be added to [Lucide lab](https://github.com/lucide-icons/lucide-lab). We also have `meal-box` icon there.

**Pull request closed without merging**
