### PR TITLE
Add tent icon

### PR DESCRIPTION
**Pull request by MoltenCoffee**
name | about | labels
-- | -- | --
New icon | Add a new icon to the library | 🎨 <icon

- **Name of the icon** : Campsite
- **Tags (alternative names for this icon)** (add them in tags.json) :  tent
- **What is the purpose of this icon?** : Depicting holidays or outdoor activities. Can be used in maps as well.
- **100% scale preview** : campsite
- **Have you considered alternative possibilities** for its naming or design? : It's roughly based on [#61 at feather](https://github.com/feathericons/feather/issues/61), but I feel this one is slightly more recognizable as a tent.

### CODE REVIEW

**Comment by ericfennis** [comment]
@MoltenCoffee Nice icon, thanks for the contribution!

Can you split up the path in separate shapes?
Because some design programs don't like combined/merged paths. 

If you need any help with that let me know!

**Comment by MoltenCoffee** [comment]
Sure, of course! Which parts would need to be separate paths? I quickly 'colored' the icon below for reference, I hope you're able to see it.

Untitled

I'd assume it would have to be split in the following paths:

- red (ground)
- both greens (outside of the tent)
- blue and brown (the entrance)
- pink and yellow (the rods at the top) (these are at a slightly different angle compared to the tent itself)

**Comment by MoltenCoffee** [comment]
Also, I named it "campsite" as that is how it is listed in #116, but I think "tent" with "campsite" as an alias is probably better. Do you agree?

**Comment by ericfennis** [comment]
@MoltenCoffee Yeah `tent` is perfect. We prefer naming as is what it shows than what it means. Because icon can multiple meanings.

For the splitting paths, I think we can split it up in 4 paths.

1. red
2. Brown
3. Green#1 with extended line to pink
4. Green #2 with extended line to yellow

I think the change of the paths that have a different angle (pink and yellow) is not visible when seeing this icon on 100%.

**Comment by MoltenCoffee** [comment]
I've replaced all paths, and like you said the difference in angles are negligible when viewed around 24px and way beyond. I've also renamed it to 'tent'.

**Comment by mittalyashu** [comment]
@ericfennis Once you merge this PR, can you update icon status in this issue as well https://github.com/lucide-icons/lucide/issues/119

**Comment by ericfennis** [comment]
@mittalyashu Will do!

**Pull request merged**
