### PR TITLE
feat: add 'a' plus/minus icons

### PR DESCRIPTION
**Pull request by mittalyashu**
Can be used for increase/decreasing font size.

| Preview |
| --- |
| CleanShot 2022-03-28 at 19 33 50@2x |

### CODE REVIEW

**Comment by delnyn** [comment]
it looks kinda weird to me...  
also in which use case would this be useful?

**Comment by mittalyashu** [comment]
> In which use case would this be useful?

If we want to add a button for increase or decreasing the font size.

**Comment by delnyn** [comment]
Oh okay  
your opinion on this @ericfennis ?

**Comment by mittalyashu** [comment]
I was thinking to make the "A" alphabet more smaller but we also haven’t setup any guidelines on english alphabets either.

**Comment by ericfennis** [comment]
I think the plus and the minus look to close to the A. Maybe move the A a little bit to the left, creates more room for the minus and the plus

**Comment by mittalyashu** [comment]
> I think the plus and the minus look to close to the A. Maybe move the A a little bit to the left, creates more room for the minus and the plus

@ericfennis I also agree, but then, the "A" alphabet would not be vertically centred. The only I can think of is to shrink the size bit more.

**Comment by ericfennis** [comment]
I think the icon should be vertically centered but horizontally it is not really that problem. See for example the `user-plus` icon.

**Comment by delnyn** [comment]
maybe you should narrow the A

**Comment by SnoutBug** [comment]
I personally think that an arrow would be more fitting because you increase the font size rather than adding or subtracting a font size.

In my head plus or minus is for deleting or adding

Take a look at open office writer or microsoft word

**Comment by ericfennis** [comment]
@mittalyashu Any updates on this?

**Comment by mittalyashu** [comment]
Adding space between `A` and `+`/`-`.

| |
| --- |
| CleanShot 2022-05-15 at 12 59 13@2x  |

This is, adding space + shrink `A` alphabet.

| |
| --- |
| CleanShot 2022-05-15 at 12 59 43@2x |

**Comment by ericfennis** [comment]
@mittalyashu Nice work, I think it is better to have the A on the same position in both icons.
I think I like the first one the most.

**Comment by ericfennis** [comment]
any progress on this @mittalyashu ?

**Comment by ericfennis** [comment]
Closing this due to inactivity

**Pull request closed without merging**
