### PR TITLE
feat: added edit page

### PR DESCRIPTION
**Pull request by jguddas**
You can click on the preview image to open the new edit page

<a title="Edit icons/cherry.svg" href="https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit/jguddas/github-icon-worflow-test/cherry/test-14?PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMiAxN2E1IDUgMCAwIDAgMTAgMGMwLTIuNzYtMi41LTUtNS0zLTIuNS0yLTUgLjI0LTUgM1oiIC8+CiAgPHBhdGggZD0iTTEyIDE3YTUgNSAwIDAgMCAxMCAwYzAtMi43Ni0yLjUtNS01LTMtMi41LTItNSAuMjQtNSAzWiIgLz4KICA8cGF0aCBkPSJNNyAxNGMzLjIyLTIuOTEgNC4yOS04Ljc1IDUtMTIgMS42NiAyLjM4IDQuOTQgOSA1IDEyIiAvPgogIDxwYXRoIGQ9Ik0yMiA5Yy00LjI5IDAtNy4xNC0yLjMzLTEwLTcgNS43MSAwIDEwIDQuNjcgMTAgN1oiIC8+Cjwvc3ZnPgo="> <a title="Edit icons/file-archive.svg" href="https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit/jguddas/github-icon-worflow-test/file-archive/test-14?PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNNCAyMlY0YzAtLjUuMi0xIC42LTEuNEM1IDIuMiA1LjUgMiA2IDJoOC41TDIwIDcuNVYyMGMwIC41LS4yIDEtLjYgMS40LS40LjQtLjkuNi0xLjQuNmgtMiIgLz4KICA8cG9seWxpbmUgcG9pbnRzPSIxNCAyIDE0IDggMjAgOCIgLz4KICA8Y2lyY2xlIGN4PSIxMCIgY3k9IjIwIiByPSIyIiAvPgogIDxwYXRoIGQ9Ik0xMCA3VjYiIC8+CiAgPHBhdGggZD0iTTEwIDEydi0xIiAvPgogIDxwYXRoIGQ9Ik0xMCAxOHYtMiIgLz4KPC9zdmc+Cg==">

TODOs:
- [ ] get redo and undo to work
- [ ] disconnect creates zero width elements for useless close tags

### CODE REVIEW

**Comment by jguddas** [comment]
Hey @ericfennis can you have a look at the logs and tell me where it is crashing?

**Comment by karsa-mistmere** [comment]
Wow, that's pretty neat!

I have a few ideas for improvement and a few questions:
1. it would be neat if on hover we could see which paths were which e.g. if I hover a path, the others faded out to low opacity, so that I could see if a point was part of one path or another (I guess this could work with the preview files as well?), as an added bonus it would be super cool if this also worked when hovering parts of the code (for those of us who are color blind).
1. Not entirely sure about the differences between format and optimize, format seems to remove some end of tag spaces that are currently part of our syntax (for whatever reason, don't ask my why 😄 )
1. Currently any syntax errors are thrown to the console, I think I could be neat if these were instead displayed on the edit page somewhere.
1. The repository/branch name should link to that branch on GitHub.
1. Not sure what the intended role of the disconnect button is. It's a neat trick, but do we really want to split up every path? What's the underlying purpose? :D
1. If I hit disconnect then optimize it, it results in some pretty funky code:
image
1. The preview doesn't seem to handle the `chakra-ui-dark` CSS class correctly, when my system preference is dark mode and the light mode is selected, the grid is not visible (see  above). (I think the edit page should set the darkMode value [based on `useColorMode`](https://chakra-ui.com/docs/styled-system/color-mode))

**Comment by jguddas** [comment]
The point of disconnect is, so you can edit path segments without affecting eachothers

1. To fix `building-2` I removed all the corners.

https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit/lucide-icons/lucide/building-2?PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTggOWgyYTIgMiAwIDAgMSAyIDJ2OWEyIDIgMCAwIDEtMiAySDRhMiAyIDAgMCAxLTItMnYtNmEyIDIgMCAwIDEgMi0yaDIiLz4KICA8cGF0aCBkPSJNMTAgNmg0Ii8+CiAgPHBhdGggZD0iTTEwIDEwaDQiLz4KICA8cGF0aCBkPSJNMTAgMTRoNCIvPgogIDxwYXRoIGQ9Ik0xMCAxOGg0Ii8+CiAgPHBhdGggZD0iTTYgMjJWNGEyIDIgMCAwIDEgMi0yaDhhMiAyIDAgMCAxIDIgMnYxOCIvPgo8L3N2Zz4=

2. And then created new corner arc elements by hand and merged everything back to gather.

https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit/lucide-icons/lucide/building-2?PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTggOWgyYTIgMiAwIDAgMSAyIDJ2OWEyIDIgMCAwIDEtMiAySDRhMiAyIDAgMCAxLTItMnYtNmEyIDIgMCAwIDEgMi0yaDIiLz4KICA8cGF0aCBkPSJNMTAgNmg0Ii8+CiAgPHBhdGggZD0iTTEwIDEwaDQiLz4KICA8cGF0aCBkPSJNMTAgMTRoNCIvPgogIDxwYXRoIGQ9Ik0xMCAxOGg0Ii8+CiAgPHBhdGggZD0iTTYgMjJWNGEyIDIgMCAwIDEgMi0yaDhhMiAyIDAgMCAxIDIgMnYxOCIvPgo8L3N2Zz4=

**Comment by jguddas** [comment]
Another good one to test things out:

https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit/lucide-icons/lucide/book-copy?PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMiwxNlY0YzAtMS4xLDAuOS0yLDItMmgxMSIgLz4KICA8cGF0aCBkPSJNNSwxNEg0Yy0xLjEsMC0yLDAuOS0yLDJzMC45LDIsMiwyaDEiIC8+CiAgPHBhdGggZD0iTTIyLDE4SDExYy0xLjEsMC0yLDAuOS0yLDJsMCwwIiAvPgogIDxwYXRoIGQ9Ik0xMSw2aDExdjE2SDExYy0xLjEsMC0yLTAuOS0yLTJWOEM5LDYuOSw5LjksNiwxMSw2eiIgLz4KPC9zdmc+Cg==

**Comment by ericfennis** [comment]
@jguddas Maybe it's an idea to create a new separate repo for Lucide Studio?
Move the site code there and close this one.

**Comment by jguddas** [comment]
> @jguddas Maybe it's an idea to create a new separate repo for Lucide Studio? Move the site code there and close this one.

https://github.com/jguddas/lucide-studio

**Pull request closed without merging**
