### PR TITLE
feat: optimized accessibility icons

### PR DESCRIPTION
**Pull request by jguddas**

### CODE REVIEW

**Comment by jguddas** [comment]
@karsa-mistmere @ericfennis is a change like we see in the thumb of the hand icon acceptable?

**Comment by ericfennis** [comment]
@jguddas No, now it creates a blurry line. See 100% view.

**Comment by jguddas** [comment]
> No, now it creates a blurry line. See 100% view.

@ericfennis which icon is a problem?

**Review by ericfennis — DISMISSED** [review]

**Review by karsa-mistmere — CHANGES_REQUESTED** [review]

**Comment by karsa-mistmere** [comment]
@jguddas Why did you close this one? 🤔

**Comment by jguddas** [comment]
Gotta have to split it up and make it one PR per icon.

**Pull request closed without merging**
