### PR TITLE
Make lucid-angular compatible with angular 14

### PR DESCRIPTION
**Pull request by ekowbaah**

### CODE REVIEW

**Review by ericfennis — COMMENTED** [review]
@ekowbaah Nice work, are you sure this is still working for older versions of angular as well?

**Comment by ekowbaah** [comment]
> @ekowbaah Nice work, are you sure this is still working for older versions of angular as well?

@ericfennis I will do some manual testing with previous versions and let you know.

**Comment by ekowbaah** [comment]
@ericfennis tested against previous versions >= angular11 and works fine

**Comment by ericfennis** [comment]
Awesome!

**Comment by ekowbaah** [comment]
Hi @ericfennis, realized the lucid angular build was failing due to the tests not running. Are you working on that? Seems its due to an outdated chromium version

**Comment by ericfennis** [comment]
Yeah noticed it. Will check

**Comment by ekowbaah** [comment]
Hello @ericfennis , I was wondering if you got the chance to check why the angular build was failing.

**Pull request merged**
