### PR TITLE
Add `radiation`/`biohazard` icons

### PR DESCRIPTION
**Pull request by danielbayley**
Alternatives:
Untitled

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
How about something like the 2nd row but with no rounding?
image

While in general, rounding fits the Lucide aesthetic more, I think in this instance it causes the well established shape to lose character.

**Comment by jguddas** [comment]
I don't like the sharp corners and the big circle that doesn't have a 2px whole in it in the center.

**Comment by jguddas** [comment]
I think this one is the best, but maybe a bit smaller with a less pronounced radius? image

**Comment by karsa-mistmere** [comment]
> I think this one is the best, but maybe a bit smaller with a less pronounced radius? image

That's not bad, but yeah, maybe let's try a somewhat smaller corner radius.

**Comment by danielbayley** [comment]
> larger gap between the segments and the central dot.

Yeah that was a rules violation. What do we think between these…?

Untitled

Untitled

**Comment by jguddas** [comment]
I prefer the right one.

**Comment by danielbayley** [comment]
> I prefer the right one.

Same…

**Comment by karsa-mistmere** [comment]
I would love to also have a matching biohazard icon, but this is just not compliant, I'm afraid. 😅 
biohazard

**Comment by jguddas** [comment]
Looks nice and compliant to me. icon (27)

**Pull request merged**
