### PR TITLE
feat: add `scan`, `scan-line` icons

### PR DESCRIPTION
**Pull request by wojtekmaj**
`scan`
scan svg

`scan-line`
scan-line svg

### CODE REVIEW

**Comment by ericfennis** [comment]
Can you maybe make a variant using the square icon as the base?

**Comment by wojtekmaj** [comment]
Absolutely @ericfennis! Makes total sense to me, I don't know why I didn't do that before.

Updated PR & previews.

**Review by ericfennis — APPROVED** [review]
Awesome I like it!

**Comment by locness3** [comment]
how is this `scan` different from `maximize`?

**Comment by ericfennis** [comment]
@locness3 Good you notice this. The icons look really similar. Maybe 1 pixel difference

**Pull request merged**
