### PR TITLE
forklift svg

### PR DESCRIPTION
**Pull request by willythewizard**
forklift (2)

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
Hey @willythewizard,

Could you clean up your repo and merge origin main from ours?
There are 1960 file changes for this request, so I think there's definitely something wrong here. :)

We also need some use cases before this can be merged.

**Comment by ericfennis** [comment]
@willythewizard I think you selected the wrong branch. You forgot first to fork the lucide repo and make your change.

**Review by ericfennis — CHANGES_REQUESTED** [review]
Can you fix the target branch?

**Comment by ericfennis** [comment]
I close this due to inactivity.
You need to switch the target branch to the correct branch, you switched them around. (You've selected the `main` as the source branch) So Please select the correct branch. If you need any help with that let us know, we're happy to help!

**Pull request closed without merging**
