### PR TITLE
Add VR/AR icons

### PR DESCRIPTION
**Pull request by danielbayley**
`focus-box` also doubles as `symbol-variable` from VS Code/[codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html).

### CODE REVIEW

**Comment by ericfennis** [comment]
I agree with @karsa-mistmere on this one. Without knowing the context it is hard to see what icon is trying to tell.

**Comment by danielbayley** [comment]
They look obvious enough to me, especially the controller! But then maybe I am heavily biased, as a long time Oculus Quest user… I have some variations I’ll post…

**Comment by xnousnow** [comment]
What about making vr headset design like Apple Vision pro?

**Comment by karsa-mistmere** [comment]
> Example icons at #1421 would be better to understand more.

I think those icons all look very much like scuba diving masks, personally, VR would never come to mind.

**Comment by ericfennis** [comment]
I agree with @karsa-mistmere and @xnousnow. These need some refinement.
Please continue in thread #1421 for feedback on designs.

**Pull request closed without merging**
