### PR TITLE
FIX: 404 when installing dependencies using APT

### PR DESCRIPTION
**Pull request by yanquisalexander**
I added a step that updates APT repositories before installing dependencies

### CODE REVIEW

**Review by ericfennis — APPROVED** [review]

**Comment by ericfennis** [comment]
Nice, I have btw a fix for #80, the icons look way better now with the path to outline fix.

**Comment by yanquisalexander** [comment]
> Nice, I have btw a fix for #80, the icons look way better now with the path to outline fix.

Is the solution already implemented or is it a possible solution?

I found this: https://github.com/elrumordelaluz/outline-stroke-cli

Convert multiple SVG files at once

I will try it

**Comment by ericfennis** [comment]
Yeah I already builded it, can make an PR for it.
But I wasn't able to test is yet, not sure if the Action will work, but we can give it a try.

yeah that package is from the same gut that made the outline-stroke package, I used that one. the icons where looking great!

**Comment by yanquisalexander** [comment]
> Yeah I already builded it, can make an PR for it.
> But I wasn't able to test is yet, not sure if the Action will work, but we can give it a try.
> 
> yeah that package is from the same gut that made the outline-stroke package, I used that one. the icons where looking great!

I just tried the CLI, maybe I was wrong about something, but look how the icons look:

Captura de pantalla (145)


Workflow file: https://github.com/yanquisalexander/lucide/blob/master/.github/workflows/font.yml

**Comment by yanquisalexander** [comment]
https://github.com/elrumordelaluz/outline-stroke-cli/issues/3

**Comment by ericfennis** [comment]
yeah those issues I tackled as wel, Is used exactly the solution in the issue you mentioned.
I pushed it to a separated branch: [](https://github.com/lucide-icons/lucide/tree/feature/ttf-fix)
Feel free to continue on this and check if everything is working, maybe you will find some improvements

**Comment by yanquisalexander** [comment]
It's funny that I did a PR to master 20 minutes ago :joy:

**Comment by ericfennis** [comment]
Oh noo, i see 😂😂

**Pull request merged**
