### PR TITLE
Renamed user-*-2 to user-round-*

### PR DESCRIPTION
**Pull request by jmsv**
## What is the purpose of this pull request?

- [ ] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other:

Rename icons

### Description

Renamed all `user-*-2` icons to `user-round-*` as-discussed in #1620, using script from #1630:

```sh
node ./scripts/renameIcon.mjs user-2 user-round
node ./scripts/renameIcon.mjs user-check-2 user-round-check
node ./scripts/renameIcon.mjs user-circle-2 user-round-circle
node ./scripts/renameIcon.mjs user-cog-2 user-round-cog
node ./scripts/renameIcon.mjs user-minus-2 user-round-minus
node ./scripts/renameIcon.mjs user-plus-2 user-round-plus
node ./scripts/renameIcon.mjs user-search-2 user-round-search
node ./scripts/renameIcon.mjs user-square-2 user-round-square
node ./scripts/renameIcon.mjs user-x-2 user-round-x
node ./scripts/renameIcon.mjs users-2 users-round
```

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Review by jguddas — APPROVED** [review]
LGTM

**Comment by jguddas** [comment]
One question, how do we decide if it should be `user-square` or `square-user`?

**Comment by jmsv** [comment]
> One question, how do we decide if it should be `user-square` or `square-user`?

I reckon `user-square` makes more sense since the user is the main subject. There's also `user-circle` in a similar format.

**Comment by jmsv** [comment]
Vercel build failed but I can't see why 🤔

**Comment by jguddas** [comment]
> Vercel build failed but I can't see why 🤔

Probably permission issue.

**Comment by jguddas** [comment]
> > One question, how do we decide if it should be `user-square` or `square-user`?
> 
> I reckon `user-square` makes more sense since the user is the main subject. There's also `user-circle` in a similar format.

Good point, pretty important part of the naming convention IMO.

Otherwise, people might name them by most common elements, and for `user-square` that would be `square` and not `user` since it uses the same square as `square` but not the same user as `user`.

**Comment by jmsv** [comment]
> > > One question, how do we decide if it should be `user-square` or `square-user`?
> > 
> > 
> > I reckon `user-square` makes more sense since the user is the main subject. There's also `user-circle` in a similar format.
> 
> Good point, pretty important part of the naming convention IMO.
> 
> Otherwise, people might name them by most common elements, and for `user-square` that would be `square` and not `user` since it uses the same square as `square` but not the same user as `user`.

Reckon this is something that should be included in the [Naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions) docs then? Happy to PR if so. Something like:

```md
7. Names should start with the subject of the icon rather than any variant description.\
   For example: `user-square` instead of `square-user`
```

**Comment by jmsv** [comment]
> > Vercel build failed but I can't see why 🤔
> 
> Probably permission issue.

Looks like it yes – I get a 404. Do you have access to see what failed?

**Comment by jmsv** [comment]
Hmm, merged `main` and the new "Fail if contributors have changed" check is failing @jguddas

**Comment by jguddas** [comment]
> Hmm, merged main and the new "Fail if contributors have changed" check is failing @jguddas

Good catch, https://github.com/lucide-icons/lucide/pull/1643 is the fix.

**Review by jguddas — APPROVED** [review]
LGTM

**Comment by karsa-mistmere** [comment]
Nice work, @jmsv!

I'm piggybacking this PR to give the `user-round` icons a bit of a visual overhaul and some much needed optimization, as already discussed with @ericfennis and @jguddas on Discord. Our current icons were just far too small in comparison to other icons, the new layout allows for much better visual weight and better consistency within this set of icons.

I've also renamed `user-*-square` and `user-*-circle` to `square-user-*` and `circle-user-*` respectively, as these names are much less confusing and more semantically correct. In the future, we'll probably also add this naming scheme to our guidelines.

**Comment by jmsv** [comment]
> Nice work, @jmsv!
> 
> I'm piggybacking this PR to give the `user-round` icons a bit of a visual overhaul and some much needed optimization, as already discussed with @ericfennis and @jguddas on Discord. Our current icons were just far too small in comparison to other icons, the new layout allows for much better visual weight and better consistency within this set of icons.
> 
> I've also renamed `user-*-square` and `user-*-circle` to `square-user-*` and `circle-user-*` respectively, as these names are much less confusing and more semantically correct. In the future, we'll probably also add this naming scheme to our guidelines.

Thanks @karsa-mistmere!

Ah okay cool, I thought we were going the the opposite (`user-shape` over `shape-user`) but I don't mind either way 😃 

> on Discord

Joined, can't find the discussion though – do you have a link/possible to tag me please?

**Comment by karsa-mistmere** [comment]
> Joined, can't find the discussion though – do you have a link/possible to tag me please?

Oh, it was a private conversation in our maintainers' chat, sorry I wasn't clearer about this. 😅 

> Ah okay cool, I thought we were going the the opposite (`user-shape` over `shape-user`) but I don't mind either way 😃

We weren't quite sure either, and we do currently have a mix of both name formats, we're leaning more towards `<shape>-<content>` because in most scenarios the resulting names will end up a bit less confusing and more logically extensible:
* some feel a bit funny, `user-round-square` ("What even is a round square?") and `user-round-circle` ("Aren't all circles round?") 
* should we ever have `square-user-round-plus` icon, this name would be a much more trivial extension of `square-user-round` than either `user-round-plus-square` or `user-round-square-plus` would be of `user-round-square`.

**Review by karsa-mistmere — APPROVED** [review]

**Comment by jmsv** [comment]
> Oh, it was a private conversation in our maintainers' chat, sorry I wasn't clearer about this. 😅

Ah ok! No problem

> We weren't quite sure either, and we do currently have a mix of both name formats, we're leaning more towards `<shape>-<content>` because in most scenarios the resulting names will end up a bit less confusing and more logically extensible:
> 
> * some feel a bit funny, `user-round-square` ("What even is a round square?") and `user-round-circle` ("Aren't all circles round?")
> * should we ever have `square-user-round-plus` icon, this name would be a much more trivial extension of `square-user-round` than either `user-round-plus-square` or `user-round-square-plus` would be of `user-round-square`.

Makes sense :+1:

The updated `user-round` style looks great btw! 👌

Thanks for updating #1620 to match too

**Review by ericfennis — APPROVED** [review]
Great work @jmsv !!

**Comment by jmsv** [comment]
> Great work @jmsv !!

Thanks for the merge! 🚀

I also have #1620 open, was waiting for this one to get merged first with the new `user-round-*` naming

**Pull request merged**
