### PR TITLE
Site: Add Logo

### PR DESCRIPTION
**Pull request by ericfennis**

### CODE REVIEW

**Comment by locness3** [comment]
The deploy preview fails...

**Comment by ericfennis** [comment]
hmm strange, the dev built worked but the deploy built not. I will take a look

**Review by locness3 — APPROVED** [review]

**Comment by locness3** [comment]
Maybe th favicon could have a background?

**Comment by ericfennis** [comment]
hmm, I kinda like this one. otherwise I think the spiral is not recognisable.
image

**Comment by locness3** [comment]
I meant a *background* so that it is visible correctly both on dark and light backgrounds.

**Pull request merged**
