### PR TITLE
Add `empty-truck` icon

### PR DESCRIPTION
**Pull request by LienMaas**
## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

This PR adds an empty truck icon

image

### Icon use case 

It can be used to distinguish trucks without loads.

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons:  truck
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by ericfennis** [comment]
Can you describe a real-life usecase for this icon? For what kind of this icon is useful?

**Comment by jguddas** [comment]
I don't think it looks all that intuitively like an empty truck.

And it should be `truck-empty`, group name comes first.

**Comment by LienMaas** [comment]
It is supposed to represent an empty container truck, such like this one 
flatbed-truck-isolated-side-view-260nw-1576250104

In the code it is named truck-empty if im correct

**Comment by ericfennis** [comment]
Need to have a real-life usecase. Please provide one.
I close this one for now, if you have one we can re-open it.

**Pull request closed without merging**
