### PR TITLE
add mobile power button

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-05-15 at 09 46 07@2x |

### CODE REVIEW

**Comment by locness3** [comment]
Hmm

**Comment by mittalyashu** [comment]
Something wrong with the icon?

**Comment by locness3** [comment]
I'll be the PR template :
- **What is the purpose of this icon?** : e.g. Shows that one can click it to... / Is used to denote or label...
- **Have you considered alternative possibilities** for its naming or design?

**Comment by ericfennis** [comment]
I think this one is too specific and abstract.

**Comment by mittalyashu** [comment]
My idea for designing this icon was creating a mobile power button.

iPhone power button, for instance.

**Comment by locness3** [comment]
I understood that, but in what context should it be used?

**Comment by mittalyashu** [comment]
IDK, if there will be any copyright issue from Apple

image

**Comment by locness3** [comment]
Oh, makes more sense now. But I think this is a very specific use-case and it would not benefit the icon set as a whole.

**Comment by mittalyashu** [comment]
You never know when and where people might use the icons.

**Comment by locness3** [comment]
They can use another icon set as well.

**Comment by mittalyashu** [comment]
Hmm... okay.

**Pull request closed without merging**
