### PR TITLE
Lucide Vue Package

### PR DESCRIPTION
**Pull request by ericfennis**
The lucide vue npm package.

Alpha pre-release on: `0.12.0-alpha.5`.
Feedback is welcome!

Docs here below:

# Lucide Vue

Use the lucide icon library in you Vue app.

## Installation

```sh
yarn add lucide-vue

# or

npm install lucide-vue
```

## How to use

It's build with ESmodules so it's completely threeshakable.
Each icon can be imported as a vue component.

### Example

You can pass additional props to adjust the icon.

``` vue
<template>
  <Camera
    color="red"
    :size="32"
  />
</template>

<script>
// Returns Vue component
import { Camera } from 'lucide-vue';

export default {
  name: "My Component",
  components: { Camera }
}

</script>
```

### Props

|  name        |   type   |  default
| ------------ | -------- | --------
| `size`       | *Number* | 24
| `color`      | *String* | currentColor
| `strokeWidth`| *Number* | 2

### Custom props

You can also pass custom props that will be added in the svg as attributes.

``` vue
<template>
  <Camera fill="red" />
</template>
```

### One generic icon component

It is possible to create one generic icon component to load icons.

> :warning: Example below importing all EsModules, caution  using this example, not recommended when you using bundlers, your application build size will grow strongly.

#### Icon Component Example
...

WIP

### CODE REVIEW

**Comment by mittalyashu** [comment]
@ericfennis I was trying using the vue package, it doesn't add `class` attribute to icon

_(forget about the second alert, see the first one)_

CleanShot 2021-01-27 at 10 55 35@2x

```html
<success-icon
	v-if="type === 'success'"
	class="alert-icon alert-icon-success"
/>
```

**Comment by ericfennis** [comment]
@mittalyashu Thanks for testing this, I will add this test case to tests. To be clear, you using Vue 2 right?

**Comment by mittalyashu** [comment]
> To be clear, you using Vue 2 right?

@ericfennis yes

**Comment by mittalyashu** [comment]
@ericfennis I mean, we can be discussed if we should add support for custom class and style attribute or not _(you don't have to take my word)_.

**Comment by ericfennis** [comment]
@mittalyashu Intentionally I wanted to support that, like we do with the react package. I consider this as a bug.

**Comment by mittalyashu** [comment]
okay

**Comment by mittalyashu** [comment]
Any ETA when non alpha/beta version will be released? @ericfennis

**Comment by ericfennis** [comment]
I hope Soon, I'm working on it right now. But have some problems with inheriting styling and classes.

**Comment by ericfennis** [comment]
@mittalyashu Just released `0.12.0-alpha.5` style and class attributes seems to work now.

**Comment by mittalyashu** [comment]
Yup, seems to be working fine.

CleanShot 2021-01-28 at 10 46 29@2x

**Pull request merged**
