### PR TITLE
Add Solid package 

### LINKED ISSUE #637: Add support for solidjs
How about it? I can help you.

### PR DESCRIPTION
**Pull request by ericfennis**
Closes #637 #792

### CODE REVIEW

**Comment by ericfennis** [comment]
Hmm I just found out that 'lucide-solid' is already used on [npm](https://www.npmjs.com/package/lucide-solid) 🤔 by @ImedAdel .

@ImedAdel Are you ok if we use the 'lucide-solid' name on npm?
Otherwise we think of other name.

**Comment by ImedAdel** [comment]
Ah yeah, no problem, I'm not maintaining the package. How do I transfer a name? :)

**Comment by ericfennis** [comment]
@ImedAdel Thanks that will be nice!

I think you can follow this guide: https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

My username on npm is: `ericfennis`

**Comment by ImedAdel** [comment]
I just sent an invitation! Make sure to remove me as a maintainer once you accept it :)

**Comment by ericfennis** [comment]
Thank you, accepted it!

**Pull request merged**
