### PR TITLE
Add (flex) align icons

### PR DESCRIPTION
**Pull request by ericfennis**
image

contributes to: #399

### CODE REVIEW

**Comment by mittalyashu** [comment]
@ericfennis can you increase 1px of the smaller box?

CleanShot 2022-01-11 at 13 51 14@2x

CleanShot 2022-01-11 at 13 51 10@2x

**Comment by ericfennis** [comment]
@mittalyashu While designing this I also looked between this variants. To me on 100% the difference between the large and the small  box looked to small
image
100%
image

**Comment by locness3** [comment]
I suggest these icons have "box" somewhere in the name.

**Comment by ericfennis** [comment]
@locness3 hmm I don't know the names will be too long I think.
`align-box-start-vertical` 🤔

**Comment by mittalyashu** [comment]
> I suggest these icons have "box" somewhere in the name.

Why "box" in the name?

**Pull request merged**
