### PR TITLE
Optimise/rename `vote`/add `tab`[`-*`]/generic output icons

### PR DESCRIPTION
**Pull request by danielbayley**
Also covers `output` from [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html).

Untitled
<br/>
Artboard 1@2x
<br/>
<br/>

Possibly closes #1172…?

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
Not convinced about the names, I also wanted to submit a similar PR, in which I was planning to use the names `ballot`, `ballot-check`, `ballot-x`, by extension the extra icon in this PR would be `ballot-text`, I guess.

I'm open to other ideas, as long as the new names are more consistent.

**Comment by jguddas** [comment]
Feels a bit like a browser-tab, probably due to not having a box the ballot is getting put in.

**Comment by danielbayley** [comment]
> Not convinced about the names, I also wanted to submit a similar PR, in which I was planning to use the names `ballot`, `ballot-check`, `ballot-x`, by extension the extra icon in this PR would be `ballot-text`, I guess.

@karsa-mistmere Works for me…

> Feels a bit like a browser-tab

That’s what #1172 is for…

**Comment by karsa-mistmere** [comment]
> > Feels a bit like a browser-tab
> 
> That’s what #1172 is for…

I do kind of agree with @jguddas on this, it does look conspicuously tab-like.

I did have a few alternate designs lying around in my drafts, but was OK with the one that got merged because mine all had some setbacks.
image

**Comment by danielbayley** [comment]
> I do kind of agree with @jguddas on this, it does look conspicuously tab-like.

Hmm, but I do like the simplicity of these…

Maybe we could just have them all as a single set, with appropriate `tags` for both? (merge with #1172)

**Comment by karsa-mistmere** [comment]
`tab-text` also kinda looks like a tombstone. 😅

**Comment by danielbayley** [comment]
> `tab-text` also kinda looks like a tombstone. 😅

@karsa-mistmere I can add that to the metadata… :)

> What about making it bigger, #1192 ?

@jguddas See updated options: https://github.com/lucide-icons/lucide/pull/1237#issuecomment-1540182422

**Review by karsa-mistmere — APPROVED** [review]

**Comment by ericfennis** [comment]
@danielbayley Can you rebase the PR?
I'm not sure about the use case for the `tab-slash` icon. Can we clear this up?

**Comment by ericfennis** [comment]
This PR is merged to the lab branch. This PR does not match our [PR template](https://github.com/lucide-icons/lucide/blob/main/.github/pull_request_template.md), which requires valid use cases. To move on we merged this PR to the [lab branch](https://github.com/lucide-icons/lucide/tree/lab), which will be moved to a separate repo in the future.

**Pull request merged**
