### PR TITLE
add 2-fa icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-02-25 at 16 00 42@2x |

### CODE REVIEW

**Comment by locness3** [comment]
Thus can represent much more than 2fa. Tags needed!

**Comment by ericfennis** [comment]
@mittalyashu I agree with @locness3, this icon is to specific named for 2fa.
Maybe `form-input`?

**Comment by mittalyashu** [comment]
@ericfennis should I add tags in this PR itself?

I hope there will be no merge conflicts.

**Comment by locness3** [comment]
@mittalyashu Please make sure to rename PRs when renaming icons

**Pull request merged**
