### PR TITLE
feat(icons): add eye-closed icon

### PR DESCRIPTION
**Pull request by karsa-mistmere**
## What is the purpose of this pull request?

- [x] New Icon

### Description
Adds an icon depicting an eye that is closed (not crossed off).

### Icon use case 

1. **Privacy Mode**
   - Indicate that privacy mode is activated.

2. **Sleep Mode**
   - Represent a device or application in sleep mode.

3. **Do Not Disturb**
   - Show that notifications or alerts are muted.

4. **Hidden Content**
   - Mark content that is hidden or needs to be revealed.

5. **Inactive Status**
   - Denote that a user is inactive or away.

6. **Muted Video**
   - Indicate that a video feed is turned off.

7. **Stealth Mode**
   - Represent a feature that operates in stealth or hidden mode.

8. **Accessibility Feature**
   - Indicate an accessibility option for users with visual impairments.

9. **Mindfulness/Relaxation**
   - Represent a feature or content related to mindfulness or relaxation exercises.

10. **Vision Test**
    - Use in applications or contexts involving eye health or vision tests.

### Alternative icon designs 
image

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] The icons are solely my own creation.
- [x] I've "based" them on the following design: `eye` (not so much based, but designed in a way they would match)

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by ericfennis** [comment]
@karsa-mistmere Nice icon, I like it.
Looking at the X-ray, it is a bit shifted relative to the `eye` icon. When using this for example to show/hide something you see it feels like it shifting a bit.

Not sure if this is intended, I've create a quick [demo](https://codesandbox.io/p/devbox/m3r3jj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0qesp6700073b6jmqcb8zmu%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0qesp6600023b6jcwmwtrui%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0qesp6700043b6j8bqtjdfo%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0qesp6700063b6jay6yvsj1%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0qesp6600023b6jcwmwtrui%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0qesp6600013b6jhfwl6bzk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0qexes200023b6jfy1cjcza%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A38%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A38%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0qesp6600023b6jcwmwtrui%2522%252C%2522activeTabId%2522%253A%2522cm0qexes200023b6jfy1cjcza%2522%257D%252C%2522cm0qesp6700063b6jay6yvsj1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0qesp6700053b6jm5n2a22m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%255D%252C%2522id%2522%253A%2522cm0qesp6700063b6jay6yvsj1%2522%252C%2522activeTabId%2522%253A%2522cm0qesp6700053b6jm5n2a22m%2522%257D%252C%2522cm0qesp6700043b6j8bqtjdfo%2522%253A%257B%2522id%2522%253A%2522cm0qesp6700043b6j8bqtjdfo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0qesp6700033b6jcdlpy22d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cm0qesp6700033b6jcdlpy22d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to demonstrate this.

**Comment by karsa-mistmere** [comment]
> @karsa-mistmere Nice icon, I like it. Looking at the X-ray, it is a bit shifted relative to the `eye` icon. When using this for example to show/hide something you see it feels like it shifting a bit.
> 
> Not sure if this is intended, I've create a quick [demo](https://codesandbox.io/p/devbox/m3r3jj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0qesp6700073b6jmqcb8zmu%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0qesp6600023b6jcwmwtrui%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0qesp6700043b6j8bqtjdfo%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0qesp6700063b6jay6yvsj1%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0qesp6600023b6jcwmwtrui%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0qesp6600013b6jhfwl6bzk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0qexes200023b6jfy1cjcza%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A38%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A38%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0qesp6600023b6jcwmwtrui%2522%252C%2522activeTabId%2522%253A%2522cm0qexes200023b6jfy1cjcza%2522%257D%252C%2522cm0qesp6700063b6jay6yvsj1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0qesp6700053b6jm5n2a22m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%255D%252C%2522id%2522%253A%2522cm0qesp6700063b6jay6yvsj1%2522%252C%2522activeTabId%2522%253A%2522cm0qesp6700053b6jm5n2a22m%2522%257D%252C%2522cm0qesp6700043b6j8bqtjdfo%2522%253A%257B%2522id%2522%253A%2522cm0qesp6700043b6j8bqtjdfo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0qesp6700033b6jcdlpy22d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cm0qesp6700033b6jcdlpy22d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to demonstrate this.

The codesandbox isn't public.

**Comment by ericfennis** [comment]
Sorry about that forgot to make it public, [here ya go](https://codesandbox.io/p/devbox/m3r3jj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0qesp6700073b6jmqcb8zmu%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0qesp6600023b6jcwmwtrui%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0qesp6700043b6j8bqtjdfo%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0qesp6700063b6jay6yvsj1%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0qesp6600023b6jcwmwtrui%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0qesp6600013b6jhfwl6bzk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0qexes200023b6jfy1cjcza%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A38%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A38%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0qesp6600023b6jcwmwtrui%2522%252C%2522activeTabId%2522%253A%2522cm0qexes200023b6jfy1cjcza%2522%257D%252C%2522cm0qesp6700063b6jay6yvsj1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0qesp6700053b6jm5n2a22m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%255D%252C%2522id%2522%253A%2522cm0qesp6700063b6jay6yvsj1%2522%252C%2522activeTabId%2522%253A%2522cm0qesp6700053b6jm5n2a22m%2522%257D%252C%2522cm0qesp6700043b6j8bqtjdfo%2522%253A%257B%2522id%2522%253A%2522cm0qesp6700043b6j8bqtjdfo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0qesp6700033b6jcdlpy22d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cm0qesp6700033b6jcdlpy22d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by ericfennis** [comment]
@karsa-mistmere Agreed. And overlapping it exactly with `eye` icon makes the icon not vertically centered right? In that case I think the 1px shift downwards is the best we can do.

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
