### PR TITLE
Add/optimise `layout-*` alternate icons

### PR DESCRIPTION
**Pull request by danielbayley**
`layout-grid-2` is `layout` from [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html). These match existing https://lucide.dev/icons?search=layout- icons…

Also fixed `layout-template` to also use `rect`s, and rounded all the corners to 2px radius.

Semi-related to #1156 and #1003…

### CODE REVIEW

**Comment by jguddas** [comment]
IMO we should add a radius to all of them network (3) -> network (2)

**Comment by danielbayley** [comment]
> IMO we should add a radius to all the layout icons

Yeah already on it 😅

**Review by jguddas — APPROVED** [review]

**Comment by karsa-mistmere** [comment]
As with other similarly themed recent PRs, I'm very unsure about taking this direction.
`grid` looks pretty decent, but anything with smaller rectangles than that is much less legible than it currently is.

**Comment by karsa-mistmere** [comment]
As with #1188, we could maybe check things out with 0, 1px and 2px corners side by side.

**Comment by jguddas** [comment]
I like those a lot better, when scrolling through the icons this just felt out of place.

**Comment by danielbayley** [comment]
> As with #1188, we could maybe check things out with 0, 1px and 2px corners side by side.

Yep, and we should get #1180 merged as a priority, so we can automate more of this review process efficiently…

**Comment by ericfennis** [comment]
I think the 1px rounding looks way better for this

**Comment by jguddas** [comment]
What we should also check is if they feel consistent in combination with other icons, not just on their own.

**Comment by danielbayley** [comment]
> I think the 1px rounding looks way better for this

`push`ed…

**Review by ericfennis — APPROVED** [review]

**Comment by karsa-mistmere** [comment]
> What we should also check is if they feel consistent in combination with other icons, not just on their own.

Definitely! Here goes:

image

In my opinion:
* Row 1 (current): yeah, definitely not very consistent
* Row 2 (PR): Not _perfectly_ consistent, but definitely lightyears better than row 1.
* Row 3 (2px): Way too blobby.

---

@danielbayley: One final thing I'm not psyched about are the names.
I just don't find the names `layout-grid-2` and `layout-template-2` very fitting.

Maybe something like `layout-panel-left`, `layout-panel-top`? In either case, something that better describes the image at hand.

**Comment by jguddas** [comment]
> Row 3 (2px): Way too blobby.

We should try to not just look at Icons in isolation, I personally don't mind the blobbyness and am more concerned about cohesion.

**Comment by karsa-mistmere** [comment]
> We should try to not just look at Icons in isolation, I personally don't mind the blobbyness and am more concerned about cohesion.

I have done just that in the review apps, yes and I still find the 2px versions way too blobby. 🙂 
* **1px** https://lucide-cf2cmvhp2-lucide.vercel.app/
* **2px** https://lucide-r7j06odgz-lucide.vercel.app/

The 2px version isn't _that_ bad per se, it's just not my cup of tea.

**Comment by danielbayley** [comment]
> Maybe something like `layout-panel-left`, `layout-panel-top`? In either case, something that better describes the image at hand.

@karsa-mistmere Done.

**Review by karsa-mistmere — APPROVED** [review]

**Pull request merged**
