### PR TITLE
Adds `images` and (updates `file-image` to match)

### LINKED ISSUE #1851: Images icon
### Icon name

images

### Use cases

My use case: An icon for a menu  "Images" where user can manage multiple images

### Design ideas

Something like this: https://boxicons.com/?query=images

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

### PR DESCRIPTION
**Pull request by karsa-mistmere**
closes #1851 

## What is the purpose of this pull request?
- [x] New Icon

### Description
Adds an `images` icon in line with `files`, `folders`, etc.

### Icon use case 
- image collection/album
- copy an image

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [x] I've based them on the following Lucide icons: `image` & `files`, `folders`, `save-all`, `copy` etc.

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by jguddas** [comment]
I prefer something like this: icon (38)

**Comment by karsa-mistmere** [comment]
> I prefer something like this: icon (38)

That's not in line whatsoever with preexisting icons I based this on.

**Review by ericfennis — APPROVED** [review]

**Comment by jguddas** [comment]
> > I prefer something like this: icon (38)
> 
> That's not in line whatsoever with preexisting icons I based this on.

You want it to be consistent with some other icons?

What other icons is it based on?

**Comment by karsa-mistmere** [comment]
> > > I prefer something like this: icon (38)
> > 
> > 
> > That's not in line whatsoever with preexisting icons I based this on.
> 
> You want it to be consistent with some other icons?
> 
> What other icons is it based on?

See our nicely filled out PR template. :)

**Comment by jguddas** [comment]
> > > > I prefer something like this: icon (38)
> > > 
> > > 
> > > That's not in line whatsoever with preexisting icons I based this on.
> > 
> > 
> > You want it to be consistent with some other icons?
> > What other icons is it based on?
> 
> See our nicely filled out PR template. :)

#1881 #1882

**Comment by jguddas** [comment]
> > #1881 #1882
> 
> I'm not quite sure this alone does the trick, since these icons currently cover two separate use cases (as also illustrated by the tag).
> A) A collection of elements
> B) Copying an element
> 
> While your alternate versions mostly just cover use case A. 🤔

The copying icons also all have round corners.

**Comment by karsa-mistmere** [comment]
> > > #1881 #1882
> > 
> > 
> > I'm not quite sure this alone does the trick, since these icons currently cover two separate use cases (as also illustrated by the tag).
> > A) A collection of elements
> > B) Copying an element
> > While your alternate versions mostly just cover use case A. 🤔
> 
> The copying icons also all have round corners.

But also gaps between the elements.

**Comment by jguddas** [comment]
> > > > #1881 #1882
> > > 
> > > 
> > > I'm not quite sure this alone does the trick, since these icons currently cover two separate use cases (as also illustrated by the tag).
> > > A) A collection of elements
> > > B) Copying an element
> > > While your alternate versions mostly just cover use case A. 🤔
> > 
> > 
> > The copying icons also all have round corners.
> 
> But also gaps between the elements.

True, I feel like adding round corners doesn't destroy the use case for copping and looks immensely better than just a line.

**Comment by karsa-mistmere** [comment]
> True, I feel like adding round corners doesn't destroy the use case for copping and looks immensely better than just a line.

I think it's mostly just personal preference, and while I don't necessarily have strong opinions on either version, we simply must be consistent in our design style.

I propose to close https://github.com/lucide-icons/lucide/pull/1881 & https://github.com/lucide-icons/lucide/pull/1882 for the time being and deal with this proposal in a single PR, since it would introduce a design style that for the time being is completely alien to Lucide, and a lot of icons would need to be updated for the set to remain consistent, including (but most likely not limited to) these (not just the two you opened PRs for):
image

I feel like this is a can of worms that simply cannot be dealt with on an icon by icon basis and (should we decide to do so) would need to be addressed in a single step – including an update to our 2px gap guideline.

Sidenote, if we change our design approach, we could also arguably need to update all of our `*-off` icons:
image

**Comment by jguddas** [comment]
If you want to consolidate it into 1PR, I would suggest changing the target branch from `main` to `collection/round-cornerrs` and pressing merge, rather than close.

image

Tags could look a bit funky, but the rest could definitely be adjusted.

`layers-2` could just be moved to replace `layers`.

**Comment by jguddas** [comment]
> Sidenote, if we change our design approach, we could also arguably need to update all of our *-off icons

I think a gap is usually nicer, but if we can't fit one than I prefer a round connection over a sharp cutoff.

**Pull request merged**
