### PR TITLE
add zero-config icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-04-14 at 13 36 55@2x |

### CODE REVIEW

**Comment by locness3** [comment]
the name...

**Comment by mittalyashu** [comment]
Any suggestions? @locness3 @ericfennis

**Comment by ericfennis** [comment]
What are the reasons to use this icon?

**Comment by mittalyashu** [comment]
Like:
* Game over
* Zero config (as same)

**Comment by mittalyashu** [comment]
@locness3 @ericfennis does the icon usage make sense

**Comment by ericfennis** [comment]
@mittalyashu Yes, I looked on the internet but it's actually used for more things.
Most common:
- In scandinavian languages as a letter.
- indicating a diameter or range etc.
- in math: zero/nothing

https://en.m.wikipedia.org/wiki/%C3%98
https://en.m.wikipedia.org/wiki/Zero_(linguistics)

According to the wikipedia articles, I think the best names are: `slashed-o`, `zero`, `circle-slashed`.

**Comment by locness3** [comment]
`circle-off`?

**Comment by ericfennis** [comment]
It's not really a "off" variant of the circle icon. It's a letter/symbol

**Comment by mittalyashu** [comment]
My vote is for `circle-slashed`

**Comment by ericfennis** [comment]
I'm fine with `circle-slashed`.

**Pull request merged**
