### PR TITLE
Add vue 3 package 

### LINKED ISSUE #292: Vue 3 issue when using the Vue package
## Prerequisites

* Version: lucide-vue@0.15.1
* Are you running from source/master: No
* Are you using a released build: lucide-vue on NPM
* Operating system: MacOs 10.15.7
* Bits: 64bits

## Step to reproduce

- Install a test Vue 3 repo with vitejs ([instructions here](https://vitejs.dev/guide/))
- install lucide-vue with `npm install --save lucide-vue`
- Create a dummy vue component
- Import and use any icon, with example code provided on this repo

## Any message or error

It will throw the following error : `[plugin:vite:vue] Cannot read property 'line' of undefined`
`line` is this example can be as well `color`, or others properties, depending on the icon you try yo import

My guess being that Vue3 change the way the render function work. Can't do much to help, as I'm not sure to understand why this is happening

## Resources

Please see the following screenshot

Screenshot

### PR DESCRIPTION
**Pull request by ericfennis**
Closes #292

### CODE REVIEW

**Comment by AdamSGit** [comment]
Hello @ericfennis ,

What is the current state of this package ? I see it was deployed in preview. Can I help in any way ?

Cheers

**Comment by ericfennis** [comment]
@AdamSGit Thanks for asking. Ignore the preview deployment, that for the our site.
I'm almost there, the icons are working in Vue 3.
I released a alpha release on `lucide-vue-next@0.15.10-alpha.1`.

I have still some things to test and fix. You can help me with testing if you like.

Here I have some topics I need to digg in.

### Typescript
Last week I fixed the types for typescript, I think it is all good, but testing this is welcome!

### Tests
I also need to fix the tests, they failing now because it is still using the Vue test utils I copied from the other vue package. The [vue-test-utils](https://github.com/vuejs/vue-test-utils-next) docs is still in development. I need to figure out how the new api works. Maybe a deep dive in their code will help.

### Typescript autocompletion in Vscode
In the other packages for `react` and `preact` we have nice autocompletion in Vscode, but couldn't get it working with Vue 3. 
I'm not sure if this is supported yet, maybe it is only working in script part of template.
image

**Comment by AdamSGit** [comment]
After some tests, I noticed that the `size` property wasn't working, as `width` and `height` weren't set from it. I made a PR on your forked repo, see [#2](https://github.com/ericfennis/lucide/pull/2)

**Comment by AdamSGit** [comment]
Hello,

I see that the typescript issue is fixed. Is there any other things to take care of ? Maybe you want to update the npm package ? I can do further tests as I use it in some project.

Cheers

**Comment by ericfennis** [comment]
@AdamSGit Sorry I was bit busy with the other package.

I just tested in for a final round and made some last fixes.

**Pull request merged**
