### PR TITLE
Feat: Adds `list-ordered`, `list-unordered`, `list-checks`

### PR DESCRIPTION
**Pull request by ericfennis**
Contributes to: [#766](https://github.com/feathericons/feather/issues/766)
Closes: [#504](https://github.com/feathericons/feather/issues/504)
Closes: [#503](https://github.com/feathericons/feather/issues/503)

I'm a bit struggling with the list icons, so I made some variants.
## Variant A
Based on currrent list icons, keeps the position of the lines. But `list-ordered` is violating the 2px spacing.

## Variant B
Same as A but, adds a `unordered` variant.

## Variant C
Position of the lines are changed to give the 2px spacing to the `list-ordered` and is applied to the others.

image

Let me know what you think!

### CODE REVIEW

**Comment by lscheibel** [comment]
Hmm I'd really like to keep the original bullets from A and to me all other bullets feel a little heavy, especially the new unordered- and checklist.

Did you try @ahtohbi4's designs from https://github.com/feathericons/feather/issues/503?

**Comment by ericfennis** [comment]
Yeah I saw his icons, but the ordered list icon he made is unreadable.

Like this? I added the checks like he made them.
image

**Comment by lscheibel** [comment]
Yeah I like the checks much better on `D`.

For the ordered list one, I'm a little torn. On the one hand I like the little more discernibility of your version but on the other hand I also like the more suggesting, feathery version of @ahtohbi4

What do the others say?

**Comment by ericfennis** [comment]
I like both to. feathery version of @ahtohbi4 is matching the best with the original `list` icon.

But what you thinking of the `ordered-list` icons?
It's violating 2px spacing on D. 🤔

**Review by johnletey — COMMENTED** [review]
@ericfennis I'm a huge fan of these, however, the `list-ordered` icon seems a bit too compact 🤔

**Comment by ericfennis** [comment]
@johnletey yeah I agree, but what I already mentioned this `list-ordered` is hard because, making readable numbers on that scale is almost impossible. Variant C is more readable and has the 2px padding, but the all the list icons need to be adjusted because between the lines need to be more space to be nicely aligned with the numbers.

**Comment by ericfennis** [comment]
Or we do like github?
image

**Comment by locness3** [comment]
> Or we do like github?
Which icons were designed by Cole, btw

**Comment by ericfennis** [comment]
@locness3 haha true!

**Comment by ericfennis** [comment]
I think I like it 🤔.
image

**Pull request merged**
