### PR TITLE
Add `arrow-*-circle` icons (including `esc`ape key)

### PR DESCRIPTION
**Pull request by danielbayley**
<kbd>esc</kbd>

Related to #1002.

### CODE REVIEW

**Comment by danielbayley** [comment]
> The names don't seem right, see https://lucide.dev/icon/arrow-down-circle?search=Arrow

What do you mean?

**Comment by karsa-mistmere** [comment]
`arrow-up-left-circle` should look similar to `arrow-up-circle` and `arrow-left-circle` etc.

**Comment by danielbayley** [comment]
> `arrow-up-left-circle` should look similar to `arrow-up-circle` and `arrow-left-circle` etc.

What do you suggest instead? I gave them generic names, but these were mainly just to accommodate the <kbd>esc</kbd>ape key symbol…

**Comment by karsa-mistmere** [comment]
@danielbayley: I really have no idea. 😅 
I just know that eventually there's going to be a conflict with these.
Maybe something like `arrow-*-from-circle`?

**Review by karsa-mistmere — APPROVED** [review]

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
