### PR TITLE
Sort `rows`/`columns` icons

### PR DESCRIPTION
**Pull request by danielbayley**
Related to #1055, #1156, #1391, #1498, and #1508.

`rows-3` and `columns-3` double as #1156 `panels-top-bottom` and `panels-left-right` variants, respectively.

### CODE REVIEW

**Review by ericfennis — APPROVED** [review]
LGTM

**Comment by karsa-mistmere** [comment]
I think the `-4` variants are a bit too dense, but I'm OK with merging this if @ericfennis and @jguddas are.

**Comment by jguddas** [comment]
Not to be that guy, but what are the use cases?

**Review by ericfennis — APPROVED** [review]

**Comment by ericfennis** [comment]
Usecase: "Splitting up application view in multiple columns or rows"

**Pull request merged**
