### PR TITLE
Optimise `grid`/add [`layout-`]`grid` `move`/`list` improvements + metadata

### PR DESCRIPTION
**Pull request by danielbayley**
Related to #1184 and #1498.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
We do have a separate # icon, so I don't think adding those use cases to `grid-2` is necessary, I definitely do not wish for us to encourage people to use this as a hashmark.

Also, maybe we could call it `grid-lines` or `guidelines` instead? I really hate numbering our alternate designs, don't get me wrong, I'm definitely guilty of having done the same, but I think a qualifier of what makes them unique is much more helpful.

**Comment by danielbayley** [comment]
> maybe we could call it `grid-lines`

@karsa-mistmere Done.

I’ve noticed that occasionally I go to add something I think is missing, then later find it accidentally, having missed it because the search didn’t bring it up due to lacking metadata… For example `frame` here, although different enough in this case.

> I think a qualifier of what makes them unique is much more helpful.

Yeah agreed, where possible…

**Comment by danielbayley** [comment]
> maybe we could call it `grid-lines`

@karsa-mistmere Done.

I’ve noticed that occasionally I go to add something I think is missing, then later find it accidentally, having missed it because the search didn’t bring it up due to lacking metadata… For example `frame` here, although different enough in this case.

> I think a qualifier of what makes them unique is much more helpful.

Yeah agreed, where possible…

**Comment by ericfennis** [comment]
hmm, the plus from `layout-grid-plus` is not aligned on the grid.
This will result in a blurry plus on low res screens. Not sure what we should do. @karsa-mistmere what do you think?
image

**Comment by danielbayley** [comment]
> on low res screens

We need this kind of low-res preview added to the bot!

@ericfennis Not sure either in this case! Is supporting low res screens a higher priority than having certain icons at all? Surely there aren’t too many around by now… Also, technically we ‘support’ 3px stroke width, but many of the icons look like shit at 3px…

**Comment by jguddas** [comment]
> > on low res screens
> 
> We need this kind of low-res preview added to the bot!

https://github.com/jguddas/lucide/commit/fa7623c2f433230cecd5ef740784e08b2eff3bc7

Sorry for it just laying there, it got lost in the migration to the new site.

I don't have time to look at it, so if someone wants to copy it over please do 🙏

**Comment by ericfennis** [comment]
This PR is merged to the lab branch. This PR does not match our [PR template](https://github.com/lucide-icons/lucide/blob/main/.github/pull_request_template.md), which requires valid use cases. To move on we merged this PR to the [lab branch](https://github.com/lucide-icons/lucide/tree/lab), which will be moved to a separate repo in the future.

**Pull request merged**
