### PR TITLE
Improve clarity and readability of packages guides in docs

### PR DESCRIPTION
**Pull request by jackson-jackson**
## What is the purpose of this pull request?

- [ ] New Icon
- [ ] Bug fix
- [ ] New Feature
- [x] Documentation update
- [ ] Other:

### Description
Improve clarity and readability of packages guides in docs.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Review by jguddas — APPROVED** [review]

**Review by ericfennis — APPROVED** [review]
Awesome work, This reads way nicer!

**Comment by ericfennis** [comment]
Maybe you like to review my text written in #1521 as well. I'm not the best writer, but I try my best 😛

**Comment by jackson-jackson** [comment]
They look pretty good so far, but I do see a few areas that can be improved. I'll take a crack at making the necessary adjustments later today. 🙌

**Comment by ericfennis** [comment]
@jackson-jackson You're awesome tnx!

**Pull request merged**
