### PR TITLE
Add `tag-arrow-*` and `delete-forward` icons

### PR DESCRIPTION
**Pull request by danielbayley**
These cover the `debug-stackframe*` _[codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html)_, and also reperesent debugger in Firefox:

Untitled
<br/>
<br/>

Also related to #1042, and #1319.

### CODE REVIEW

**Review by karsa-mistmere — APPROVED** [review]

**Comment by danielbayley** [comment]
Note that these had to be renamed, as they were conflicting with `arrow-*-square` icons, since #994 was merged…

**Comment by ericfennis** [comment]
I'm not sure about these names as well. What are other libraries naming these icons?

**Comment by danielbayley** [comment]
> I'm not sure about these names as well. What are other libraries naming these icons?

Well other libraries have different naming schemes… whereas this one tries to be more literal (which I think is better). As mentioned above, these are called `debug-stackframe*` in _codicons_, so no help there…

@ericfennis What about `arrow-pantagon-*`?

**Comment by ericfennis** [comment]
Or maybe `tag-arrow-top`,`tag-arrow-right`, `tag-arrow-bottom, `tag-arrow-left` etc ?

**Comment by jguddas** [comment]
Do we want to generally have the same icon in different orientations?

**Comment by danielbayley** [comment]
> Do we want to generally have the same icon in different orientations?

I’m only interested in the ones pointing right, personally. I just figured they should probably be a set…

But no problem with dropping the others…? @ericfennis @jguddas @karsa-mistmere

**Comment by ericfennis** [comment]
If we drop the others maybe we can think of better name.

Maybe just. `tag-2`?
What is the use case with the dot?

**Comment by danielbayley** [comment]
> Maybe just. `tag-2`?

@ericfennis What about just `tag-right`[`-dot`]?

> What is the use case with the dot?

As [mentioned](https://github.com/lucide-icons/lucide/pull/1039#issue-1662091107) these cover `debug-stackframe` [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html)… So the one with the dot is `debug-stackframe-active`.

**Comment by ericfennis** [comment]
@danielbayley Is it not more convenient to fill the icon for the active state?

**Comment by danielbayley** [comment]
> @danielbayley Is it not more convenient to fill the icon for the active state?

Definitely not more convenient. Not sure even possible, with how VS Code icon themes work…

**Pull request closed without merging**
