### PR TITLE
Add `boombox` icon

### PR DESCRIPTION
**Pull request by danielbayley**
Explored alts:

preview

### CODE REVIEW

**Comment by jguddas** [comment]
How about making one of the circles bigger?

**Comment by karsa-mistmere** [comment]
> How about making one of the circles bigger?

How? It very barely fits as it is.

**Comment by jguddas** [comment]
> > How about making one of the circles bigger?
> 
> How? It very barely fits as it is.

True.

**Review by jguddas — APPROVED** [review]

**Comment by danielbayley** [comment]
> This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 5 days.

Is there no way to remove the `stale` label? @ericfennis

**Comment by danielbayley** [comment]
> How about making one of the circles bigger?

> How? It very barely fits as it is.

@jguddas Yeah obviously can’t do that, but could make one smaller, something like this…?

preview

cc: @karsa-mistmere

**Review by ericfennis — APPROVED** [review]

**Comment by ericfennis** [comment]
For us maintainers, this is useful automation to label stale PRs, so I'm not really in favor of removing this.

**Comment by jguddas** [comment]
> > How about making one of the circles bigger?
> 
> > How? It very barely fits as it is.
> 
> @jguddas Yeah obviously can’t do that, but could make one smaller, something like this…?
> 
> preview
> 
> cc: @karsa-mistmere

Yeah, this looks nice :+1:

**Comment by danielbayley** [comment]
> For us maintainers, this is useful automation to label stale PRs, so I'm not really in favor of removing this.

@ericfennis Sure, I’m not suggesting removing the bot! Just the `stale` label… Or if I misinterpreted that, I mean shouldn’t it ideally remove the label if there are further comments or `push`es?

> Yeah, this looks nice 👍

@jguddas Ok, side by side comparison… Another case for a poll bot. What is the vote? @karsa-mistmere @ericfennis

preview

**Comment by ericfennis** [comment]
@danielbayley yeah that should be nice improvement!

For the icons, Not sure which one I prefer. I vote for them both

**Comment by karsa-mistmere** [comment]
Maybe we could take a page out of `speaker`'s box and make the second circle a simple dot?
boombox

**Comment by ericfennis** [comment]
@karsa-mistmere Not bad idea, then it will also match sort of with the [`radio-receiver` icon](https://lucide.dev/icons/radio-receiver)

**Comment by danielbayley** [comment]
> Maybe we could take a page out of `speaker`'s book and make the second circle a simple dot?

@karsa-mistmere Maybe, but then in the case of `speaker`, the dot is actually the tweeter, not another subwoofer… If I’d bought a boom box that came with a tweeter instead, I’d want a refund! 😅

cc: @ericfennis @jguddas

**Comment by ericfennis** [comment]
I'm okay with this change, what do you think @karsa-mistmere ?

**Comment by karsa-mistmere** [comment]
> I'm okay with this change, what do you think @karsa-mistmere ?

I think I'd rather have one of the other variants, i.e. preferably
boombox
or maybe
boombox-2

**Review by karsa-mistmere — APPROVED** [review]

**Pull request merged**
