### PR TITLE
Add `grip-down-right` icon

### PR DESCRIPTION
**Pull request by ocavue**
## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

This PR adds a new `grip-down-right` icon, shown below.

image

### Icon use case 

This kind of icon is commonly used as a resize handle, at the bottom right corner of a resizable window. 

- Example 1: https://stackoverflow.com/questions/55166626/how-are-dots-in-the-corner-called-and-how-to-disable-them)
- Example 2: https://superuser.com/questions/614020/where-does-the-resize-handle-in-browser-textboxes-come-from

### Alternative icon designs 

For the use case of the resize handle, browsers show multiple slashes at the bottom right corner. It seems that Lucide doesn't have this either so I will submit a [separate PR](https://github.com/lucide-icons/lucide/pull/1793) for this icon. 

image

image

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: `grip`
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Review by jguddas — CHANGES_REQUESTED** [review]
- Icon is not visually centered
- Name describes usecase rather than content

**Comment by karsa-mistmere** [comment]
> * Icon is not visually centered
> * Name describes usecase rather than content

I think in this instance the icon not being centered is intentional. 🤔

**Comment by ocavue** [comment]
> Icon is not visually centered

I don't see a way to make it visually centered. It's just an icon that uses a corner of the space, like existing [rss](https://lucide.dev/icons/rss), [move-3d](https://lucide.dev/icons/move-3d) and [triangle-right](https://lucide.dev/icons/triangle-right).

> Name describes usecase rather than content

There are already three [`grip` icons](https://lucide.dev/icons/?focus=&search=grip). It seems that my `grip-down-right` just follows the existing pattern.

**Review by ericfennis — APPROVED** [review]
I don't see why we shouldn't add this

**Pull request closed without merging**
