### PR TITLE
feat: add logo

### PR DESCRIPTION
**Pull request by ericfennis**
Add new logo!
image

### CODE REVIEW

**Comment by ericfennis** [comment]
Yeah let's first get an agree on the the color.

**Comment by delnyn** [comment]
Which font is used?

**Comment by delnyn** [comment]
Cover(1)

**Comment by ericfennis** [comment]
Mutka

https://fonts.google.com/specimen/Mukta

**Comment by ericfennis** [comment]
Nice looking good

**Comment by delnyn** [comment]
Thanks

**Comment by delnyn** [comment]
Shouldn't we put the logo on the website?

**Pull request merged**
