### PR TITLE
feat(icons): added `volleyball` icon

### PR DESCRIPTION
**Pull request by jguddas**
#1978

## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

Adds new `volleyball` icon

### Icon use case 

- showing volleyball courts on a map

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [x] The icons were originally created in #1304 by @danielbayley 
- [ ] I've based them on the following Lucide icons: 
- [ ] I've based them on the following design: 

### Naming 

- [ ] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to two points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by jguddas** [comment]
Is that a sufficient enough use case?
Is the name good, or should it be `ball-volleyball` instead?

**Comment by danielbayley** [comment]
Nice one @jguddas, do all of my previous icons that got merged into `lab` have to be submitted one at a time now? 😖

**Comment by jguddas** [comment]
> do all of my previous icons that got merged into lab have to be submitted one at a time now? 😖

They should always be submitted one at a time IMO, otherwise they are never gonna get merged.

---

I have this little script for now. Ideally lucide studio would handle moving things between branches.

```bash
grab-lab () {
  git fetch origin lab;
  git checkout main;
  git checkout -b gbc studio/$1;
  git checkout origin/lab icons/$1.svg icons/$1.json
  git commit -m "chore: pull `$1` icon from lab branch"
}
```

**Comment by danielbayley** [comment]
> I have this little script for now.

@jguddas Nice, maybe this can be simplified, and expanded on with [`gh` CLI](https://cli.github.com/manual/gh_pr)…

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
