### PR TITLE
add utensils icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-03-12 at 12 59 06@2x |

Reference https://github.com/lucide-icons/lucide/issues/119

### CODE REVIEW

**Comment by locness3** [comment]
may want seperate icons with appropriate tags too

**Comment by mittalyashu** [comment]
@locness3 sure

But then, there is a also very common use-case for using utensils as icon too.

**Comment by locness3** [comment]
Yeah but both is good

**Comment by ericfennis** [comment]
Hmm I don't know with this handles. Maybe we can try single line handles?
Maybe from this thread? https://github.com/feathericons/feather/issues/552

**Comment by mittalyashu** [comment]
Oh! That's interesting. Will try that.

**Pull request closed without merging**
