### PR TITLE
Fix `folder-git` icons

### PR DESCRIPTION
**Pull request by danielbayley**
Oops, looks like some `class`es sneaked through, because of the issue (before it was) fixed in #1126…

But also, on a closely related note, what do we think of these? @karsa-mistmere @ericfennis @jguddas 

I’m looking for some kind of `folder-root` (`git` repo or otherwise) icon, for the file explorer/tree in my VS Code extension…

Untitled

Untitled

Related to #1009.

### CODE REVIEW

**Comment by jguddas** [comment]
> I’m looking for some kind of folder-root (git repo or otherwise) icon, for the file explorer/tree in my VS Code extension…

Wouldn't drive(hard-drive (1)) cover most use cases?

**Comment by jguddas** [comment]
@karsa-mistmere so cool :tada: 
image

**Comment by danielbayley** [comment]
> Wouldn't drive(hard-drive (1)) cover most use cases?

Well the root would be one or more project folders, not the root of the hard drive…

**Comment by jguddas** [comment]
I don't know what icon would mark something as project root, I don't associate anything with it :man_shrugging:

**Comment by danielbayley** [comment]
> I don't know what icon would mark something as project root, I don't associate anything with it 🤷‍♂️

I mean in VS Code, and Atom, root folders have a different icon than normal/subfolders…

Untitled

Untitled

**Comment by karsa-mistmere** [comment]
@danielbayley I don't really associate "project root" with any image, I guess `folder-dot` could work and still have generic usages, but let's make sure to use the same dot for all of these (`bell-dot`, `braces-dot` etc)

**Review by karsa-mistmere — CHANGES_REQUESTED** [review]

**Review by karsa-mistmere — APPROVED** [review]

**Pull request merged**
