### PR TITLE
Add `eye-closed` icon

### PR DESCRIPTION
**Pull request by danielbayley**
Also [wal]nut/leaf…

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
I don't find this particularly recognisable, the alternate use cases are also a bit dubious, I'd vote against merging this as it currently is.

**Comment by ericfennis** [comment]
I agree with @karsa-mistmere, also the use case is missing.

**Comment by danielbayley** [comment]
> the use case is missing.

@karsa-mistmere @ericfennis Sorry, too many PRs! 

Use case is situations like these being used as e.g watch/unwatch as a simple toggle, where this pair of icons are overlayed on top of each other…

Untitled

**Comment by jguddas** [comment]
Another use case is for password fields and such.

What about adding a bit of curvature to the eyelid?

**Comment by danielbayley** [comment]
> Another use case is for password fields and such.

Yeah, another good example!

> What about adding a bit of curvature to the eyelid?

I can’t `push`, since this is now closed (a bit of a silly limitation of GitHub I think…) and don’t really want to open a new PR for the same thing @ericfennis…

Untitled

Untitled

**Pull request closed without merging**
