### PR TITLE
Fix YouTube icon appearance with fill color

### PR DESCRIPTION
**Pull request by wojtekmaj**
When fill color was applied to YouTube icon, it appears as a rectangle with rounded corners, nothing more:

Zrzut ekranu 2023-04-11 o 09 39 58

This PR fixes that by replacing polygon with second path added with `fill-rule="evenodd"`.

Zrzut ekranu 2023-04-11 o 09 43 29

The default appaerance remains unchanged. Before:

Zrzut ekranu 2023-04-11 o 09 44 41

After (I swear it's a different screenshot 😆):

Zrzut ekranu 2023-04-11 o 09 44 18

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
Hmm... I'm not sure with #94 being in progress and all, at this point why not just use Simpleicons instead?

https://simpleicons.org/?q=youtube

**Comment by wojtekmaj** [comment]
I'd rather not have multiple icon libraries unless I'm forced to, and it happens that I don't need more brand icons than Lucide offers at a time. I respect that no new icons are added, but I also fail to see the reason not to fix the old ones, no? :)

**Comment by wojtekmaj** [comment]
Can we get this merged, pretty please? 🥺

**Comment by ericfennis** [comment]
Nope sorry we don't accept compound paths. These will nog work well in design programs.

**Pull request closed without merging**
