### PR TITLE
fix(icons): changed `hand` and `pointer` icons

### PR DESCRIPTION
**Pull request by jamiemlaw**
## What is the purpose of this pull request?

- [ ] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other: icon update

### Description

This PR proposes a new series of hand icons, with a more slender and expressive shape, at the cost of a finger.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
As stated in #2344, I'm not really into these changes.

**Comment by jamiemlaw** [comment]
> As stated in #2344, I'm not really into these changes.

Completely fine. I'll leave it between you and @jguddas to battle it out! 😬

**Comment by karsa-mistmere** [comment]
> Completely fine. I'll leave it between you and @jguddas to battle it out! 😬

Let's also not forget that @ericfennis has the deciding vote here.

My case is: there is hardly any precedent of four fingered hand icons, as for hand emojis, [there isn't a single design](https://emojipedia.org/raised-hand#designs) that uses four fingers.

Switching to these will make any future icons that rely on pinky, ring or middle fingers almost completely unfeasible — `hand-metal` is a good example, it's just not recognisable for what it is anymore.

**Comment by jguddas** [comment]
I love them ❤️

**Comment by ericfennis** [comment]
I agree with @karsa-mistmere, we shouldn't do this if we aren't sure about future designs. 

For this reason:
> Switching to these will make any future icons that rely on pinky, ring or middle fingers almost completely unfeasible — hand-metal is a good example, it's just not recognisable for what it is anymore.

But I'm open to researching this design and will suggest that we add this to [lucide-icons/lucide-lab](https://github.com/lucide-icons/lucide-lab) to explore

**Comment by jamiemlaw** [comment]
I feel like this is pretty much a solved problem. Take, for example, Homer Simpson giving the finger, or Fry giving the "Spock" symbol in Futurama—gestures that you would think require all five fingers, but don't. Cartoonists for decades have circumvented the issue of not having all five fingers on one hand.

It also opens up the possibility to include icons that would otherwise be too cramped under the five-finger system, maybe like a hand with splayed fingers, a waving hand, a finger-tap. So, I'd argue on balance it would make more icons possible than it would prohibit.

However, if there's no consensus, I would love to see these at least in the`lab` branch.

**Comment by jguddas** [comment]
Learned something new today:

> Japanese characters usually have all five fingers, and there are different reasons for that: an aversion towards number four due to its similar pronunciation with the word for “death”, the four fingers are considered an offensive reference to the burakumin caste, and the Yakuza tradition of cutting a finger off as punishment.
As a result, many cartoon characters who are typically drawn with four fingers had to be edited to have the fifth finger in order to avoid controversy in Japan.

**Pull request closed without merging**
