### PR TITLE
feat(icons): added `grid-2x2-check` icon

### PR DESCRIPTION
**Pull request by chessurisme**
## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

This PR contains `grid-2x2-check` icon that helps grid icon scenario.

### Icon use case 

- validating data tables
- represent the currently selected grid view option, especially if there are different ways to display the grid (e.g., number of columns, sorting options).
- enabling grid feature
- could signify that particular task within the grid has been finished

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [x] I've based them on the following Lucide icons: `grid-2x2` and `calendar-check`
- [x] I've based them on the following design: [The Noun Project](https://thenounproject.com/icon/data-validation-6183944/) 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by jguddas** [comment]
Not sure if we should Arcify the checkmarks, @karsa-mistmere @ericfennis ?

**Comment by chessurisme** [comment]
> Not sure if we should Arcify the checkmarks, @karsa-mistmere @ericfennis ?

Oh, that would be terrible if we arcify it. One thing is, it doesn't match to `calendar-check`, which I based it upon."

**Comment by jguddas** [comment]
> @chessurisme @jguddas We should keep the symbols like these, otherwise, it will look more like a little arc instead of a check mark.

We could add something like "checkmarks and arrows should remain pointy" to the guidelines

**Comment by chessurisme** [comment]
@jguddas, @ericfennis I've already unarchify it. Everything is good now?

**Review by ericfennis — APPROVED** [review]
Looks good!

**Pull request merged**
