### PR TITLE
Added factory icon

### PR DESCRIPTION
**Pull request by karsa-mistmere**
## Icon Request

* Icon name: factory
* Use case: Used for representing industry, sectors, manufacture, businesses etc.
* _Screenshots_ of similar icons:
image

image

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
https://github.com/lucide-icons/lucide/issues/119

**Comment by ericfennis** [comment]
@karsa-mistmere I think the icon can be a bit more refined. Side by side with the other building icons, the "factory" looks a bit off.
image

**Comment by karsa-mistmere** [comment]
@ericfennis I think you're right, I've increased the size to match the others, this is what they currently look like:
factory

**Comment by ericfennis** [comment]
@karsa-mistmere Nice this is better.
One idea, I don't know if you agree with me.
My feeling the icon feels a bit empty, maybe we can try add some windows.

My take:
image

I'm curious what you think.

**Comment by karsa-mistmere** [comment]
Oooh, love it!

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
