### PR TITLE
Hand-optimizations for size

### PR DESCRIPTION
**Pull request by aschaap**
Some optimization types are separated into their own commit, in case these are found to be objectionable.

No new icons, just size reductions where the final result is effectively or exactly identical.

Relevant issue: #902

### CODE REVIEW

**Comment by aschaap** [comment]
I see <use /> is not rendered properly by the workflow.

**Comment by karsa-mistmere** [comment]
@aschaap: I've found multiple instances where separate paths have been merged into a single one, this is something we've deliberately chosen not to do as such compound paths sometimes render incorrectly in Figma amongst others.

(E.g. the two separate lines of arrows have been merged).

**Comment by karsa-mistmere** [comment]
> I see <use /> is not rendered properly by the GitHub Action.

Not sure we even have support for `<use>` in general, it might also break font outlining, we'll have to check.

**Comment by aschaap** [comment]
> @aschaap: I've found multiple instances where separate paths have been merged into a single one, this is something we've deliberately chosen not to do as such compound paths sometimes render incorrectly in Figma amongst others.
> 
> (E.g. the two separate lines of arrows have been merged).

Interesting, I found you in #936 mentioning Figma also does not render zero-length paths with caps as dots.

Is this decision to avoid compound paths (and any others like it) documented anywhere beyond the Readme/website? I.e., are there other Figma limitations to be aware of, and are there other similarly limited use cases to support?

**Comment by karsa-mistmere** [comment]
> Is this decision to avoid compound paths (and any others like it) documented anywhere beyond the Readme/website?

It isn't, but I guess we should probably add this (and some others) to the [icon design guide](https://lucide.dev/docs/icon-design-guide), thanks for bringing this to my attention. In fact the guidelines are in dire need of some rewrite anyway: #650

**Comment by aschaap** [comment]
Thank you for the quick response. I found a generic 'improve SVG support' https://forum.figma.com/t/improve-svg-support/2505 dating back to April 2021. Do you know whether there is an issue for the Figma SVG path problems? 

If Figma's SVG support is an outlier, would it make sense to adapt the package exporter to separate the combined paths instead?

**Comment by jguddas** [comment]
I'm working on automating some of those optimizations.
One question, which elements are preferred over `path`?

My opinion:

- `rect`, `circle`, `ellipse` should be used instead of `path`.
- `path` should be used instead of `line`, `polygon`, `polyline`.

You can already do things like decompounding and converting `line`, `polygon`, `polyline` to `path` using https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit.

But I haven't built the `path` to `rect`/`circle`/`ellipse` feature, and I wanted to ask your opinion first.

**Comment by aschaap** [comment]
@jguddas : I agree with your opinion, but would add nuance to the preference of `rect` over `path`: `rect` with `rx` is shorter than the equivalent `path` with arcs, but without `rx` a `path` is often shorter.

As for `circle`, I'm not sure one can create a truly equivalent `path`; converting `path' to `circle' would require some loss of precision/approximate matching.

**Comment by ericfennis** [comment]
@aschaap Can you rebase, your PR. I opmized the rest of the icons, so this PR should be a bit cleaner now.

**Comment by aschaap** [comment]
@ericfennis Your optimization PR #1025 seems to only rearrange attributes? If you used a tool for this, would it make sense to solve all the merge conflicts it creates? It would seem easier to reapply them after this PR, unless I'm missing something.

**Comment by ericfennis** [comment]
@aschaap I thought you were optimizing the icons by accident. So I thought to do it I a separate PR we could see you changes better. Are your changes now gone after rebasing?

**Comment by aschaap** [comment]
I optimized icons with the intention of doing so (along with learning more of the SVG Path spec). Rebasing does not eliminate my changes, and is taking time due to having to merge it with rearranged attributes.

**Pull request closed without merging**
