### PR TITLE
Optimise/add missing `check`[`-*`] icon/s

### PR DESCRIPTION
**Pull request by danielbayley**
`check-square`[`-2`] was missing, plus these were inconsistent with other `check-`[`*`/`2`] icons, in that the `-2` variation is for when the check extends outside of it’s shape, as opposed to the original where it should be contained inside…

### CODE REVIEW

**Review by ericfennis — COMMENTED** [review]
Nice icons!

Not sure if we need to switch the `check` and `check-2`. I agree your change should be the how it should be. But the people who are using Lucide upgrading to a new version are getting surprised with a new check icon, not sure if we should do this.

**Comment by danielbayley** [comment]
> Not sure if we need to switch the `check` and `check-2`. I agree your change should be the how it should be. But the people who are using Lucide upgrading to a new version are getting surprised with a new check icon, not sure if we should do this.

So many inconsistencies when you really look at the whole set :/

@ericfennis Ok, switched them back now…

**Comment by karsa-mistmere** [comment]
I think we need better names instead of the `-2` suffixes to begin with. 🤔

**Comment by danielbayley** [comment]
> I think we need better names instead of the `-2` suffixes to begin with. 🤔

@karsa-mistmere Agreed where possible, but that particular can of worms isn’t specific to this PR. I think that should be addressed separately, because a lot of these kind of variants already have this numbered naming scheme as it stands…

**Pull request merged**
