### PR TITLE
add lightbulb-off icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-02-03 at 22 25 14@2x |

### CODE REVIEW

**Comment by ericfennis** [comment]
@mittalyashu Looks a bit off, I think for one side of the slash you have to have 2px spacing, see other `-off` icons

**Comment by mittalyashu** [comment]
@ericfennis something like this?

| Preview |
| --- |
| CleanShot 2021-02-05 at 10 08 29@2x |

**Comment by mittalyashu** [comment]
@ericfennis fixed the icon

**Review by ericfennis — COMMENTED** [review]
I think It looks better if we extend the second bottom line a bit.
image

**Comment by mittalyashu** [comment]
> https://github.com/lucide-icons/lucide/pull/206#pullrequestreview-592135081

You mean the first or second icon

**Comment by ericfennis** [comment]
@mittalyashu the first one

**Comment by mittalyashu** [comment]
okay, let me try.

**Review by ericfennis — APPROVED** [review]
nice looks good!

**Pull request merged**
