### PR TITLE
Add indentation icons in/out

### PR DESCRIPTION
**Pull request by Themistoklis**
Indent icon:
indent_grid

Outdent icon:
oudent_grid

### CODE REVIEW

**Comment by locness3** [comment]
Maybe putting some text around the arrow, like :
Capture du 2020-10-19 09-50-56

**Comment by Themistoklis** [comment]
I thought about it but I used three lines to keep it under the same style as the list icons, what do you think?

Otherwise there is plenty of space to add another line and make two of them longer above and bellow the arrow.

indent_grid_2

**Comment by ericfennis** [comment]
@Themistoklis First of all welcome to the Lucide community!
 Nice work.

I think it maybe looks better with chevrons, [https://lucide.netlify.app/?query=chevron](https://lucide.netlify.app/?query=chevron)
And it would be nice if the icons match with the align icons (same lines), [https://lucide.netlify.app/?query=align](https://lucide.netlify.app/?query=align)

**Comment by Themistoklis** [comment]
Both with chevron.

Using the "align" lines:
indent_grid_align_chevron

Using previous lines:
indent_grid_chevron

**Comment by ericfennis** [comment]
Hmm I think I like the bottom one better, the top one looks to tight.
I think we can better refactor the align icons, I think they can have an re-design.

The chevron looks a bit distorted, the lines are not fully 45 deg.

**Comment by Themistoklis** [comment]
I updated the svg with the second model with a 90 deg angle (45 ?).

indent_grid_chevron

**Comment by ericfennis** [comment]
@Themistoklis Nice that looks better. But I looked in to the current 'text-align' icons, and I think they deserve a redesign.
The checked your icon with the four lines, but I think it fit not very well with the rest.
I think the first one you designed looks the best with the chevrons.

I redesigned the align icons, the ones below are your initial designed icons arrows replaced with the chevrons.
I'm curiouse what you think. 

image

**Comment by Themistoklis** [comment]
I think they fit rather well together.

**Comment by ericfennis** [comment]
Nice, I will make a separate PR for the text-align icons, here are the svgs for the indent and outdent.

indent:

```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <polyline points="3 8 7 12 3 16" />
  <line x1="21" y1="12" x2="11" y2="12" />
  <line x1="21" y1="6" x2="11" y2="6" />
  <line x1="21" y1="18" x2="11" y2="18" />
</svg>
```

outdent:

```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <polyline points="7 8 3 12 7 16" />
  <line x1="21" y1="12" x2="11" y2="12" />
  <line x1="21" y1="6" x2="11" y2="6" />
  <line x1="21" y1="18" x2="11" y2="18" />
</svg>
```

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
