### PR TITLE
feat: add `arrow-left-right` icon

### PR DESCRIPTION
**Pull request by wojtekmaj**
`arrow-left-right`
arrow-left-right svg

### CODE REVIEW

**Comment by mittalyashu** [comment]
What do you think? @ericfennis 

This is a preview by keeping 2px padding on all sides.

| Preview |
| --- |
| CleanShot 2021-12-04 at 12 59 48@2x |

**Comment by ericfennis** [comment]
@wojtekmaj Nice icon!! 
I think the improvement from @mittalyashu looks a bit better with the equal paddings. 

Maybe nice addition to add an `arrow-up-down` icon as well.

**Comment by wojtekmaj** [comment]
@mittalyashu @ericfennis Updated!

**Review by ericfennis — APPROVED** [review]
Awesome!

**Pull request merged**
