### PR TITLE
add emoji-metal icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-05-15 at 14 32 43@2x |

### CODE REVIEW

**Comment by locness3** [comment]
I'd name cursor-something

**Comment by mittalyashu** [comment]
I tried to recreate this emoji 🤘

**Comment by mittalyashu** [comment]
Which one is better?

CleanShot 2021-05-15 at 14 36 23@2x

**Comment by ericfennis** [comment]
@mittalyashu I prefer right!

**Comment by mittalyashu** [comment]
@ericfennis LGTM

**Comment by locness3** [comment]
Maybe `hand-metal`? But I think this can go beyond metal culture.

**Comment by ericfennis** [comment]
yeah lets rename it to `hand-metal`.

**Comment by mittalyashu** [comment]
Done

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
