### PR TITLE
Adds computer hardware icons from #527

### PR DESCRIPTION
**Pull request by karsa-mistmere**
closes: #527

### CODE REVIEW

**Comment by ericfennis** [comment]
Nice work!
I checked the figma file once again, and maybe `computer-fan` and `headset` and `satelite` are nice to have icons from that figma file 🤔

**Comment by karsa-mistmere** [comment]
@ericfennis We already have a separate [`fan`](https://lucide.dev/icon/fan?search=fan) icon, not sure if both are needed.
I'll take a look at the others.

**Comment by karsa-mistmere** [comment]
Headset is not compliant, I'm afraid.

I've added `satellite` (and a `satellite-dish` too!).

I'd also love to have a PCIe card standing in for GPU, but not sure about this particular design.
I've tried some draft, but I think I need some feedback:
image

**Comment by ericfennis** [comment]
@karsa-mistmere Yeah true we are already a fan icon, I thought maybe as a `square-fan` or `fan-square` icon.
Nice work for the icons you added.
For the GPU, I like the right one. I think it fits more the lucide style.

**Comment by jguddas** [comment]
> I'd also love to have a PCIe card standing in for GPU, but not sure about this particular design. I've tried some drafts, but I think I need some feedback: image

Looks a bit like a sideways duck head.

**Comment by karsa-mistmere** [comment]
> > I'd also love to have a PCIe card standing in for GPU, but not sure about this particular design. I've tried some drafts, but I think I need some feedback: image
> 
> Looks a bit like a sideways duck head.

Naaaah, it's definitely a parrot. 😄

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
