### PR TITLE
Improve metadata for keys, and modify `arrow-big-*` icons to include `shift` key

### PR DESCRIPTION
**Pull request by danielbayley**
<kbd>⇧</kbd>

See also #1013.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
Too similar to: https://lucide.dev/icon/arrow-big-up?search=arrow-big-up

I'd rather just add the `shift` tag to this existing icon.

**Comment by ericfennis** [comment]
@danielbayley we could try that. Looking at your design of the "big arrow" it seems a bit more balanced than the current big arrows. Maybe we could try a side-by-side comparison and decide?

**Review by ericfennis — APPROVED** [review]
Awesome work @danielbayley !

**Review by ericfennis — CHANGES_REQUESTED** [review]
@danielbayley Sorry one last thing, I think the name for `arrow-big-up-2` is not right because it is not another variant of it. Rename it to: `arrow-big-up-dash` or something, and why don't we add this one also for other directions (if we do, it is maybe better to create a separate PR if we do this)?

**Comment by danielbayley** [comment]
>  and why don't we add this one also for other directions (if we do, it is maybe better to create a separate PR

We could, but it’s just meant to be <kbd>caps lock</kbd>… Not sure what use case for the others would be?

**Comment by ericfennis** [comment]
@danielbayley Not sure as well but best to keep the generic, so adding them is possible

**Review by ericfennis — APPROVED** [review]

**Comment by karsa-mistmere** [comment]
Hm... I could've sworn that's what I'd originally seen in this PR, but what do you think of something more like this for `arrow-big-up-dash`?

image

**Comment by danielbayley** [comment]
> what do you think of something more like this

@karsa-mistmere Implemented…

**Pull request merged**
