### PR TITLE
Add `concierge`/hospitality/hotel icons

### PR DESCRIPTION
**Pull request by danielbayley**
> an alternative to `bell-dot`. I personally prefer the `concierge-bell`, but it doesn’t currently have a `*-dot` variation for notifications…

Untitled
<br/>
<br/>

`chevrons-up-down-square` represents elevator. Also altered/renamed `square-code` to `chevrons-left-right-square` (and `square-dashed-bottom-code`) from #1068 to match this.

Explored alts:

preview

### CODE REVIEW

**Review by jguddas — APPROVED** [review]
Noice.

**Comment by karsa-mistmere** [comment]
What's the use case for the new dot variant?

**Comment by danielbayley** [comment]
> What's the use case for the new dot variant?

As an alternative to `bell-dot`. I personally prefer the `concierge-bell`, but it doesn’t currently have a `*-dot` variation for notifications…

Untitled

**Comment by karsa-mistmere** [comment]
Not totally about this use case to be honest, but whatever rings your bell. 🤪 

Maybe an alternate dot placement?
image

**Comment by jguddas** [comment]
Top right makes more sens to me, after all the base is not what is making the noise.

**Comment by danielbayley** [comment]
> Top right makes more sens to me, after all the base is not what is making the noise.

Yeah, plus consistent with the placement of other `*-dot` icons…

**Comment by karsa-mistmere** [comment]
I don't think the dot represents noise. 😁

**Comment by danielbayley** [comment]
> This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 5 days.

😢

**Comment by karsa-mistmere** [comment]
`arrows-up-down-square` and `intercom` are too large.

**Comment by jguddas** [comment]
`stairs` does not feel centered.

**Comment by ericfennis** [comment]
This PR is merged to the lab branch. This PR does not match our [PR template](https://github.com/lucide-icons/lucide/blob/main/.github/pull_request_template.md), which requires valid use cases. To move on we merged this PR to the [lab branch](https://github.com/lucide-icons/lucide/tree/lab), which will be moved to a separate repo in the future.

**Pull request merged**
