### PR TITLE
Refine `helping-hand`/add `hand-*` icons

### LINKED ISSUE #1322: Add money in hand icon
helping-hand-money

Not sure if this really works, trying to create a icon based on helping hand for savings 

* Icon name: helping-hand-money
* Use case: offers, banking

Similar icons 
moneyhand

### PR DESCRIPTION
**Pull request by danielbayley**
Closes #1322.

### CODE REVIEW

**Comment by jguddas** [comment]
I like the `hand-platter` one.

**Comment by KayleyHill** [comment]
@danielbayley how about a heart hand icon using your template?
file-heart

**Comment by xnousnow** [comment]
Looks way better than before!

**Comment by xnousnow** [comment]
It seems the icon is ready to get added.. Does anyone have negative opinions on these? :D

**Review by ericfennis — COMMENTED** [review]
Sorry for the late reply, I got a bit overwhelmed by all the PRs.

@danielbayley I'm not sure about the `thumbs-up-down` icon, It's a bit of sense to me and is not very recognizable.

**Comment by ericfennis** [comment]
To move on and to keep focus on closing the linked issue I've removed the `thumbs-up-down` icon, I think we should iterate on it more.

Awesome icons @danielbayley!

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
