### PR TITLE
add power-off icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-02-03 at 22 37 15@2x |

### CODE REVIEW

**Comment by locness3** [comment]
What's the use case?

**Comment by mittalyashu** [comment]
> What's the use case?

For instance, if a cloud hosting site wants to show if the server is on/off.

**Comment by ericfennis** [comment]
Hmm I don't know, this icon already presenting if something is on or off. 🤔

**Comment by mittalyashu** [comment]
@ericfennis the `power-off` icon doesn't exists

CleanShot 2021-02-07 at 21 47 41@2x

**Review by ericfennis — APPROVED** [review]
I think I don't know a direct use case, but there will be possible ones I guess.

**Comment by mittalyashu** [comment]
@ericfennis @locness3 is there any other change required to be made in this PR?

**Comment by ericfennis** [comment]
@mittalyashu It's allright!

**Pull request merged**
