### PR TITLE
fix(icons): changed `search-code` icon

### PR DESCRIPTION
**Pull request by jguddas**
## What is the purpose of this pull request?
- [x] Other: Icon update

### Description
Increase size.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
I prefer the before. 🤔

**Comment by jguddas** [comment]
> I prefer the before. 🤔

It felt a bit cramped, but that's just a feel thing.

**Review by ericfennis — COMMENTED** [review]
Hmm, this created half pixels

**Comment by karsa-mistmere** [comment]
> Hmm, this adds half pixels. Not sure either

That was also my issue, but to be fair, it kinda looks better at 100% 
image

Still, should we update this, a lot of other icons should be updated to match `square-code`, `file-code`, `message-code` etc etc etc

**Comment by jguddas** [comment]
If you are happy with this I can update the rest of the code icons.

**Comment by jguddas** [comment]
I ran my little magic command to apply changes accross icons automagically.

```sh
magic(){old=$(mktemp) && pwd="$(pwd)" && git show main:icons/$1.svg >| "$old" && pushd ../lucide-studio && time bun run magic.ts $old $pwd/icons/$1.svg $pwd/icons/*.svg && popd}

magic search-code
```

**Comment by ericfennis** [comment]
@karsa-mistmere Yeah true, looks better on 100%. Angled paths always add a bit of half pixels. We should go for it.

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
