### PR TITLE
add alphabet-a icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-03-09 at 10 40 36@2x |

### CODE REVIEW

**Comment by locness3** [comment]
maybe just `a`?

**Comment by mittalyashu** [comment]
I think adding "alphabet" before file name is more descriptive.

> An alphabet is a standardized set of basic written symbols or graphemes that represent the phonemes of certain spoken languages.

**Comment by locness3** [comment]
This implies more alphabet icons then

**Comment by mittalyashu** [comment]
okay

**Comment by ericfennis** [comment]
We should not adding typography, see thread in #327.

**Pull request closed without merging**
