### PR TITLE
Migration to Svelte 4

### LINKED ISSUE #1382: Add support for Svelte 4
Svelte 4 was released today and I'd love to use `lucide-svelte` with it

### PR DESCRIPTION
**Pull request by softwarecurator**
closes #1382

### CODE REVIEW

**Comment by xnousnow** [comment]
Is there any `SvelteComponentTyped`? Because of the [change](https://svelte.dev/docs/v4-migration-guide#sveltecomponenttyped-is-deprecated), we can just use `SvelteComponent` instead of it.

**Comment by ericfennis** [comment]
@softwarecurator Nice work if this directly works by simply changing the versions. 
Can you update the lockfile?

**Comment by itenisz** [comment]
Need to update peerDependencies to v4 too.

**Comment by softwarecurator** [comment]
> @softwarecurator Nice work if this directly works by simply changing the versions. Can you update the lockfile?

done!

**Comment by ericfennis** [comment]
@softwarecurator Looks like the tests are failing 😞

**Comment by itenisz** [comment]
> @softwarecurator Looks like the tests are failing 😞

@softwarecurator It seems need to upgrade @testing-library/svelte to the latest version to pass the test, it supports svelte 4 from version 4.

**Comment by t-miller** [comment]
There are a few outdated peer libraries in addition to @testing-library/svelte. [I have a PR for svelte-strip](https://github.com/sciactive/svelte-strip/pull/4), and I think Vite might need a bump too.

**Comment by ericfennis** [comment]
Jumped into it, @itenisz was correct testing library and Vite needed a bump as well. Resulting in Vite updating for all Lucide packages. So created PR #1414 with all the changes. Thanks, everyone for helping!

**Pull request closed without merging**
