### PR TITLE
add person icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-05-01 at 15 12 05@2x |

### CODE REVIEW

**Comment by ericfennis** [comment]
Hmm, I'm not very fan of the design.
I just merged the `person-standing` (accessibility) icon. So what should this icon add?

**Comment by mittalyashu** [comment]
Is the person's head too big?

**Comment by locness3** [comment]
What's the use case?

**Comment by mittalyashu** [comment]
Use case:

* Bathroom
* Person standing

In older version of Google maps there used to be a feature call Peek where you drag the person icon on the map.

**Comment by mittalyashu** [comment]
@locness3 What do you think?

**Comment by locness3** [comment]
Not sure we need that icon.

**Comment by mittalyashu** [comment]
okay 🙂

**Comment by locness3** [comment]
That's only my opinion.

**Comment by delnyn** [comment]
do we need this @ericfennis @locness3 @mittalyashu?

**Comment by ericfennis** [comment]
Hmm I don't know. I think I should match with this one: https://lucide.dev/icon/person-standing

**Comment by mittalyashu** [comment]
This icon can also be used to define "male" gender 🤷‍♂️

image

**Comment by delnyn** [comment]
no, because there should also be an icon for females, and maybe non-binary people.  
(adding a skirt to it doesn't make it a female,  defining a gender by clothes the gender is "supposed to wear" is kind of sexist, or at least very stereotypical)

**Comment by mittalyashu** [comment]
Hmm... I see.

**Pull request closed without merging**
