### PR TITLE
Add color palette icon

### PR DESCRIPTION
**Pull request by ericfennis**
image
100% image

### CODE REVIEW

**Review by locness3 — COMMENTED** [review]
Maybe just `palette` ? Also it does look a little weird, not sure why...

**Comment by Andreto** [comment]
I feel like the dots look a bit small. I know that it's hard to do it any other way though.

**Comment by ericfennis** [comment]
@Andreto yeah it's hard to adjust. I tried some adjustments.
What do you think of this?

image
100% 
image

**Comment by delnyn** [comment]
Oh I wanted a palette icon, since a long time ago! This one's great

**Comment by ericfennis** [comment]
@delnyn Thanks!

**Pull request merged**
