### PR TITLE
Add `versions` icons

### PR DESCRIPTION
**Pull request by danielbayley**
Alternatives:

Untitled

### CODE REVIEW

**Comment by ericfennis** [comment]
Maybe rename this to `file-stack` and `square-stack`?

**Comment by danielbayley** [comment]
> Maybe rename this to `file-stack` and `square-stack`?

@ericfennis Done.

**Comment by jguddas** [comment]
Why is square stack top left to bottom right?

**Comment by danielbayley** [comment]
> Why is square stack top left to bottom right?

@jguddas Because https://lucide.dev/icon/copy is… Whereas https://lucide.dev/icon/files is bottom left to top right.

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
