### PR TITLE
Lucide Flutter packging

### PR DESCRIPTION
**Pull request by marchellodev**
https://pub.dev/packages/lucide_icons

### CODE REVIEW

**Comment by locness3** [comment]
I can't say anything about the code, but this is nice

**Comment by marchellodev** [comment]
@locness3 The code is very short and simple. Also, I'm using this package in my project [sharik](https://github.com/marchellodev/sharik), so it definitely works :)

**Comment by ericfennis** [comment]
@marchellodev Awesome work!

**Comment by ericfennis** [comment]
@marchellodev I will add the workflow for this!

**Comment by marchellodev** [comment]
@ericfennis Thanks! Please let me know if you need any help

**Comment by ericfennis** [comment]
@marchellodev I'm done with the workflows, I will merge this one first.

**Comment by marchellodev** [comment]
The latest version is not updated on pub.dev. Is the workflow working properly? :) @ericfennis

**Comment by ericfennis** [comment]
@marchellodev sorry I was working on it yesterday evening. But I've one bug in the flow. But I know what it is. I will create a fix for I today. 

GitHub actions is always a bit hard to test, so the only way is just try it. :P

**Pull request merged**
