### PR TITLE
add robot icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-05-01 at 16 00 03@2x |

### CODE REVIEW

**Comment by locness3** [comment]
what's the difference with the `bot` icon?

**Comment by mittalyashu** [comment]
The `bot` icon is different from this one.

**Comment by ericfennis** [comment]
@mittalyashu Can you please give a better explanation.
What makes `bot` different from `robot`? 
Or you just want to submit an other variant from robot>

**Comment by locness3** [comment]
> The `bot` icon is different from this one.

Yeah, i know 😁

**Comment by mittalyashu** [comment]
The use case can be bit different based on the context, for instance.

Bot: Is more of related to programatic and automated
Robot: Can mean a machine which interact with human.

**Comment by locness3** [comment]
:thinking:

**Comment by mittalyashu** [comment]
@ericfennis @locness3 Is that convincing? https://github.com/lucide-icons/lucide/pull/310#issuecomment-833188701

**Comment by locness3** [comment]
no

**Comment by mittalyashu** [comment]
@ericfennis any thoughts?

**Comment by locness3** [comment]
> Robot : Can mean a machine which interact with human.

From what I recall, much apps use a "bot" icon for this purpose.

**Comment by mittalyashu** [comment]
then how about `bot-2`?

**Comment by ericfennis** [comment]
@mittalyashu If I can be honest I don't really like the design. I think it's not fitting with the rest of the icons.
I don't know why. Maybe it's a bit too abstract.
But that's my opinion, if other people like it (give thumbs up for example), I maybe consider to approve it as well.

**Comment by mittalyashu** [comment]
Okay :)

**Comment by locness3** [comment]
This icon doesn't have much approval, so I' m closing this.

**Pull request closed without merging**
