### PR TITLE
feat(icons): added `saturn` icon

### PR DESCRIPTION
**Pull request by Footagesus**
## What is the purpose of this pull request?
- [x] New Icon

### Description
Added new `saturn` icon.

### Icon use case

The Saturn icon represents a planet with rings and is used to represent space, astronomy, or futuristic ideas in applications and interfaces.

### Concept

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license

- [ ] The icons are solely my own creation.
- [x] The icons were originally created in #<issueNumber> by @Footagesus
- [x] I've based them on the following Lucide icons: `layers-circle`
- [ ] I've based them on the following design: 

### Naming

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design

- [ ] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [ ] I've made sure that the icons look sharp on low DPI displays.
- [ ] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [ ] I've made sure that the icons are visually centered.
- [ ] I've correctly optimized all icons to three points of precision.

## Before Submitting
- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [ ] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
Feels far too small and the ring has a gap guideline violation, also duplicates https://lucide.dev/icons/lab/planet

**Comment by Footagesus** [comment]
I couldn't find this icon on the site

**Comment by karsa-mistmere** [comment]
> I couldn't find this icon on the site

It's still in our lab branch, you have to select Lab on the site:
image

The reason it's in lab and not main is exactly why this PR won't either go through as is: it has severe gap guideline violations.

Something like this could work, I guess:

<a title="Open lucide studio" target="_blank" href="https://studio.lucide.dev/edit?value=1.LIFgdArAbABAjOAnFAhnAzGK6aYOywYTwAMcJYIAtOZQNp0BEAxgJYBOzANgKaMA0AbxYAPRgC44AJn4sAnhOmz2EgBwBfALqagA">icons<br/>Open lucide studio</a>

**Comment by jguddas** [comment]
> > I couldn't find this icon on the site
> 
> It's still in our lab branch, you have to select Lab on the site: image
> 
> The reason it's in lab and not main is exactly why this PR won't either go through as is: it has severe gap guideline violations.
> 
> Something like this could work, I guess:
> 
> [iconsOpen lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M4.57+14.97a13.63+3.74+135+1+0+10.4-10.4%22+/%3E%3Ccircle+cx=%2212%22+cy=%2212%22+r=%228%22+/%3E)

Your version is pretty cute, do we have a good list of use cases for the icon.

> The Saturn icon represents a planet with rings and is used to represent space, astronomy, or futuristic ideas in applications and interfaces.

@Footagesus i.e. don't tell me what the icon represents, tell me places where it would be used.

Only "applications and interfaces" is not specific enough.

**Comment by Footagesus** [comment]
OK! Thank you

**Pull request closed without merging**
