### PR TITLE
Add `key` variants

### PR DESCRIPTION
**Pull request by danielbayley**

### CODE REVIEW

**Comment by jguddas** [comment]
The tip feels a bit heavy.

**Review by ericfennis — APPROVED** [review]
Nice!

**Comment by danielbayley** [comment]
I think the existing `key` is a bit weak… What do you guys think of replacing it with `key-2`, and just having these 2 variants?

**Comment by jguddas** [comment]
I quite like the current `key` icon, not a fan of those more realistic options, it's just not cute enough.

My vote is for keeping it like it is.

**Comment by karsa-mistmere** [comment]
In hindsight, maybe we could do with lower density?
image
image

**Comment by karsa-mistmere** [comment]
> > In hindsight, maybe we could do with lower density?
> 
> @karsa-mistmere That’s basically what I had originally! 😆

Similar, but not quite:
image

**Comment by danielbayley** [comment]
> In hindsight, maybe we could do with lower density?

@karsa-mistmere `push`ed… Looking good now 👍🏼

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
