### PR TITLE
Add `shopping-basket` icon

### PR DESCRIPTION
**Pull request by danielbayley**

### CODE REVIEW

**Comment by jguddas** [comment]
The `shoping-bag` looks cute and a bit big?

**Comment by danielbayley** [comment]
> The `shoping-bag` looks cute and a bit big?

@jguddas It [already exists](https://lucide.dev/icons/shopping-bag), I just optimised it… Do we think it should be slightly smaller? @karsa-mistmere @ericfennis

**Comment by karsa-mistmere** [comment]
While it is in fact a bit too large, I don't think making it more square-ish is the way to go, since then it looks less and less like a shopping bag. I tried to make it narrower (the same dimensions as `tablet`), but that doesn't feel great either:
image

I think we should maybe just keep it as it is.

**Review by karsa-mistmere — APPROVED** [review]

**Review by ericfennis — APPROVED** [review]
@danielbayley Nice work!

**Pull request merged**
