### PR TITLE
Add `lucide-react-native` package

### LINKED ISSUE #394: React Native support through Expo
Perhaps an easier way to add support is via https://icons.expo.fyi/, rather than creating and mantain a new package

How to add the icon library to the expo project: https://github.com/expo/vector-icons

### PR DESCRIPTION
**Pull request by wojtekmaj**
Closes #394

Alternative to #472

Adds `lucide-react-native` package based on `lucide-react` with [this patch](https://github.com/lucide-icons/lucide/issues/394#issuecomment-9810720130) applied, and not much else. Looks like it's the easiest way to make it React Native compatible.

Note: We're running this patched version in production in our React Native apps for nearly a year now.

### CODE REVIEW

**Comment by ericfennis** [comment]
@wojtekmaj Awesome work, this exactly how I imagine it. I will test it.

**Comment by ericfennis** [comment]
Something is going wrong with the imports. I don't know what, maybe we mis something in the build config.
image

**Comment by wojtekmaj** [comment]
Apologies @ericfennis! I messed up the parentheses.

**Comment by wojtekmaj** [comment]
@ericfennis Your PR has been merged, just a heads up. :)

**Comment by ericfennis** [comment]
Nice work, works perfect! tested on Ios and Android,

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
