### PR TITLE
add image-minus icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-02-02 at 15 03 42@2x |

### CODE REVIEW

**Comment by mittalyashu** [comment]
@ericfennis can you run the refactor icon script magic on this PR too.

**Comment by ericfennis** [comment]
@csandman worked on this. `yarn optimize` is fixing icons, if I'm right. If you experience any issues let us know.

**Comment by csandman** [comment]
It looks like the precommit hook worked and it's already formatted/optimized!  Glad to see it.

**Comment by mittalyashu** [comment]
@csandman I don't think so, I had to manually run that `yarn optimize` build to refactor the icons.

**Comment by csandman** [comment]
> @csandman I don't think so, I had to manually run that `yarn optimize` build to refactor the icons.

Did you try committing the file without running the script?  It should optimize during the commit process.

**Comment by mittalyashu** [comment]
> Did you try committing the file without running the script?

The first commit was without refactor, then I had the run the script manually and commit the changes.

> It should optimize during the commit process.

Does this script will only run when using terminal instead of GUI app?

**Comment by csandman** [comment]
@mittalyashu it should be doing it either way, I'll take a look at it tomorrow.

**Review by ericfennis — APPROVED** [review]

**Comment by csandman** [comment]
@mittalyashu The change to add the pre-commit hook was recent however it should definitely be working.  can you please make sure your `package.json` file has the following at the bottom in your local version of the repo?

```json
"husky": {
  "hooks": {
    "pre-commit": "lint-staged"
  }
},
"lint-staged": {
  "icons/*.svg": "npx babel-node ./scripts/optimizeStagedSvgs.js --presets @babel/env"
}
```

And if it does, make sure you run `yarn install` to get those dependencies set up?  I'm very curious if this ends up working!

@ericfennis We might want to add a note in the readme that people should update their local repo before committing any new icons, otherwise people might commit icons which are not consistent with the others and will require future optimization.

**Pull request merged**
