### PR TITLE
add alphabet-b icon

### PR DESCRIPTION
**Pull request by mittalyashu**
| Preview |
| --- |
| CleanShot 2021-05-15 at 11 47 44@2x |

### CODE REVIEW

**Comment by locness3** [comment]
@mittalyashu please use the pull request template...

**Comment by mittalyashu** [comment]
Didn't knew we've PR template, I mostly create a PR directly from VS code.

Will do that next time.

**Comment by MoltenCoffee** [comment]
The B feels a bit off for me. It might be the 'comic sans'-y playfullness of the rounded edges, but I think it's mostly the fact that both the upper and lower counter (the open areas inside) are the same size and shape. Most font families will have the upper counter be slightly smaller than the lower one. 
I'm sorry for nitpicking here, but I have the feeling this 'B' is also a lot more 'playful' than the even more geometric 'A' in #258.

In general though, I'm personally not entirely sure there's really a need for letters. In my experience fonts are really a skill in its own right, and require a lot of work to look natural. I'm also somewhat afraid of a slippery slope, would we need underscores, slashes, and punctuation as well? Cyrilic characters?

**Comment by mikeott** [comment]
@MoltenCoffee I agree. The design language is not quite the same as the rest of the iconography.

@mittalyashu Adding a random letter suggests the rest of the English speaking alphabet should also be considered. And if so, what about numerals? And even then, why only English? This is a slippery slope and seems like a pretty good way to add unnecessary bloat.

An icon is a way to graphically represent something symbolic, a concept or an idea. Letters and numbers are what they are - just letters and numbers and don't require graphical representation to explain what they are, hence, can not be considered icons.

**Comment by mittalyashu** [comment]
Hmm... @mikeott you do make a point.

Okay, closing this PR for now.

@ericfennis what should we do about "A" icon already added to the set.

**Comment by ericfennis** [comment]
I agree with @MoltenCoffee and @mikeott. We should avoid adding typographic. Then we can better consider making a font 😄 . 

@mittalyashu Yeah close it as wel.

**Comment by mikeott** [comment]
@mittalyashu If it helps, there is this: https://lucide.dev/icon/bold

**Comment by mittalyashu** [comment]
> @mittalyashu If it helps, there is this: https://lucide.dev/icon/bold

Wait, when did we had that icon 😂

**Comment by locness3** [comment]
lmao, perfect.

**Comment by fbarikzehi** [comment]
I suggest adding a guideline like `Avoid adding typographic icons` to the PR checklist.

**Pull request closed without merging**
