### PR TITLE
Add split-square icon

### PR DESCRIPTION
**Pull request by Patchethium**
Add the `split block` icon in VSCode's `Jupyter Notebook` mode.

This icon is used in splitting current text cell into two cells at the cursor position.

Screenshot 2023-02-17 00 24 21

Screenshot 2023-02-17 00 25 10

Hope I got the tags right!

### CODE REVIEW

**Comment by ericfennis** [comment]
@Patchethium Nice icon!
I can imagine a horizontal version is useful as well.
So instead of `split-square` we get `split-square-horizontal` and split-square-vertical`.

**Comment by Patchethium** [comment]
Should be okay now.

**Review by ericfennis — CHANGES_REQUESTED** [review]
Nice work!
One final thing in the SVG code.

**Comment by Patchethium** [comment]
Should be okay now.

**Review by ericfennis — APPROVED** [review]
Awesome, good to go!

**Pull request merged**
