### PR TITLE
Add 100% scale variant to GitHub comments icon workflow

### PR DESCRIPTION
**Pull request by danielbayley**
Building on @jguddas excellent work in #946, could we also include a 100% scale (24x24px) preview?

### CODE REVIEW

**Comment by jguddas** [comment]
```diff
         uses: tj-actions/changed-files@v35
         with:
           files: icons/*.svg
+      - name: Generate preview
+        id: generate-preview
+        run: |
+          delimiter="$(openssl rand -hex 8)"
+          echo "body<<$delimiter" >> $GITHUB_OUTPUT
+          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            echo "![$file](https://raw.githubusercontent.com/${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}/icons/$file) "
+          done | tr '\n' ' ' >> $GITHUB_OUTPUT
+          echo >> $GITHUB_OUTPUT
+          echo "$delimiter" >> $GITHUB_OUTPUT
       - name: Generate comment
         id: generate-comment
         run: |
@@ -50,6 +60,7 @@ jobs:
           issue-number: ${{ github.event.pull_request.number }}
           body: |
             ### Added or changed icons
+            ${{ steps.generate-preview.outputs.body }}
             <details>
             <summary>Icon X-rays</summary>
             ${{ steps.generate-comment.outputs.body }}

```

# Result (not tested)

### Added or changed icons
accessibility
<details>
<summary>Icon X-rays</summary>

</details>

**Comment by jguddas** [comment]
We could also add a preview with 3px and 1px stroke width.

**Comment by danielbayley** [comment]
I wonder if we could run similar code on  [`issue_comment`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment)s, so that we can simply paste SVG markup, and have it render in the same way…?

Something like:
~~~ yaml
on:
  issue_comment:
    types: [created]
~~~

**Comment by jguddas** [comment]
https://github.com/lucide-icons/lucide/pull/1180

**Comment by ericfennis** [comment]
Fixed by #1180

**Pull request closed without merging**
