### PR TITLE
Add alternative home icon

### PR DESCRIPTION
**Pull request by Tummerhore**
Preview:
Unbenannt

### CODE REVIEW

**Comment by ericfennis** [comment]
@Tummerhore Welcome to the Lucide Community!

Thanks for opening this.
This icon is very similar to the current [`home`](https://lucide.dev/icon/home) icon.
Can you maybe explain why this is a good addition?

**Comment by locness3** [comment]
Did you update the preview along with your commits?

**Comment by Tummerhore** [comment]
> Did you update the preview along with your commits?
Yes. The preview schows the latest iteration.

> This icon is very similar to the current home icon.
Yeah, you're right. It's just personal taste. While the original icon is ok, I did not like it that much. Maybe some people share that opinion so I made an alternative icon. But since some other people might like the original icon more I did not want to change the original one.
I think it's not wrong to have more alternatives. (Other icon projects like font awesome for example also have a lot of alternatives for one icon.)

**Comment by ericfennis** [comment]
@Tummerhore Good explanation! 
Personally I like the current home icon, but indeed maybe there are more people like to change this.
So for now I keep this one open and if there are more upvotes, we will consider merging this.

**Comment by delnyn** [comment]
I personally think that adding this icon isn't a great idea - it's not really useful

**Comment by ericfennis** [comment]
@delnyn You're right. I'm closing this one for now.

**Pull request closed without merging**
