### PR TITLE
add `piggy-bank` icon

### PR DESCRIPTION
**Pull request by b0b90**
[outdated]
4 New Icons :
piggy-bank
rocking-chair
landmark
gem

### CODE REVIEW

**Comment by nixoncode** [comment]
Looks Great!

**Comment by mittalyashu** [comment]
@b0b90 Can you run the `optimise` script to refactor the icons?

**Comment by locness3** [comment]
Unstale.

**Comment by ericfennis** [comment]
Rocking chair and landmark icons are added. I removed them from the PR.
Gem icon pr #359  is still open and in discussion.

I optimized the piggy-bank icon for you.

**Pull request merged**
