### PR TITLE
Optimize icons

### PR DESCRIPTION
**Pull request by ericfennis**

### CODE REVIEW

**Comment by danielbayley** [comment]
I feel like there should be some kind of CI process/`pre-commit` hook (maybe using `svgo`, along with possibly one or more [plugins](https://github.com/svg/svgo/blob/main/plugins-api.md) even) to automate some of this kind of thing…

**Comment by karsa-mistmere** [comment]
[There is.](https://github.com/lucide-icons/lucide/blob/main/.husky/pre-commit)

**Comment by danielbayley** [comment]
> [There is.](https://github.com/lucide-icons/lucide/blob/main/.husky/pre-commit)

Ah nice! I hadn’t done `pnpm install` and so `husky` wasn’t running the `pre-commit` hook…

Although it seems things like, for example:
~~~
class="s01"
~~~
added by Illustrator slip through…

I seem to remember making a note to put together an `svgo` plugin to remove these myself, but life got in the way…

Can it still not be done without a plugin?

**Comment by ericfennis** [comment]
@danielbayley You can run `pnpm optimize` manually.

**Comment by danielbayley** [comment]
> @danielbayley You can run `pnpm optimize` manually.

Nice, yeah I had been running `npx svgo` before…

Should `pnpm optimize` not be in the `pre-commit` hook too?

It still doesn’t remove e.g `class="st0"` output from Illustrator mind…

**Comment by karsa-mistmere** [comment]
No, we only optimize staged icons in the pre commit hook (see `pnpm lint-staged`).

**Comment by garikAsplund** [comment]
It'd be nice to have a snowflake with 6 arms instead of 4. Should be simple enough. 🙏

**Comment by karsa-mistmere** [comment]
> It'd be nice to have a snowflake with 6 arms instead of 4. Should be simple enough. 🙏

I have one in my drafts already, I'll post it asap.
It's also been bugging me, since real life snowflakes always have sixfold symmetry.

**Comment by garikAsplund** [comment]
Excellent--appreciate it!! I know there are a couple other icons in the mix that have the same unnatural snowflake as part of their design. [See here](https://lucide.dev/icons/?focus=&search=snow).

**Comment by karsa-mistmere** [comment]
> Excellent--appreciate it!! I know there are a couple other icons in the mix that have the same unnatural snowflake as part of their design. [See here](https://lucide.dev/icons/?focus=&search=snow).

PR now open: https://github.com/lucide-icons/lucide/pull/2610

**Pull request merged**
