### PR TITLE
Add Valve Icon

### PR DESCRIPTION
**Pull request by Vadoola**
## What is the purpose of this pull request?

- [x] New Icon
- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description
Adding a Valve icon

### Icon use case 
**Diagrams:** Could be used by diagrams that discuss valves and their functions (such as part of a functional description)
**Industrial HMIs / SCADA:** To show or animate valve state of a valve in a manufacturing plant (what I designed it for)

### Alternative icon designs 
n/a

### Concept 

- [x] I have provided valid use cases for each icon.
- [x] I have not added any a brand or logo icon.
- [x] I have not used any hate symbols.
- [x] I have not included any religious or political imagery.

### Author, credits & license
- [x] The icons are solely my own creation.
- [ ] The icons were originally created in #<issueNumber> by @<githubUser>
- [ ] I've based them on the following Lucide icons: 
- [ ] I've based them on the following design: 

### Naming 

- [x] I've read and followed the [naming conventions](https://lucide.dev/guide/design/icon-design-guide#naming-conventions)
- [x] I've named icons by what they are rather than their use case.
- [x] I've provided meta JSON files in `icons/[iconName].json`.

### Design 

- [x] I've read and followed the [icon design guidelines](https://lucide.dev/guide/design/icon-design-guide)
- [x] I've made sure that the icons look sharp on low DPI displays.
- [x] I've made sure that the icons look consistent with the icon set in size, optical volume and density.
- [x] I've made sure that the icons are visually centered.
- [x] I've correctly optimized all icons to three points of precision.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

**Comment by karsa-mistmere** [comment]
This does not fulfil our icon design guideline requiring a gap of at least 2 pixels between elements.

I'm also not entirely convinced about the design itself, should we add one engineering symbol, there will be no end to them. 😄

Maybe a more "cartoony" valve is more of a fit for Lucide: 
image

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+2v4%22+/%3E%3Cpath+d=%22M14+10.341V7a1+1+0+0+0-1-1h-2a1+1+0+0+0-1+1v3.341%22+/%3E%3Cpath+d=%22M17.197+13H22%22+/%3E%3Cpath+d=%22M2+12v8%22+/%3E%3Cpath+d=%22M2+13h4.803%22+/%3E%3Cpath+d=%22M22+12v8%22+/%3E%3Cpath+d=%22M22+19h-4.803%22+/%3E%3Cpath+d=%22M6.803+19H2%22+/%3E%3Cpath+d=%22M8+2h8%22+/%3E%3Ccircle+cx=%2212%22+cy=%2216%22+r=%226%22+/%3E">icons<br/>Open lucide studio</a>

**Comment by Vadoola** [comment]
Sorry for the delay in responding, I've had a lot going on.

> This does not fulfil our icon design guideline requiring a gap of at least 2 pixels between elements.

I guess it isn't clear to me what is meant here. Looking through the design guidelines i got the impression his gap between elements was between multiple distinct objects. To me the valve is a single objects so there is no other element to be 2px away from. If perhaps the top domed part of the valve and the lower part of the valve are considered 2 distinct objects, the vertical distance from the edge of he dome down is 2px, however if you draw at an angle from the edge of the dome to the top corner of the bottom section of the valve that is less than 2px and can probably be addressed.

> I'm also not entirely convinced about the design itself, should we add one engineering symbol, there will be no end to them. 😄

This is my first time submitting anything to Lucide, there are many categories, and I couldn't find a particular rhyme or reason as to what categories are accepted or not. If Engineering symbols are not something to be desired, then I understand, and feel free to reject the pull request.

> Maybe a more "cartoony" valve is more of a fit for Lucide:

That certainly is a route you could go, if I recall many of the material icon sets I've come across use a similar more "cartoony" looking valve. Unfortunately that style of valve won't suite my purpose, and I'm not sure I have the time right now to try and create/submit icons I don't directly have a use for. If this is the route you think you want to go, feel free to reject this pull request, and submit a valve based on the design you have presented. If you think the one I initially submitted could be adjusted to suite, and you would be willing to consider adding it let me know I'll see what I can do to improve it.

**Comment by karsa-mistmere** [comment]
Hi @Vadoola 

Yes, it's the domed part that is the issue. While the two elements are indeed connected, there _is_ a gap between them, and since there is a gap, it must be at least 2px wide.

My qualm with your submission is that this isn't just a generic symbol meaning "valve", it's a very specific type of valve (a control valve if I'm not mistaken) in what is a very specific context (engineering symbol), that will have little more generic usability other than this very specific use case, and even in this specific use case, some people might be like "oh, but this won't do, because what I would really need is a hand operated globe/ball/needle/plug/gate valve etc".

I'll let @ericfennis decide whether he wants to close this or not.

**Comment by ericfennis** [comment]
Unfortunately, this is not the right fit for this library. For me the `value` should present something else like @karsa-mistmere mentioned something closer to what is recognizable for most people in the world. So I'm in for more of a cartoony approach.

**Pull request closed without merging**
